### ISSUE TITLE
models/InceptionTimePlus.py produces syntax warning under Python 3.8.5

### ISSUE THREAD

**Issue by williamsdoug** [timeseriesAI/tsai#106]
tsai 0.2.17 produces import-time syntax warning for file models/InceptionTimePlus.py under Python 3.8.5.  Warning only occurs when initially importing .py file.  Once module is pre-compiled,  warning will not be reported on subsequent imports.  Use touch or make trivial whitespace change to file to force recompilation and reproduce warning.

````
from tsai.all import *

/media/big_ssd/doug/Documents/GitHub/tsai/tutorial_nbs/tsai/models/InceptionTimePlus.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if stoch_depth is not 0: keep_prob = np.linspace(1, stoch_depth, depth // 3)

````

Existing code at lines 99-100:
````
        if stoch_depth is not 0: keep_prob = np.linspace(1, stoch_depth, depth // 3)
        else: keep_prob = np.array([1] * depth // 3)
````

Proposed change:
````
        if stoch_depth != 0: keep_prob = np.linspace(1, stoch_depth, depth // 3)
        else: keep_prob = np.array([1] * depth // 3)
````

**Comment by oguiza** [comment]
Hi @williamsdoug, 
thanks for creating this issue. I've just uploaded the fixed code into the GitHub repo based on your proposed solution. 
It'd be good if you can confirm it works as expected.

**Comment by williamsdoug** [comment]
Hi @oguiza 

I've confirmed that your tsai update no longer produces an import-time warning under Python 3.8.5.  Also, tutorial notebook 01a_MultiClass_MultiLabel_TSClassification.ipynb that makes reference to InceptionTimePlus appears to run without error.

**Comment by oguiza** [comment]
Thank you @williamsdoug!!
