### ISSUE TITLE
How to create/generate a file like "NATOPS_TRAIN.arff"

### ISSUE THREAD

**Issue by DogarXu** [timeseriesAI/tsai#11]
Thank you for the detailed introduction! However, I am not sure how to create/generate a file like "NATOPS_TRAIN.arff". I know how to convert my data (in csv) to the file like "NATOPSDimension1_Train.arff", which contains only one dimension. How can I combine different dimensions together? Thank you!

**Comment by vrodriguezf** [comment]
Related to this, I have another question. Is there any way o load data in this package without a `.arff` file?

**Comment by Senorelegans** [comment]
bump! would love to import a csv of some type instead of the .arff file

**Comment by oguiza** [comment]
There's not need to use .arff files with `tsai`. You can just create a pandas dataframe, and then select the required columns and transform it into a numpy array. Here's a brief example to simulate how you'd load data from a df:

```
a = np.random.rand(100, 5)
df = pd.DataFrame(a, columns=['a', 'b', 'c', 'd', 'target'])
X = df[['a', 'c', 'd']].values
y = round(df['target'], 0).astype(int)
splits = RandomSplitter()(y)
dsets = TSDatasets(X, y, splits=splits)
dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=64)
xb, yb = first(dls.train)
```
