### ISSUE TITLE
MiniRocketFeatures: got an unexpected keyword argument 'c_in'

### ISSUE THREAD

**Issue by Quaterion** [timeseriesAI/tsai#115]
I try to follow your example code at "in [105]" in the file https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/10_Time_Series_Classification_and_Regression_with_MiniRocket.ipynb

The following code with tsai version 0.2.17 ... 

    from tsai.all import *
    dsid = 'LSST'
    X, y, splits = get_UCR_data(dsid, split_data=False)
    mrf = MiniRocketFeatures(c_in=X.shape[1], seq_len=X.shape[2]).to(default_device())

gives me the following error: 

    TypeError: __init__() got an unexpected keyword argument 'c_in'

**Comment by Johnreidsilver** [comment]
I get this error too

versions:

    fastai==2.3.1
    fastcore==1.3.20
    fastprogress==1.0.0
    torch : 1.8.1+cu102

Python 3.8.5
Ubuntu 20.04.1 LTS

**Comment by oguiza** [comment]
Can you try removing the keywords, l mean doing: 
```
from tsai.all import *
dsid = 'LSST'
X, y, splits = get_UCR_data(dsid, split_data=False)
mrf = MiniRocketFeatures(X.shape[1],X.shape[2]).to(default_device())
```

**Comment by oguiza** [comment]
I will close this issue due to a lack of response. I've tested it and it seems to work well.
