### ISSUE TITLE
progress_bar error in get_UCR_data, fastprogress doesn't take 'comment' argument

### ISSUE THREAD

**Issue by Johnreidsilver** [timeseriesAI/tsai#117]
Hi, maybe I have some incompatibility with the tsai version modules I have installed 

Just loading data with get_UCR_data throws an error

```
line 168, in get_UCR_data
    for i in progress_bar(range(X_train_df.shape[-1]), display=verbose, leave=False):
TypeError: __init__() got an unexpected keyword argument 'comment'
```

versions:
> tsai==0.2.17
> fastai==2.3.1
> fastcore==1.3.20
> fastprogress==1.0.0
> torch : 1.8.1+cu102

Python 3.8.5
Ubuntu 20.04.1 LTS

I just edited out the comment in line 168 of external.py for now

**Comment by ymlea** [comment]
Same error here

**Comment by Modius22** [comment]
Same Error:
Python 3.9.5
Conda Env
On Mac OS X

**Comment by oguiza** [comment]
This seems to be due to a change in fastprogress version. 
I've just removed the comment (which is not essential). It'd be great if you would test that it now works well.

**Comment by oguiza** [comment]
I will close this issue due to a lack of response. Please, reopen if needed.
