### ISSUE TITLE
core.py defined in root and in data

### ISSUE THREAD

**Issue by hvingelby** [timeseriesAI/tsai#12]
The file `core.py` exists both in the root directory and in the data folder of the tsai package. This however is only present in when the package is installed from pip (version 0.1.0) and not on the github repository.

There are differences between e.g. the `TSTensor` class defined in both of the `core.py`.

Are there any reason for having the two versions?

**Comment by oguiza** [comment]
No, I wasn't aware of this. 
In any case I've made a major update to the tsai library and it should work well now. Please, let me know if you still have any issues.
