### ISSUE TITLE
how to load the best model weight?

### ISSUE THREAD

**Issue by cozec** [timeseriesAI/tsai#123]
when the model is load as: "learn = load_learner_all"
Is there a way to load best model, in term of valid acc?

**Comment by dnth** [comment]
In my workflow I use the fastai `SaveModelCallback` to save the best model during training. 

It will look like this in code
`learn.fit(100, lr=1e-4, cbs=[SaveModelCallback(monitor='valid_loss')])`

You can specify which metric to monitor. In the above code, the model will only be saved if there is an improvement in the `valid_loss` metric. You can specify more things in the callback like minimum improvement to the metrics, save with optimizer states, etc... according to the [documentation](https://docs.fast.ai/callback.tracker.html).

**Comment by cozec** [comment]
it seems working. thanks!

**Comment by oguiza** [comment]
Thanks @cozec for your question, and @dnth for providing a very good reply. That's exactly what I do when I want to save the best model for inference. I'll close this issue based on your comments.
