### ISSUE TITLE
limit on time points ?

### ISSUE THREAD

**Issue by ymlea** [timeseriesAI/tsai#127]
Hello,
I'm playing the package with the provided datasets. With sample in shape of batch*var*time_points, I noticed that when the 
time_points is too big, the learner will throw error about dimension match.

For example with dataset:

dsid='HouseholdPowerConsumption1'
X, y, splits = get_regression_data(dsid, split_data=False)
print(dsid, X.shape, y.shape)
HouseholdPowerConsumption1 (1431, 5, 1440) (1431,)

It has 1440 time points.

When I run:
tfms  = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_sample=True, by_var=True)
dls = get_ts_dls(x, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=128)
dls.one_batch()
learn = ts_learner(dls, TSTPlus, metrics=[mae, rmse], cbs=ShowGraph())
learn.lr_find()

I'll get error (from learn.lr_find() )  as below:
RuntimeError: The size of tensor a (512) must match the size of tensor b (1440) at non-singleton dimension 3

Please help !

Thanks!

**Comment by oguiza** [comment]
Hi @ymlea,
The root cause of this issue is twofold.
1. On one side, transformers are pretty memory intensive. To prevent out-of-memory (OOM) errors TSTPlus has a max_seq_len parameter set by default to 512. This means that any time series longer than that is transformed into a 512 one. This usually works well. 
2. But in this case, the dataset has nan values. The previous transformation doesn't work when there are nan values (the system can't assign padding to the shorter time series). 
This combination breaks the model.
What you can do is to set the max_seq_len parameter to None, and reduce the batch size to avoid OOM errors. I've tested it in Colab and the bs can only be 4, which means training will be pretty slow. 
An alternative is to use any other model in the library. The only thing to bear in mind is that other models will require you to remove nan values. You can do it this way: 
```
batch_tfms = [TSStandardize(by_sample=True, by_var=True), Nan2Value()]
```

**Comment by ymlea** [comment]
Thanks for replying, could you please detail where to set max_seq_len=None for both TST and TSTPlus? Thanks

**Comment by williamsdoug** [comment]
Hi @ymlea.  ```help(TST)``` and/or ```help(TSTPlus)```  shows that ```max_seq_len``` appears as one of the optional parameters when creating your instance of the model.

Sample output:
````
class TST(fastai.torch_core.Module)
 |  TST(c_in: int, c_out: int, seq_len: int, max_seq_len: Union[int, NoneType] = None, n_layers: int = 3, 
d_model: int = 128, n_heads: int = 16, d_k: Union[int, NoneType] = None, d_v: Union[int, NoneType] = None, 
d_ff: int = 256, res_dropout: float = 0.1, act: str = 'gelu', fc_dropout: float = 0.0, 
y_range: Union[tuple, NoneType] = None, verbose: bool = False, **kwargs)
````

**Comment by dnth** [comment]
Correct me if i'm wrong but we can pass the `max_seq_len` argument this way right? Since `ts_learner` accepts `kwargs`?

`learn = ts_learner(dls, TSTPlus, metrics=[mae, rmse], cbs=ShowGraph(), max_seq_len=200)
`

**Comment by oguiza** [comment]
Exactly @dnth, that’s the easiest way to use max_seq_len. In this case you might set it to None and pass the entire time series to the attention layers (reducing bs).

**Comment by ymlea** [comment]
Thanks, I’m going to play it with my own data. I will have three preprocessed datasets (training, validation and testing). How do I make dls from here to feed them into model without any further normalization?

**Comment by oguiza** [comment]
Just build a normal dls but don't pass any batch_tfms arguments if you don't want to apply any normalization. 
You can see examples of how to build a dls in the tutorial notebooks.

**Comment by ymlea** [comment]
I have already split my data into train, validation and test datasets(3 pair of  x and y np arrays). How do I make one dls from here for ts_leaner? thanks.

**Comment by dnth** [comment]
@ymlea I had the same question before and it was answered in this [issue](https://github.com/timeseriesAI/tsai/issues/19#issuecomment-724956780) :)

**Comment by oguiza** [comment]
I’m glad you got it to work @ymlea.
The issue is you are using a classification metric (accuracy) in a regression task.
Try it again replacing accuracy by mae (mean absolute error) for example.

**Comment by ymlea** [comment]
Thanks for quick reply. Is there a correlation metric for validation in regressions?

**Comment by ymlea** [comment]
My script runs ok in notebook, but gave me error in console.
![image](https://user-images.githubusercontent.com/84790301/121592677-9b585400-ca00-11eb-944f-c2989777fd86.png)

**Comment by oguiza** [comment]
Try this (without the callback):

learn = ts_learner(dls, TST, metrics=mae)

**Comment by dnth** [comment]
From what I know there isnt an automated way. Most of the time we follow "a rule of thumb" to select them illustrated [here ](https://docs.fast.ai/callback.schedule.html#LRFinder)

Try them out on your dataset :)

**Comment by oguiza** [comment]
I'll close this issue due to a lack of response. If needed, please, reopen it.
