### ISSUE TITLE
TSStandardize not applied during Inference

### ISSUE THREAD

**Issue by meanpenguin** [timeseriesAI/tsai#135]
`fastai     : 2.4   
fastcore   : 1.3.20   
torch      : 1.9.0+cu102   
tsai       : 0.2.18`

When running Regression, 
performing inference does not apply TSStandardize when get_X_preds() is ran for a second time

Scenario 1:
If you learn.fit_one_cycle(), and immediately run get_X_preds(), input is standardized
If you run get_X_preds() a second time, input is no longer standardized

Scenario 2:
If you learn.fit_one_cycle(), and run learn.export()
Then run get_X_preds(), input is not standardized

See linked Notebook
https://colab.research.google.com/drive/1Nf5GVA4oPM32wjl1STVIOEIn2bHCR5J0?usp=sharing

**Comment by meanpenguin** [comment]
Couple of additional Scenarios
Get X, Y, using =get_regression_data()
Get dls using get_ts_dls()
Get learn using ts_learner()
learn.fit_one_cycle()
Perform inference using learn.get_X_preds(X[splits[1]])   (Input Data is standardized)
learn.export(PATH)

Reset Kernel
Get X, Y, using =get_regression_data()
Get Learner using load_learner()
Perform inference using learn.get_X_preds(X[splits[1]])   
==> Input Data is standardized

NOTE: If you export the learner right after training, and before performing an Inference
You are able to load_learner() and the first inference will have the input data standardized

**Comment by oguiza** [comment]
Thanks a lot, @meanpenguin for finding and raising this issue. There was indeed a bug in the code.
I believe it's fixed now. I've re-run your notebook in Colab and it works ok, but it'd be great if you would confirm it.

**Comment by meanpenguin** [comment]
I have confirmed that the the commit fixes the issue.
Thank you for the quick turnaround and the time!
