### ISSUE TITLE
TSStandardize on subset of variables

### ISSUE THREAD

**Issue by oguiza** [timeseriesAI/tsai#141]
### Discussed in https://github.com/timeseriesAI/tsai/discussions/140

<div type='discussions-op-text'>

<sup>Originally posted by **meanpenguin** June 26, 2021</sup>
No sure if it's a bug or I'm not using it as intended....  I need standardize some of the columns

TSStandardize seems like it can take a list of column numbers to standardize

in 
```
    def setups(self, dl: DataLoader):
        ...
        if self.by_var and is_listy(self.by_var):
        ...
```

Since I don't want the first column standardized, calling
```
   batch_tfms = TSStandardize(by_sample=False, by_var=[1,2,3] , verbose=True)
```

Get the following error
```
/usr/local/lib/python3.7/dist-packages/fastcore/dispatch.py in __call__(self, *args, **kwargs)
    116         elif self.inst is not None: f = MethodType(f, self.inst)
    117         elif self.owner is not None: f = MethodType(f, self.owner)
--> 118         return f(*args, **kwargs)
    119 
    120     def __get__(self, inst, owner):

/usr/local/lib/python3.7/dist-packages/tsai/data/preprocessing.py in encodes(self, o)
    131                 self.mean = torch_nanmean(o, dim=self.axes, keepdim=self.axes!=())
    132                 self.std = torch.clamp_min(torch_nanstd(o, dim=self.axes, keepdim=self.axes!=()), self.eps)
--> 133         return (o - self.mean) / self.std
    134 
    135     def decodes(self, o:TSTensor):

/usr/local/lib/python3.7/dist-packages/fastai/torch_core.py in __torch_function__(self, func, types, args, kwargs)
    338         convert=False
    339         if _torch_handled(args, self._opt, func): convert,types = type(self),(torch.Tensor,)
--> 340         res = super().__torch_function__(func, types, args=args, kwargs=kwargs)
    341         if convert: res = convert(res)
    342         if isinstance(res, TensorBase): res.set_meta(self, as_copy=True)

/usr/local/lib/python3.7/dist-packages/torch/_tensor.py in __torch_function__(cls, func, types, args, kwargs)
   1021 
   1022         with _C.DisableTorchFunction():
-> 1023             ret = func(*args, **kwargs)
   1024             return _convert(ret, cls)
   1025 

RuntimeError: The size of tensor a (2) must match the size of tensor b (6) at non-singleton dimension 1
```

See linked Notebook
https://colab.research.google.com/drive/1Nf5GVA4oPM32wjl1STVIOEIn2bHCR5J0?usp=sharing
</div>

**Comment by oguiza** [comment]
I have re-classified this as an issue as it's something that wasn't actually available in `tsai`. I've found this same need on some occasions, so I share this need. It's actually an enhancement more than a bug though.

There's always the option to pass a predefined mean and std with the appropriate shape. Having said that, I've upgraded TSStandardize to be able to standardize data in multiple ways: 
- by_var=False (mean and std is the same for all variables)
- by_var=True (different mean and std by variable)
- by_var=[0,1,3] (different mean and std by variable in the list. For variables not on the list mean=0 and std=1)
- by_var=[0, [1,3]] (different mean and std by variable or list of variables in the list. For variables not on the list mean=0 and std=1)
This upgrade should not only allow to standardize some of the variables only, but also groups of variables. 
I've attached a [gist](https://colab.research.google.com/gist/oguiza/89c65c40370ec7d97626f369f48009ea/bug-tsstandardize.ipynb) to test that this enhancement works, but it'd be good if you can confirm this works as you expect.

**Comment by meanpenguin** [comment]
@oguiza Thank you again!!

Verified the 4 options listed above.  With both Sample=True/False.
Standardization is performing as expected.

I have a question regarding the  "For variables not on the list mean=0 and std=1"
The actual behavior is that the data is not modified in any way (I prefer this option)
So the description should be "For variables not on the list, not modified"?

**Comment by oguiza** [comment]
Thanks, @meanpenguin!
Ok, I've updated the comment in the description of TSStandardize to clarify this. 
I'll close this issue based on your feedback.
