### ISSUE TITLE
Can't install tsai in Colab

### ISSUE THREAD

**Issue by mlgitter** [timeseriesAI/tsai#145]
> [3]
> ## NOTE: UNCOMMENT AND RUN THIS CELL IF YOU NEED TO INSTALL/ UPGRADE TSAI
> stable = False # True: latest version from github, False: stable version in pip
> if stable: 
>     !pip install tsai -U >> /dev/null
> else:      
>     !pip install git+https://github.com/timeseriesAI/tsai.git -U >> /dev/null
> 
> ## NOTE: REMEMBER TO RESTART YOUR RUNTIME ONCE THE INSTALLATION IS FINISHED
>   Running command git clone -q https://github.com/timeseriesAI/tsai.git /tmp/pip-req-build-pmi1a6hz
> ERROR: googleapis-common-protos 1.53.0 has requirement protobuf>=3.12.0, but you'll have protobuf 3.11.2 which is incompatible.
> ERROR: google-api-core 1.26.3 has requirement protobuf>=3.12.0, but you'll have protobuf 3.11.2 which is incompatible.
> ERROR: distributed 2021.6.2 has requirement cloudpickle>=1.5.0, but you'll have cloudpickle 1.3.0 which is incompatible.
> ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.

**Comment by meanpenguin** [comment]
As a workaround for now ...

`!pip install 'matrixprofile>1.1.9'  protobuf==3.12.0 cloudpickle>=1.5.0 imgaug==0.2.6 git+https://github.com/timeseriesAI/tsai.git  -U  >> /dev/null`

Returns one error 
`ERROR: matrixprofile 1.1.10 has requirement protobuf==3.11.2, but you'll have protobuf 3.12.0 which is incompatible.`

But after a reset, the `from tsai.all import *` executes successfully
```
tsai       : 0.2.18
fastai     : 2.4
fastcore   : 1.3.20
torch      : 1.9.0+cu102
```

**Comment by oguiza** [comment]
Hi @mlgitter,
@meanpenguin is right. I understand it's a bit confusing to see the ERROR messages, but they don't impact `tsai`. 
The messages are due to 2 dependencies of `tsai`: scipy and tsfresh.
If you run: 
```
!pip install -U scipy
!pip install -U tsfresh
```
You will see the same error messages. There's nothing I can do about that. Everybody using scipy and/or tsfresh are getting those error messages.
You should follow the instructions on the notebook, and restart the kernel/ runtime when all packages are installed.

**Comment by mlgitter** [comment]
Thanks, @meanpenguin and @oguiza!

After restarting, tsai did import.

**Comment by oguiza** [comment]
Thanks for confirming it works @mlgitter. Based on your feedback, I'll close this issue.
