### ISSUE TITLE
problem downloading datasets 

### ISSUE THREAD

**Issue by mlgitter** [timeseriesAI/tsai#147]
yet zenodo.org is can be accessed, at least from my machine
there is problem downloading datasets

```
dsid = 'm1_yearly_dataset'
X = get_Monash_forecasting_data(dsid, force_download=True, remove_from_disk=True)
test_eq(X.shape, (181, 1, 58))
```

`Dataset: m1_yearly_dataset
downloading data...

---------------------------------------------------------------------------
timeout                                   Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    383                     # otherwise it looks like a programming error was the cause.
--> 384                     six.raise_from(e, None)
    385         except (SocketTimeout, BaseSSLError, SocketError) as e:

23 frames
timeout: The read operation timed out

During handling of the above exception, another exception occurred:

ReadTimeoutError                          Traceback (most recent call last)
ReadTimeoutError: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=4)

During handling of the above exception, another exception occurred:

ReadTimeout                               Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    527                 raise SSLError(e, request=request)
    528             elif isinstance(e, ReadTimeoutError):
--> 529                 raise ReadTimeout(e, request=request)
    530             else:
    531                 raise

ReadTimeout: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out. (read timeout=4)`

**Comment by oguiza** [comment]
Hi @mlgitter,
Thanks for reporting this issue.
I've noticed that the connection to Zenodo (the data provider for several forecasting datasets) is not always stable. Having said that, I've always been able to download the data after several attempts, and/ or increasing the timeout.
I'm not sure what else could be done to avoid this issue. Do you have any recommendations?

**Comment by oguiza** [comment]
I'm closing this issue due to a lack of a response. Please, re-open it if necessary.
