### ISSUE TITLE
AttributeError: 'TSTPlus' object has no attribute '__name__'

### ISSUE THREAD

**Issue by TKassis** [timeseriesAI/tsai#157]
I'm trying to setup a learner as follows:

```python
  # Define model
  model = TSTPlus(
      c_in=dls.vars, 
      c_out=dls.c,
      seq_len=dls.len,
      n_layers=config['n_layers'],
      d_model=config['d_model'],
      n_heads=config['n_heads'],
      d_k=config['d_k'],
      d_v=config['d_v'],
      d_ff=config['d_ff'],
      res_dropout=config['res_dropout'],
      fc_dropout=config['fc_dropout'], 
  )
  
  # Setup fastai/tsai learner
  learn = ts_learner(
      dls=dls, 
      arch=model,
      pretrained=True,
      weights_path='trained_models/selfsup_best.pth',
      metrics=[mae, mape, rmse], 
      loss_func=eval(config['loss_func']), 
      cbs=[SaveModelCallback(monitor='valid_loss', fname=f'{trial}_model'),
              EarlyStoppingCallback(monitor='valid_loss', patience=int(0.25*config['num_epochs'])),
              WeightedPerSampleLoss(weights),
              WandbCallback()],
      path = None,
      model_dir = 'trained_models',
  )
```
But I get the error: AttributeError: 'TSTPlus' object has no attribute '__name__'

I'm assuming 'arch' takes the name of the model, so in this case it would be 'TSTPlus', but if that's the case how do I define the model parameters? I have tried setting up a Learner using:

```python
learn = Learner(dls, model)
```
Which works correctly, but I cannot pass pretrained weights that way.

Any advice is appreciated.

Thanks!

**Comment by vrodriguezf** [comment]
I think the correct way is to use the class reference directly (i.e., `TSTPlus` without quotes) as `arch` argument, and pass the model parameters as `**kwargs`.

**Comment by oguiza** [comment]
Hi @TKassis,
Thanks, @vrodriguezf! You are right. You need to pass the selected architecture (no the name of the architecture, that is without quotes) to ts_learner. In your case, you were passing an already instantiated model. 
So just do this:
```
learn = Learner(dls, TSTPlus, **config)
```

I'm not sure what you store in the config. The only thing you need to bear in mind is that you should only pass to ts_learner model hyperparameters or any arguments required by the Learner. If you had anything like `epochs`, for example, you should remove it before passing it to the learner: 

```
config = dict(fc_dropout=.5, n_layers=6, epochs=100)
config2 = dict((k, v) for k, v in config.items() if k not in ['epochs'])
learn = Learner(dls, model, **config2)
learn.fit_one_cycle(config['epochs'])
```
I hope this is clearer now.

**Comment by TKassis** [comment]
Thanks that works! I can use the ts_learner function now.
