### ISSUE TITLE
Error in MVP: custom_mask is not defined

### ISSUE THREAD

**Issue by vrodriguezf** [timeseriesAI/tsai#160]
I think there's an error in this line:
https://github.com/timeseriesAI/tsai/blob/8ffa0afbcac6f886c3cb8310fa60d636becb1799/tsai/callback/MVP.py#L179

`custom_mask` should be replaced with `self.custom_mask`

Best!

**Comment by oguiza** [comment]
Yes, you are right. Sorry about that!
I've already fixed the issue.
