### ISSUE TITLE
What are plus models?

### ISSUE THREAD

**Issue by diegoquintanav** [timeseriesAI/tsai#174]
Many models have a `Plus` variant, like `RNN` and `RNNPlus`. What makes them different from non-plus models? I've looked into the documentation but I did not find anything. 

Thanks!

**Comment by dnth** [comment]
As far as I know the Plus models allow you to pass in a `custom_head` [argument](https://github.com/timeseriesAI/tsai/blob/main/tsai/models/RNNPlus.py). This means you can customize the layers at the model head to your liking. Additionally, with Plus models, you can run unsupervised pretraining like in the example [here](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/08_Self_Supervised_TSBERT.ipynb).

**Comment by TKassis** [comment]
Also, the Plus variants sometimes have features/parameters that you can play with that aren't available in the non-Plus implementation which try to follow the published model as faithfully as possible.

**Comment by oguiza** [comment]
@dnth, @TKassis, thanks for answering this question. You are absolutely correct.
I will close this issue now. Please, feel free to reopen if you feel that the question hasn't been properly answered.
