### ISSUE TITLE
Use fastai dataloader for tsimage_learner

### ISSUE THREAD

**Issue by moozgoos** [timeseriesAI/tsai#177]
Hello,
when using fastai I am using a standard dataloader, loading files from folders:
`images = DataBlock(
    blocks=(ImageBlock, CategoryBlock), 
    get_items=get_image_files, 
    splitter=GrandparentSplitter(train_name='train', valid_name='valid'),
    get_y=parent_label,
    item_tfms=Resize(128, ResizeMethod.Squish))`    
`dls = images.dataloaders(path, num_workers=0, bs=32)`

Those images are pandas dataframes converted to Gramian Angular Field.

Is there a way to use fastai dataloaders with tsimage_learner or use tsai dataloaders to load data from directories?

**Comment by oguiza** [comment]
Sorry, but I don't quite understand your setup. Do you have an image-like file for each sample in each folder?
If so I believe you should be able to use `tsai` (tsimage_loader) to train your model.
But it'd be good if you would provide some more information on your dataset.

**Comment by oguiza** [comment]
I will close this issue due to a lack of response. Please, reopen if necessary.
