### ISSUE TITLE
Bug in encode_positions?

### ISSUE THREAD

**Issue by vrodriguezf** [timeseriesAI/tsai#178]
There's a variable `a` in that line with should be the argument `pos_arr` if i am not wrong.

https://github.com/timeseriesAI/tsai/blob/816ccd794a398759c7614e68df406be4c62b06a9/tsai/utils.py#L882

Best!

**Comment by oguiza** [comment]
You are right @vrodriguezf . Good catch!
It's fixed now. I'll close this issue.
