### ISSUE TITLE
from tsai.all import *: 'str' object has no attribute '__stored_args__'

### ISSUE THREAD

**Issue by vladimirkovacevic** [timeseriesAI/tsai#18]
When run locally with latest tsai version or when transferred to google colab the obtained error is:
`'str' object has no attribute '__stored_args__'`
It can be reproduced by running 01_Intro_to_Time_Series_Classification.ipynb on google colab.

**Comment by qnkhuat** [comment]
I have the same issue. If I install fastcore==1.0.0 it does resolve the problem but I can't import fastai anymore

**Comment by jeremyjong** [comment]
Facing the same problem.

**Comment by jeremyjong** [comment]
Anyone facing the issue, just downgrade your fastcore to 1.0.0 using pip
pip install fastcore==1.0.0

**Comment by qnkhuat** [comment]
> Anyone facing the issue, just downgrade your fastcore to 1.0.0 using pip
> pip install fastcore==1.0.0

Doing this does resolve the problem but the problem will occur again if you want to import fastai the latest version.
My solution is I clone this repo and replace all import "fastai2" to "fastai".

**Comment by oguiza** [comment]
I've made a major update to the `tsai` library and it should work well now with fastai v2. Please, let me know if you still have any issues.
