### ISSUE TITLE
Grad-CAM on InceptionTime

### ISSUE THREAD

**Issue by francescocarel** [timeseriesAI/tsai#180]
Hallo,
I would like to make a grad-CAM map out of the Inception time module, however I cannot access the layers. e.g. `learn.model[layer]` gives the error `TypeError: 'InceptionTime' object is not subscriptable`. 
How can I solve the problem?

**Comment by vrodriguezf** [comment]
you can access the ith inception module with `learn.model.inceptionblock.inception[i]`

**Comment by oguiza** [comment]
@francescocarel, for this particular example you can follow @vrodriguezf 's advice.
In general, what I normally do when I don't remember how to access a particular layer is:
1.  print the model I want to access
2. find the next module names I want to access
3. print it again until I reach the desired level.

**Comment by oguiza** [comment]
I will close this issue due to a lack of response. Please, reopen if necessary.
