### ISSUE TITLE
Should a `freq` option be included in `add_missing_timestamps` function when `range_by_group` is `True`?

### ISSUE THREAD

**Issue by rkainkaryam** [timeseriesAI/tsai#181]
Hi,

Thanks for the great work on this project!

For [this line](https://github.com/timeseriesAI/tsai/blob/main/tsai/data/preparation.py#L149), should there be a `freq` option in `pd.date_range` call in the `add_missing_timestamps` function when `range_by_group` is `True`? This would allow non-day-level timestamps to be filled in.

Current line:
```
idx_tuples = flatten_list([[(d, key) for d in pd.date_range(min_date, max_date)] for min_date, max_date, key in zip(min_dates, max_dates, keys)])
 ```

Suggested change:
```
idx_tuples = flatten_list([[(d, key) for d in pd.date_range(min_date, max_date, freq=freq)] for min_date, max_date, key in zip(min_dates, max_dates, keys)])
 ```

Happy to send a PR is this works!

**Comment by oguiza** [comment]
Hi @rkainkaryam, good to see you around!

Good catch! Your request makes a lot of sense. 

I've created a minimalist [example](https://colab.research.google.com/gist/oguiza/0ee4d2e0fc75b3bdedd5b104db187315/add_missing_timestamps.ipynb) to confirm we are aligned in terms of the expected outputs. Please, take a quick look at it and let me know if it's ok. 

There are 2 options to make the required changes: 
1. You install an editable version of `tsai`*, make the changes in the notebook (including the testing I've added) and submit the PR, or
2. I make the change

*I can prepare some instructions on how to make changes in `tsai` using `nbdev`.
 
Please, let me know your preference.

**Comment by rkainkaryam** [comment]
Thanks @oguiza -- I would be happy to start contributing (using these [instructions](https://github.com/timeseriesAI/tsai/blob/main/CONTRIBUTING.md)?) to `tsai`, if you have the patience 😁

**Comment by oguiza** [comment]
> I would be happy to start contributing

That's great to hear @rkainkaryam !!

I'm working on some updated/ detailed instructions especially for those that are not familiar with nbdev. But if you are, please, feel free to submit a PR when ready. 
I believe the instructions will be updated by the end the day tomorrow.

> The example you shared looks good to me. I tested adding freq to the two places you mentioned and it works with both situations (only watch-out is to probably add a check for duplicate timestamps before reindexing)

Well if this happens, you'd get an error message describing why this happens. It's something we can add as part of the documentation (you can add a Note in the notebook in Markdown clarifying this. That will be exported to the documentation.

**Comment by oguiza** [comment]
Hi @rkainkaryam ,

Something important that is missing is to run all tests to confirm your fix doesn't break anything. To do that you run: 

```nbdev_test_nbs```

I run it between nbdev_build_lib and nbdev_build_docs, although there's no problem if nbdev_build_docs is run before. You must run nbdev_build_lib before so that the scripts are updated. 


Here are the interim guidelines. I still need to finalize them, but they might be useful to you.


# How to contribute to `tsai`:

If you plan to contribute to tsai here are the steps you should follow. These steps make use of `gh`which is GitHub's official command line tool. They also show you how to create a separate conda environment with all required packages.

1. Install/ upgrade gh using these instructions [here](https://cli.github.com/manual/installation).

2. Use an editable install. To do that navigate to the folder where you want to install the tsai repo and do the following:

   ```git clone https://github.com/timeseriesAI/tsai```
   
   ```cd tsai```
   
   ```conda create -n py38 python=3.8``` (I'm calling the environment py38 but you can change the name)
   
   ```conda activate py38```
   
   ```pip install -e ".[dev]"```
   
3. Run 

   ```nbdev_install_git_hooks``` 

inside the repo folder. This sets up git hooks, which clean up the notebooks to remove the extraneous stuff stored in the notebooks (e.g. which cells you ran) which causes unnecessary merge conflicts.

4. Checkout to new feature branch (this is where new feature/bug-fix should be made):

   ```git checkout -b <enter--relevant-feature-branch-name>``` 
   
   (for example ```git checkout -b tsai_feature1```)
    
5. Navigate to the folder you wish to modify in the tsai/nbs folder and open the required Jupyter Notebook you wish to modify. Make changes to Jupyter Notebook (ie., add tests, update feature, add new feature, add documentation etc.). When finished, before closing the notebook, restart the kernel and run the entire notebook to ensure everything runs smoothly until the end of the notebook. Now you can close it.
    
6. Run library tests using

    ```nbdev_test_nbs```
 
    in your terminal (you should still be within the conda environment you previously created). This step will take a few minutes. 
    
    Sometimes, a change may create an issue when running tests in the same notebook or in other notebook/s. In that case, you'll get a message like this: 
    
    Exception: The following notebooks failed:
    003_data.preprocessing.ipynb
    
    You should then open that notebook and run it to learn where is the issue. You should fix it, rerun the notebook you have fixed and run:
    
    ```nbdev_test_nbs```
    
    until this message: All tests are passing!    
    
7. Update the documentation by running: 
    
    ```nbdev_build_docs```
 
8. Commit changes with a brief message describing your changes:
    
   ```
    git add .
    git commit -m "modified index nb"
    ```
    
9. Create a pull request using GitHub CLI. 
    
    Note: first time you run `gh` you'll get this message: 
    
    Welcome to GitHub CLI!

    To authenticate, please run `gh auth login`.
    
    Follow the instructions to be authenticated. 

    When you are authenticated (first time only) you can proceed to create the pull request:
    
    
    ```gh pr create -B master -b "enter body of PR here" -t "enter title"```
    
    This command will automatically create a fork for you if you’re in a repository that you don’t have permission to push to.
    
    
Note: Steps 1-3 need to be only performed once when you fork tsai for the first time. In subsequent PRs start from the step 4.

**Comment by rkainkaryam** [comment]
Thanks, @oguiza! I followed the instructions and was able to edit, test, build, and commit the changes. One small hiccup was a missing dependency in a separate notebook: `fastdownload` in `001_data.external.ipynb` that I resolved by manually installing `fastdownload`.

The bigger issue is this github error on creating the PR:
```
Branch 'freq_add_missing_timestamp' set up to track remote branch 'freq_add_missing_timestamp' from 'fork'.
pull request create failed: GraphQL error: Head sha can't be blank, Base sha can't be blank, No commits between timeserie
sAI:master and rkainkaryam:freq_add_missing_timestamp, Base ref must be a branch
```

However, I do see the fork and the [PR here](https://github.com/rkainkaryam/tsai/tree/freq_add_missing_timestamp)

But it is not listed on the PRs on the [main repo](https://github.com/timeseriesAI/tsai/pulls), though 😬

**Comment by oguiza** [comment]
Sorry I made a mistake.

Please, replace 

gh pr create -B master -b "enter body of PR here" -t "enter title"

by 

gh pr create -B main -b "enter body of PR here" -t "enter title"

**Comment by dnth** [comment]
> Hi @rkainkaryam ,
> 
> Something important that is missing is to run all tests to confirm your fix doesn't break anything. To do that you run:
> 
> `nbdev_test_nbs`
> 
> I run it between nbdev_build_lib and nbdev_build_docs, although there's no problem if nbdev_build_docs is run before. You must run nbdev_build_lib before so that the scripts are updated.
> 
> Here are the interim guidelines. I still need to finalize them, but they might be useful to you.
> 
> # How to contribute to `tsai`:
> If you plan to contribute to tsai here are the steps you should follow. These steps make use of `gh`which is GitHub's official command line tool. They also show you how to create a separate conda environment with all required packages.
> 
> 1. Install/ upgrade gh using these instructions [here](https://cli.github.com/manual/installation).
> 2. Use an editable install. To do that navigate to the folder where you want to install the tsai repo and do the following:
>    `git clone https://github.com/timeseriesAI/tsai`
>    `cd tsai`
>    `conda create -n py38 python=3.8` (I'm calling the environment py38 but you can change the name)
>    `conda activate py38`
>    `pip install -e ".[dev]"`
> 3. Run
>    `nbdev_install_git_hooks`
> 
> inside the repo folder. This sets up git hooks, which clean up the notebooks to remove the extraneous stuff stored in the notebooks (e.g. which cells you ran) which causes unnecessary merge conflicts.
> 
> 1. Checkout to new feature branch (this is where new feature/bug-fix should be made):
>    `git checkout -b <enter--relevant-feature-branch-name>`
>    (for example `git checkout -b tsai_feature1`)
> 2. Navigate to the folder you wish to modify in the tsai/nbs folder and open the required Jupyter Notebook you wish to modify. Make changes to Jupyter Notebook (ie., add tests, update feature, add new feature, add documentation etc.). When finished, before closing the notebook, restart the kernel and run the entire notebook to ensure everything runs smoothly until the end of the notebook. Now you can close it.
> 3. Run library tests using
>    `nbdev_test_nbs`
>    in your terminal (you should still be within the conda environment you previously created). This step will take a few minutes.
>    Sometimes, a change may create an issue when running tests in the same notebook or in other notebook/s. In that case, you'll get a message like this:
>    Exception: The following notebooks failed:
>    003_data.preprocessing.ipynb
>    You should then open that notebook and run it to learn where is the issue. You should fix it, rerun the notebook you have fixed and run:
>    `nbdev_test_nbs`
>    until this message: All tests are passing!
> 4. Update the documentation by running:
>    `nbdev_build_docs`
> 5. Commit changes with a brief message describing your changes:
>    ```
>     git add .
>     git commit -m "modified index nb"
>    ```
> 6. Create a pull request using GitHub CLI.
>    Note: first time you run `gh` you'll get this message:
>    Welcome to GitHub CLI!
>    To authenticate, please run `gh auth login`.
>    Follow the instructions to be authenticated.
>    When you are authenticated (first time only) you can proceed to create the pull request:
>    `gh pr create -B main -b "enter body of PR here" -t "enter title"`
>    This command will automatically create a fork for you if you’re in a repository that you don’t have permission to push to.
> 
> Note: Steps 1-3 need to be only performed once when you fork tsai for the first time. In subsequent PRs start from the step 4.

Thanks for this! Very easy to follow!

**Comment by rkainkaryam** [comment]
Done! Sorry, should have read more closey before copy-pasting code 🙈

**Comment by rkainkaryam** [comment]
Done! Thanks for the detailed instructions! 🙏

**Comment by rkainkaryam** [comment]
@oguiza Thanks for the detailed instructions on using `nbdev` and submitting a PR to `tsai`. Looking forward to contributing more!
