### ISSUE TITLE
large datasets and unwindow dataset

### ISSUE THREAD

**Issue by mvccn** [timeseriesAI/tsai#182]
This could be related to the last one(#126). I have tested both the old code and new code. In TSAI, in order to create a dataloader before training, we typically do this: 

Xw = df[dp.allfeatures].to_numpy()
yw = df['label'].to_numpy() 
#save to disk and load so X, y are in  zarr or npmemmap format
zarr.save(X_path,Xm)
zarr.save(y_path, ym)
del Xm, ym
X = zarr.open(X_path, mode='r')
y = zarr.open(y_path, mode='r')
splits = TSSplitter()(y)

dsets = TSDatasets(X, y, tfms=[None, [Categorize()]], splits=splits, inplace=True)

dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid,
								device=device,
								bs=config['dataloader']['batch_size'],
								batch_tfms=TSStandardize(),
								)

The process above became very slow for X is only 4G and run into out of memory issue. I have 3 questions regarding this process: 
1. Splitting:  the calls to dsets.train and dsets.valid took very long time, it appears bring data on disk to memory. in the new release, shouldn't the splits only passing indexes and not bring the data on the disk to memory during splitting?  I see dsets.train is calling TSDatasets's subset() which will pass the dsets's one of tl to create a new TSDatasets. does the process load all data to memory during the process?
   
2. data to memory in TSDataset constructor : for X, y in zarr, npmemmap etc format, ideally data should only be brought to memory when dataloader load batch as discussed in #126, but in constructor:
   self.ptls =L([tl if not self.inplace else tl[:] if type(tl[0]).__name__ == 'memmap' else tensor(stack(tl[:])) for tl in self.tls])
 does this bring data to memory? 
3. unwindowed data:  this could be another request, but this is related. we use slidingwindow to create data(sequence), which makes data much larger. data with window 200 are 200 times bigger. There is an unwindowed class, but I don't see it can achieved similar functions as slidingwindow. ideally the windowed data should be handled in TSDatasets. 
Struggled with these issues in past one week, really appreciate for any help.

**Comment by mvccn** [comment]
my bad, I saw the notes in example note book, inplace need to be disabled and use TSClassification transform.  It created the dls very quickly.

**Comment by oguiza** [comment]
Hi @mvccn,
I’m a bit confused by your last comment. Do you still have any open issues/ questions, or should we close this issue?

**Comment by mvccn** [comment]
+
.-
.
0.

**Comment by mvccn** [comment]
The dataloader part is fine, however, the training with zarr is really slow, it tooks 2 hours for each epoch(my zarr size is about 12g), the same training when data is all in memory used to take less than 10 mins.  I tried set chunks and add num of workers, still have no luck.

**Comment by oguiza** [comment]
That's weird. Could you please @mvccn  create a gist with some dummy data showing what you are doing?

**Comment by oguiza** [comment]
Hi @mvccn , 
I've just released a new [tutorial notebook](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/11_How_to_train_big_arrays_fast_in_tsai.ipynb) that demonstrates the use zarr arrays in tsai. There are some interesting insights as to how to make training really fast. It's important that arrays are correctly prepared. 
I don't know if it can help you.

**Comment by oguiza** [comment]
I will close this issue due to a lack of response. Please, reopen if necessary.

**Comment by mvccn** [comment]
Sorry, I was tied up last few days. I spent a lot of time to get zarr working, it became reasonable but still slower than memmap, I will try your tutorial later.&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Ignacio ***@***.***&gt;;
Date: &nbsp;Sat, Sep 11, 2021 01:13 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [timeseriesAI/tsai] large datasets and unwindow dataset (#182)

&nbsp;



 
I will close this issue due to a lack of response. Please, reopen if necessary.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
