### ISSUE TITLE
Getting Embedded Space Values in InceptionTime

### ISSUE THREAD

**Issue by eyalbetzalel** [timeseriesAI/tsai#186]
Hi,

After training my model, I wish to access the embedded space like they did in this example : 

https://www.kaggle.com/guntherthepenguin/fastai-deep-learning-with-embeddings

It seems that InceptionTime doesn't have this option. Is there a convenient way to infer this data? 

Thanks in advance, 
Eyal

**Comment by oguiza** [comment]
Hi @eyalbetzalel,

Well I'm afaid there isn't as InceptionTime doesn't use embeddings unlike tabular models. There are other models in `tsai`that use embeddings, like TST or TSiT for example.

**Comment by oguiza** [comment]
I will close this issue due to a lack of response. Please, reopen if necessary.
