### ISSUE TITLE
colab tutorial notebook doesn't work

### ISSUE THREAD

**Issue by Sandyxuxinxi** [timeseriesAI/tsai#20]
![image](https://user-images.githubusercontent.com/24632905/98456273-e2af0580-21cf-11eb-8dc9-c63b088b0dbd.png)

https://colab.research.google.com/github/timeseriesAI/timeseriesAI/blob/master/tutorial_nbs/04_Intro_to_Time_Series_Regression.ipynb#scrollTo=FCo_EfE8uv5m

**Comment by oguiza** [comment]
I've made a major update to `tsai`. The library has been migrated [here](https://github.com/timeseriesAI/tsai).

Please, use the following link: 
https://colab.research.google.com/github/timeseriesAI/tsai/blob/master/tutorial_nbs/04_Intro_to_Time_Series_Regression.ipynb

Let me know if you have any issues.
