### ISSUE TITLE
fit a model multiple times with different data

### ISSUE THREAD

**Issue by frederikvanhevel** [timeseriesAI/tsai#216]
I have a couple of different datasets with similar data. Is it possible to use Learner to fit multiple times with these different datasets? Sorry if this is a newbie question. I cant seem to find this information anywhere. Thanks!

**Comment by vrodriguezf** [comment]
I guess you can create multiple dataloaders and change them by replacing `learn.dls`

**Comment by frederikvanhevel** [comment]
thanks!
