### ISSUE TITLE
Can't use GPU runtime on Google Colab

### ISSUE THREAD

**Issue by DavidykZhao** [timeseriesAI/tsai#23]
Hi,

Thanks for making this wonderful package. 
There is one small problem I encountered. I was trying to run 06_TS_to_image_classification.ipynb. 
It would run well on a CPU setting but when I switch to a GPU runtime, it would give `TypeError: expected CPU (got CUDA)`
I tried manually .to(device) or .cuda() but none prevailed. 
Would love to hear about your suggestions.

**Comment by oguiza** [comment]
Hi @DavidykZhao,
Thanks for your compliments, for using this package, and for reporting this issue!
I've looked into it and there was indeed a bug in the code. I've fixed it and rerun the notebook and it works well. 
Please, let me know if you get this or any other issue.
Thanks again

**Comment by DavidykZhao** [comment]
Hi @oguiza ,

Thanks for getting on this issue and solving it this fast. I just re-run that and it works perfectly. Thanks for making this package such a smooth process to work with!

I do have another question. So what I am trying to do is to turn TS into images and then do regression. I followed the regression notebook and put `[None, ToNumpyTensor()]` in `tfms`, and put `[TSToPlot]` in `batch_tfms`. However, my `y`, which should be a float tensor, is also converted to a `TSImage` object. I attach a screenshot here.

![Screen Shot 2020-11-16 at 9 38 44 AM](https://user-images.githubusercontent.com/37813116/99296083-d5b39700-280b-11eb-884b-6e6f38dc3c2b.png)

I have also tried to put `[[TSToPlot], None]` in `batch_tfms` but my `y` is still transformed to a `TSImage` object.

The current hack I tried and worked is by putting `[None, None]` in `tfms` like following: 
![Screen Shot 2020-11-16 at 1 04 41 PM](https://user-images.githubusercontent.com/37813116/99296462-6ee2ad80-280c-11eb-951d-9cd29a674511.png)


I am not sure if I have misunderstandings regarding `batch_tfms` or if there are more details I need to pay attention to. 
Could you please advice on what might be the best practice to do regression on TS turned images?


Thanks again.

**Comment by oguiza** [comment]
This new issue is a great catch! It was a bug I had missed as I hadn't tested the TS to image transforms for regression. 
I've now updated the code and tested in Colab and it works as I expect. But please, confirm that it also meets your expectations. 
You should run this code: 
```
tfms  = [None, ToNumpyTensor()]
batch_tfms = [TSNormalize(), TSToGADF()]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits)
dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=[64, 128], batch_tfms=batch_tfms)
xb, yb = first(dls.train)
xb, yb
```
or an even simpler one: 
```
tfms  = [None, ToNumpyTensor()]
batch_tfms = [TSNormalize(), TSToGADF()]
dls   = get_ts_dls(X, y, tfms=tfms, splits=splits, bs=[64, 128], batch_tfms=batch_tfms)
xb, yb = first(dls.train)
xb, yb
```
In either case, you should get this output: 
```
(TSImage(shape:(64, 24, 224, 224)), NumpyTensor(shape:(64,)))
```
So the ys are not converted to TSImages as before. You can also use `dls.show_batch()` which correctly. 

This is all the code you need to train a model using images: 
```
dsid = 'NATOPS' 
X, y, splits = get_UCR_data(dsid, return_split=False)
y = y.astype(np.float) # to simulate you have a continuous target

tfms  = [None, ToNumpyTensor()]
batch_tfms = [TSNormalize(), TSToPlot()]
dls = get_ts_dls(X, y, tfms=tfms, splits=splits, bs=[64, 128], batch_tfms=batch_tfms)

model = create_model(xresnet34, dls=dls)
learn = Learner(dls, model, metrics=accuracy)
learn.fit_one_cycle(50, lr_max=1e-3)
```
Thanks again for raising this, and let me know if you find any further issues.

**Comment by DavidykZhao** [comment]
Hi @oguiza ,

Thanks for fixing this issue and now it works very well.
By looking at how did you fix the issue I also gained a better understanding of the package. 
I will continue exploring this wonderful package and let you know if I can find any issues.
Thanks again for building this amazing package. It brought me as much excitement as when I discovered fastai years ago.
