### ISSUE TITLE
[Questions] how to use get_X_preds when Y=none?

### ISSUE THREAD

**Issue by bettermorn** [timeseriesAI/tsai#233]
Hello there,

I would like to use learn.get_X_preds(X[splits[1]])   by referring  the following sample: https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/04_Intro_to_Time_Series_Regression.ipynb

For  get_X_preds,how to set parameters  such as  with_input, with_decoded, with_loss to avoid the following errors:

The size of tensor a (18) must match the size of tensor b (19) at non-singleton dimension 1

Thanks for your great support!

**Comment by Wabinab** [comment]
Have you try create a new dimension with `None` to replace where `y` is originally? Otherwise you could do

```
test_ds = valid_dl.dataset.add_test(X)
test_dl = valid_dl.new(test_ds)
preds, targs = learn.get_preds(dl=test_dl)
```
and replace `valid_dl` with your dl (it could be `dls` as well).

**Comment by oguiza** [comment]
Hi @bettermorn ,
You should be able to use get_X_preds without using y (or setting y=None). 
Is there an issue in the 04_Intro_to_Time_Series_Regression.ipynb? Or is are you referring to an issue with your own data?

**Comment by bettermorn** [comment]
Thanks for your explanation.From the logic of my model,I have to use predict value as my Independent variable.I will close this issue.
