### ISSUE TITLE
Question on MiniRocket tutorial notebook.

### ISSUE THREAD

**Issue by elichienxD** [timeseriesAI/tsai#237]
Hi,

Thanks for this great project! I encounter a problem when I try to reproduce the result from the MiniRocket tutorial notebook. In the Offline Pytorch implementation section, I find that the predicted label does not match the one in y. For example:
![image](https://user-images.githubusercontent.com/46387845/137221532-7078b8d1-719a-42dd-bb28-333576b6e45a.png)

Here the preds are actually ranging from 0 to 13 (14 unique labels) but y has non-consecutive labels:
![image](https://user-images.githubusercontent.com/46387845/137221660-8c4d9ddf-29b8-45b3-9e4d-efb052e6b991.png)

I find that in its current form the skm.accuracy_score will be zero:
![image](https://user-images.githubusercontent.com/46387845/137221731-6ee73afc-e741-452c-9314-223df78a4719.png)

However, in the above cells, 
![image](https://user-images.githubusercontent.com/46387845/137221863-0e4c04ad-a5d9-4372-a3eb-6a12747fab0a.png)
I can reproduce the accuracy as the tutorial notebook displayed. Thus I think the model is trained correctly, just the label hashing is off. I want to double-check if this is indeed a bug or I've messed up something.

My environment is as follows (I create a clean virtual environment)
![image](https://user-images.githubusercontent.com/46387845/137222197-5bda0729-1a61-43d3-8fe1-4d9c457569fb.png)

Thanks in advance for the help!
Eli

**Comment by oguiza** [comment]
I've checked this and there's truly a bug somewhere. I'll work on this in the next few days.

**Comment by oguiza** [comment]
I've rerun the MiniRocket tutorial nb and have confirmed the accuracy is calculated as expected. 
Predictions will be decoded when using with_decoded argument in get_X_preds.
Based on this I'll close this issue.
