### ISSUE TITLE
Mixed precision training

### ISSUE THREAD

**Issue by dnth** [timeseriesAI/tsai#24]
At the moment do we have support for mixed precision training? I seem to get NaN loss with with learn.to_fp16 training. Running on RTX3090. Not sure if theres issue with the cuda 11 support for the new 30 series card.

**Comment by oguiza** [comment]
Hi @dnth, 

I don't know much about mixed-precision training. I've tried it a few times with native fastai but didn't see any improvements, so it may be hardware dependent.
I haven't built anything specifically for mixed-precision training. So unless I've inadvertently broken something it works as fastai. 
Actually I've tested it in Colab (Tesla V100-SXM2-16GB) and it works, although timings are worse for some reason. 
This is the code I used:
```
dsid = 'NATOPS' 
X, y, splits = get_UCR_data(dsid, return_split=False)
tfms  = [None, [Categorize()]]
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, bs=[64,128])
model = InceptionTime(dls.vars, dls.c)

# non mixed-precision training
learn = Learner(dls, model, metrics=accuracy)
start = time.time()
learn.fit_one_cycle(100, lr_max=1e-3)
print('\nelapsed time:', time.time() - start)

# mixed-precision training
learn = Learner(dls, model, metrics=accuracy).to_fp16()
start = time.time()
learn.fit_one_cycle(100, lr_max=1e-3)
print('\nelapsed time:', time.time() - start)
```
But other than that, I'm not sure I'll be able to help. Sorry.

**Comment by dnth** [comment]
I havent have much luck for mixed precision training too. If I dont get Nan losses, the time it takes per epoch is longer than the default training. Thank you so much for your works in this repo. TSAI really opens up a lot of possibilities in my research area!
