### ISSUE TITLE
TypeError: df2Xy() got an unexpected keyword argument 'steps_in_rows'

### ISSUE THREAD

**Issue by rozanecm** [timeseriesAI/tsai#245]
Hi! I tried installing tsai both from pip and from git, getting versions 0.2.22 and 0.2.23 respectively.
In both cases, I get the error mentioned in the title. No further info is given.

I see the `steps_in_rows` arg. in the repo code, so I'm not sure why I'm getting this error.

I'm running this in Google Colab.

**Comment by jefferyanderson** [comment]
@rozanecm I'm getting the samething, can you please let me know what you did to resolve/ work around this issue?

**Comment by oguiza** [comment]
You can avoid this issue by installing tsai from GitHub: 
```bash
pip install git+https://github.com/timeseriesAI/tsai.git >> /dev/null
```

I will create a new pip release later this week, and you'll be able to use a regular pip install.

**Comment by rozanecm** [comment]
@jefferyanderson I didn't really change much; I came back to it later and just worked.
Note that
- I installed the GitHub version as @oguiza suggested though,
- and that you need to restart the runtime after installation for things to work properly.
If you take care of those 2 things, it should work ok!

Hope it helps!
