### ISSUE TITLE
Normalize output in regression/forecasting

### ISSUE THREAD

**Issue by vrodriguezf** [timeseriesAI/tsai#246]
Hi,

Is there anything like a batch_tfm for the target `y` when it is a number, like in a regression, or a tensor, like in a multi-horizon (or multi-step) forecasting problem? I don't even know if that's something that fastai contemplates

Thanks!

**Comment by oguiza** [comment]
It's not possible out of the box. And I'm not sure there's any benefit in doing that. Maybe for very large outputs. I don't know. 
In any case, if you want to create a reversible transform, you'd need to create a new tensor subtype (for example, LabelTensor) and a new transform specific for that tensor subtype, with a encode and decode method (similar to TSStandardize).

**Comment by oguiza** [comment]
I'll move this to Discussions as it's more a question than an issue.
