### ISSUE TITLE
TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by yangtzech** [timeseriesAI/tsai#250]
I just installed tsai and was running the tutorial notebook _00c_Time_Series_data_preparation.ipynb_. 

Where the error occurs is shown in the image below in  **Multivariate** of **Pandas dataframe with samplesas rows**      

![image](https://user-images.githubusercontent.com/41911522/140883835-c2d291e8-f01e-4831-a335-44c46cb90f50.png)
[error.txt](https://github.com/timeseriesAI/tsai/files/7503050/error.txt)

**Comment by oguiza** [comment]
Thanks for raising this issue. I believe it is fixed now. Please, let me know if the issue persists.

**Comment by yangtzech** [comment]
Thanks for your work. The problem doesn't exsist anymore.

**Comment by oguiza** [comment]
Wow! Thanks for checking it so quickly! 😀
Based on your comment, I'll close this issue.
