### ISSUE TITLE
AttributeError: 'TST' object has no attribute '__name__'

### ISSUE THREAD

**Issue by strakehyr** [timeseriesAI/tsai#253]
So I am trying to use several models on a regression issue with some specific model variable changes (like shown in https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/07_Time_Series_Classification_with_Transformers.ipynb), and whenever I pass the learner line it gives me the error: 
`AttributeError: 'TST' object has no attribute '__name__'`

Full code:

```
X, y = SlidingWindow(look_back, get_x = list(df.iloc[:,1:].columns), get_y = (df.iloc[:,0].name), horizon=horizon)(df)
splits = get_splits(y, n_splits=1, valid_size=.2, shuffle=True)
check_data(X, y, splits)
tfms  = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_sample=True, by_var=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=24)
dls.one_batch()
dls.show_batch()
model = TST(c_in = dls.vars, c_out = dls.c, seq_len = dls.len, res_dropout = .3, fc_dropout = .8)
learn = ts_learner(dls, model, opt_func = SGD, loss_func = mse, metrics=[mae, mse], cbs=ShowGraph())
```

**Comment by vrodriguezf** [comment]
Does it happen too if you use `TSTPlus` instead of `TST`?

**Comment by oguiza** [comment]
Hi @strakehyr,
There are a couple of issues with your code: 
1. res_dropout is not an argument of TST. You should replace it by dropout.
2. There are 2 ways to pass a model to a learner: 

> Option 1: build the model and pass it to a Learner:
> ```bash
> X, y, splits = get_regression_data('Covid3Month', split_data=False)
> tfms = [None, [TSRegression()]]
> batch_tfms = TSStandardize(by_sample=True, by_var=True)
> dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=24)
> model = TST(c_in=dls.vars, c_out=dls.c, seq_len=dls.len, dropout=.3, fc_dropout=.8)
> learn = Learner(dls, model, opt_func=SGD, loss_func=mse, metrics=[mae, mse], cbs=ShowGraph())
> learn.fit_one_cycle(1)
> ```

> Option 2: pass an architecture (and any kwargs if necessary) to a ts_learner. The architecture is not initialized as you can see in the example below. In this option, the model is initialized inside the ts_learner, which picks the arguments from the dataloaders.
> ```bash
> X, y, splits = get_regression_data('Covid3Month', split_data=False)
> tfms = [None, [TSRegression()]]
> batch_tfms = TSStandardize(by_sample=True, by_var=True)
> dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=24)
> learn = ts_learner(dls, TST, dropout=.3, fc_dropout=.8, opt_func=SGD, loss_func=mse,
>                 metrics=[mae, mse], cbs=ShowGraph())
> learn.fit_one_cycle(1)
> ```

Both options deliver the same result. 
In your case, you are combining both options. This is not possible.

**Comment by strakehyr** [comment]
> Does it happen too if you use `TSTPlus` instead of `TST`?

Happens for both. 


> Hi @strakehyr, There are a couple of issues with your code:
> 
> 1. res_dropout is not an argument of TST. You should replace it by dropout.
> 2. There are 2 ways to pass a model to a learner:
> 
> > Option 1: build the model and pass it to a Learner:
> > ```shell
> > X, y, splits = get_regression_data('Covid3Month', split_data=False)
> > tfms = [None, [TSRegression()]]
> > batch_tfms = TSStandardize(by_sample=True, by_var=True)
> > dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=24)
> > model = TST(c_in=dls.vars, c_out=dls.c, seq_len=dls.len, dropout=.3, fc_dropout=.8)
> > learn = Learner(dls, model, opt_func=SGD, loss_func=mse, metrics=[mae, mse], cbs=ShowGraph())
> > learn.fit_one_cycle(1)
> > ```
> 
> > Option 2: pass an architecture (and any kwargs if necessary) to a ts_learner. The architecture is not initialized as you can see in the example below. In this option, the model is initialized inside the ts_learner, which picks the arguments from the dataloaders.
> > ```shell
> > X, y, splits = get_regression_data('Covid3Month', split_data=False)
> > tfms = [None, [TSRegression()]]
> > batch_tfms = TSStandardize(by_sample=True, by_var=True)
> > dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=24)
> > learn = ts_learner(dls, TST, dropout=.3, fc_dropout=.8, opt_func=SGD, loss_func=mse,
> >                 metrics=[mae, mse], cbs=ShowGraph())
> > learn.fit_one_cycle(1)
> > ```
> 
> Both options deliver the same result. In your case, you are combining both options. This is not possible.
So for option 1 : 
    Thanks for the tip. I have used the same syntax as in https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/07_Time_Series_Classification_with_Transformers.ipynb
    (even though I am doing Regression, not classification) so I assumed it was right. 
    
    -If I specify :
    `model = TST(c_in = dls.vars, c_out = dls.c, seq_len = dls.len, dropout = .2, fc_dropout = .8)`
    then I get the error: 
    `TypeError: __init__() got an unexpected keyword argument 'dropout'`
    despite the fact that in the documentation it sais dropout as you pointed out. The same happens with TSTPlus. 
    
    Anyway, even if I remove the dropout part, when setting up the learn, I still get the error:
    `learn = ts_learner(dls, model, opt_func = SGD, loss_func = mse, metrics=[mae, mse], cbs=ShowGraph())`
    
    `AttributeError: 'TSTPlus' object has no attribute '__name__'`
    
    My tsai version is: 0.2.22

Option 2 seems to work. Thanks for the tip.

**Comment by oguiza** [comment]
You are right. There was an error in https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/07_Time_Series_Classification_with_Transformers.ipynb 
Thanks for raising it! I've now fixed it (replaced res_dropout by dropout).
If you still get an error with option 1 please, try updating to the latest GitHub release if you can: 
```bash
!pip install git+https://github.com/timeseriesAI/tsai.git -U >> /dev/null
```
In any case, I'm planning to create a new release later this week.
