### ISSUE TITLE
''Time_Series_Classification_with_Transformers'' Enhancement

### ISSUE THREAD

**Issue by yangtzech** [timeseriesAI/tsai#256]
I run the 7_Time_Series_Classification_with_Transformers.ipynb and it did work. But I want to use it for regression and it failed.

And you said in the notebook that it is not the official implementation. I found that the author has released it in Github [here : mvts_transformer](https://github.com/gzerveas/mvts_transformer). 

Is it possible that you can add regression function to enhance the Transformer?

Thank you in advance for your kind help and I am looking forward to your answersing.

**Comment by oguiza** [comment]
You can do it just replacing Categorize() by TSRegression() and passing a y array of type float.

**Comment by yangtzech** [comment]
I did change, but i just found that there are some other parameters to change. It now works☺. Btw, as the code has been released, you may get to know what the author adopted in the paper.

Thanks for your help again.

**Comment by oguiza** [comment]
What other parameters need to be changed?

> Btw, as the code has been released, you may get to know what the author adopted in the paper.

I benchmarked TST code to the original mvts_transformer. It's now essentially the same.

**Comment by yangtzech** [comment]
From

> loss_func=LabelSmoothingCrossEntropyFlat(), metrics=[RocAucBinary(), accuracy], 

to

> loss_func=MSELossFlat(), metrics=[mae, rmse]

Btw, there is a underscore infront of rmse. Is that on purpose?
![ddbf775ad66433ce23992c9c9eae4ec](https://user-images.githubusercontent.com/41911522/141785243-bb62e2d6-ce4c-4192-a596-eb0cca620438.png)

**Comment by oguiza** [comment]
> From
> 
> > loss_func=LabelSmoothingCrossEntropyFlat(), metrics=[RocAucBinary(), accuracy],
> 
> to
> 
> > loss_func=MSELossFlat(), metrics=[mae, rmse]


Ok, I understand. I'll edit my previous response to address this.

> Btw, there is a underscore infront of rmse. Is that on purpose? ![ddbf775ad66433ce23992c9c9eae4ec](https://user-images.githubusercontent.com/41911522/141785243-bb62e2d6-ce4c-4192-a596-eb0cca620438.png)
That's coming from fastai. I'm not exactly sure why. Probably to differentiate it from some other rmse. 

Should I close this issue now?

**Comment by yangtzech** [comment]
Yes, no more questions. Thanks.
