### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'window_size'

### ISSUE THREAD

**Issue by yangtzech** [timeseriesAI/tsai#259]
I ran the code shown below and get a typeerror like this.
I tried updating from git but it could not get settled. 

![image](https://user-images.githubusercontent.com/41911522/141952055-62e67982-eab0-4bae-8391-ff4a3d725181.png)

And, I found the latest api of TST has changes from res_dropout to dropout. But the former still works and the latter doesn't work.
![image](https://user-images.githubusercontent.com/41911522/141952591-a740c5e7-5f78-414a-9b2a-2ff138fdec54.png)

**Comment by oguiza** [comment]
Those changes have been made to the current tsai version which is still under development. 
If you want to use you'd need to pip install it from GitHub: 
```bash
pip install git+https://github.com/timeseriesAI/tsai.git -U >> /dev/null
# NOTE: REMEMBER TO RESTART (NOT RECONNECT/ RESET) THE KERNEL/ RUNTIME ONCE THE INSTALLATION IS FINISHED
```
I'm planning to create a new release later this week. When done, these changes will be available with a regular pip install.

**Comment by yangtzech** [comment]
Due to network reason, I download a zip of the newest repository and run `python setup.py install`. It is the same as your command, right? 

But how to solve the typeerror?

**Comment by oguiza** [comment]
>Due to network reason, I download a zip of the newest repository and run python setup.py install. It is the same as your command, right?
No that is the same as the latest pip version. I've made some changes that are only available if you pip install directly from github.

**Comment by oguiza** [comment]
I've just created a new pip version (0.2.23). 
I'll close this issue now. Please, reopen it if necessary.
