### ISSUE TITLE
ModuleNotFoundError: No module named 'nbformat'

### ISSUE THREAD

**Issue by yangtzech** [timeseriesAI/tsai#261]
I ran the following command
`pip install -Uqq git+git://github.com/timeseriesAI/tsai.git`

Then the error came when importing modules. I comment out the code  in 'export.py' and problem is solved

![image](https://user-images.githubusercontent.com/41911522/141981040-7df976f3-63c4-463f-b058-ac4ee5fd47b7.png)

**Comment by oguiza** [comment]
Can you try to reinstall tsai from GitHub again please? I've added a missing dependency.

**Comment by yangtzech** [comment]
It is solved. Thanks.
