### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'nan_to_num'

### ISSUE THREAD

**Issue by yangtzech** [timeseriesAI/tsai#262]
I am sorry to interrupt again. But I ran the **Pretrain model**  in 08_Self_Supervised_TSBERT.ipynb. An error came.

```
# Unlabeled 100%
learn = ts_learner(udls100, InceptionTimePlus, cbs=[ShowGraph(), MVP(target_dir='./data/MVP', fname=f'{dsid}_200')])
learn.fit_one_cycle(200, 1e-2)
```

![image](https://user-images.githubusercontent.com/41911522/141986567-27f98b76-821e-4ef3-bf17-ea12036a5986.png)

error:
[error.txt](https://github.com/timeseriesAI/tsai/files/7546328/error.txt)

**Comment by oguiza** [comment]
Oh, sorry about that!
Pytorch 1.8 released torch.nan_to_num. I updated the function, but didn't realize that both fastai and tsai support Pytorch 1.7 as well. I've fixed this now. Please, try it again when you can and let me know if you find any issues.

**Comment by yangtzech** [comment]
It is solved. Thanks.
