### ISSUE TITLE
MVP question

### ISSUE THREAD

**Issue by yangtzech** [timeseriesAI/tsai#263]
- I tried the following code in Pretrain Model in 08_Self_Supervised_TSBERT.ipynb. Setting model to TSTPlus & InceptionTimePlus works fine. But choosing TST results in a error. And I found #86. So TST can't work with MVP right?

`RuntimeError: Given groups=1, weight of size [6, 165888, 1], expected input[2, 4608, 36] to have 165888 channels, but got 4608 channels instead`

- Then I tried it for my own data.

```
X      - shape: [232108 samples x 6 features x 2 timesteps]  type: ndarray  dtype:float64  isnan: 0
y      - shape: (232108,)  type: ndarray  dtype:<U7  n_classes: 1 (232108 samples per class) ['43650.0']  isnan: False
splits - n_splits: 2 shape: [185687, 46421]  overlap: False
```

- Choosing **InceptionTimePlus** works fine

![image](https://user-images.githubusercontent.com/41911522/141997831-e7728fe6-7973-4304-b6f2-909ac7f3796d.png)

```
tfms  = [None, [TSRegression()]]
batch_tfms = [TSStandardize(by_var=True)]
unlabeled_dls = get_ts_dls(x, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=64)
learn = ts_learner(unlabeled_dls, InceptionTimePlus, cbs=[MVP(fname=f'{modelname}', window_size=.5)]) # trained on variable window size
learn.fit_one_cycle(1, 3e-3)
```

- Choosing **TSTPlus** results in this.

`IndexError: The shape of the mask [64, 6, 1] at index 2 does not match the shape of the indexed tensor [64, 6, 2] at index 2`

![image](https://user-images.githubusercontent.com/41911522/141998284-4fa7b8ff-5cd7-4179-8e2d-6161636d41d3.png)
```
tfms  = [None, [TSRegression()]]
batch_tfms = [TSStandardize(by_var=True)]
unlabeled_dls = get_ts_dls(x, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=64)
learn = ts_learner(unlabeled_dls, TSTPlus, cbs=[MVP(fname=f'{modelname}', window_size=.5)]) # trained on variable window size
learn.fit_one_cycle(1, 3e-3)
```

**Comment by oguiza** [comment]
You are right @yangtzech, you cannot use TST with MVP.
Only models ending in Plus can be used. MVP needs a model with a backbone and head attributes.

**Comment by yangtzech** [comment]
Got it. But what about the error happend with TSTPlus in my data ?

**Comment by vrodriguezf** [comment]
Try removing the `window_size` argument when using TST. Variabl window sizes work good with convolutions, but transformers need a fixed sequence length

**Comment by yangtzech** [comment]
Problem solved. Thank you for your kind help.
