### ISSUE TITLE
how to name class labels?

### ISSUE THREAD

**Issue by vrodriguezf** [timeseriesAI/tsai#27]
Hi, 

How would you give names to the class labels in this package? I normally use a dictionaries like this, to convert indices into
```
lbl_dict = dict([
        ('-1.0', 'class 1'),
        ('0.0', 'class 2'),   
        ('1.0', 'class 3'),   
        ('2.0', 'class 4')]
    )
```

and then I add the function `lbl_dict.get` as part of the y `tfms`. It used to work for me in other fastai pipelines when creating the `Datasets` object, but using `TSDatasets` gives me a weird error about `retain_type` that I do not manage to understand. What is the easiest way to do this here?

Thank you! ;)

**Comment by oguiza** [comment]
Hi Victor,

I usually just fo it this way: 

```
dsid = 'NATOPS'
X, y, splits = get_UCR_data(dsid, return_split=False)
tfms = [None, Categorize()]
dls = get_ts_dls(X, y, splits=splits, tfms=tfms)
```

y consists of str labels:  memmap(['4.0', '3.0', '3.0', '4.0', '3.0', '5.0', '1.0', '6.0', '3.0', '2.0'], dtype='<U3')

but they are converted into TensorCategory([3, 2, 1, 2, 0, 3, 0, 2, 2, 3]). 
You can also see the dls vocab dict by doing: 
'''dls.vocab.o2i'''
which returns {'1.0': 0, '2.0': 1, '3.0': 2, '4.0': 3, '5.0': 4, '6.0': 5} .
Within Categorize you can pass your own dictionary or set add_na=True just in case there are new labels in valid or test sets.
I think the issue with your dictionary is that you want type int as output, not a str. 
Does this answer your question?

**Comment by vrodriguezf** [comment]
Thanks Ignacio,

I just want to add intermediate step between getting the ys from the data and calling Categorize, a step to "rename" the categories from '1.0' to 'class 1' within the `tfms` Pipeline. In your example, how would you pass from your y:

memmap(['4.0', '3.0', '3.0', '4.0', '3.0', '5.0', '1.0', '6.0', '3.0', '2.0'], dtype='<U3')

to a TensorCategory, renaming in the middle with 'class 1', 'class 2'...

**Comment by oguiza** [comment]
Ok. So the issue is more to rename labels that you get, before they are encoded in the TSDatasets. You then want any output (in show_batch, show_results, etc) to be decoded back to the new labels. 
Based on an offline conversation, this is the agreed solution:
```
dsid = 'NATOPS'
X, y, splits = get_UCR_data(dsid, split_data=False)
lbl_dict = {'#na#': 'unknown', '1.0': 'class_1', '2.0': 'class_2', '3.0': 'class_3', '4.0': 'class_4', '5.0': 'class_5', '6.0': 'class_6'}
tfms = [None, [lbl_dict.get, Categorize(add_na=True)]]
dls = get_ts_dls(X, y, splits=splits, tfms=tfms)
dls.show_batch()
```

**Comment by vrodriguezf** [comment]
only one more thing for people having the same issue. In the example given by @oguiza , the dtype of `y` is `<U3`. In my case the `dtype` was `str`. Moving my original numeric array to a `U3` with `y.astype('<U3')` made it work as expected.
