### ISSUE TITLE
Multivariant Classification fails at Dataset Generation

### ISSUE THREAD

**Issue by hno2** [timeseriesAI/tsai#274]
Hey everyone, 

I am currently looking into a use case where I want to classify a multivariate dataset (2 features with 15 timesteps and 1 target) 
I found #250 which is the same as my error, but I just updated all fastai+tsai from git so I should be at the latest version. 
<details>
<summary>Version Details</summary>

```
os             : macOS-10.16-x86_64-i386-64bit
python         : 3.9.6
tsai           : 0.2.23
fastai         : 2.5.4
fastcore       : 1.3.27
torch          : 1.9.1
n_cpus         : 4
device         : cpu
```

</details>

My Data looks like this, with `id` a unique id, `feature` one of two features and a `target` column with the targets.
![Bildschirmfoto 2021-11-23 um 09 15 45](https://user-images.githubusercontent.com/436990/142989907-ca87e6f0-6afc-4d6c-95be-8d6b81196b5a.png)
Using `df2Xy` yields ((146, 2, 15), (146, 2)) X and y ndarrays.
But creating a `TSDataset` is not possible as it yield the same `TypeError: unhashable type: 'numpy.ndarray'` (as in #250). 
```
/python3.9/site-packages/fastcore/basics.py in uniqueify(x, sort, bidir, start)
    579 def uniqueify(x, sort=False, bidir=False, start=None):
    580     "Unique elements in `x`, optionally `sort`-ed, optionally return reverse correspondence, optionally prepend with elements."
--> 581     res = list(dict.fromkeys(x))
    582     if start is not None: res = listify(start)+res
    583     if sort: res.sort()

TypeError: unhashable type: 'numpy.ndarray'
```
Two questions: 
1. Why is the duplicated `y` target needed
2. How can I fix this issue?

Thanks in advance for your help!

**Comment by oguiza** [comment]
Hi @hno2, 

Actually, the issue occurs because you are using a duplicated y. When you create the X and y, df2Xy doesn't know what the target shape should be. That's why if you only want a single target you should pass a y_func to df2Xy.
In your case you may pass this one: 

```bash
def y_func(o): return o[:, 0] # you only want the first value from each sample as they are the same
```

Please, try it and let me know if the issue is fixed.
