### ISSUE TITLE
On individual predict

### ISSUE THREAD

**Issue by shushan2017** [timeseriesAI/tsai#29]
I trained the model with this code：
#----------------------------------

 ` `

`   X, y, splits = combine_split_data([X_train, X_test], [y_train, y_test])
 tfms  = [None, [Categorize()]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits)
dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=64, batch_tfms=TSStandardize(by_var=True))
model = TST(dls.vars, dls.c, dls.len, res_dropout=0.3, fc_dropout=0.9)
learn = Learner(dls, model, loss_func=LabelSmoothingCrossEntropyFlat(), 
                metrics=[RocAucBinary(), accuracy],  cbs=ShowGraphCallback2())
learn.fit_one_cycle(15, lr_max=1e-3
learn.save('md1')
`

#------------------------------------
Then I want to use this model alone to predict new unlabeled data. X2, the structure is the same as X for training，I can see the example. It seems that the method can only be added. Can we use it like this, that is, we don't need to divide train, test and y
`dsets=TSDataset(X2)
dls   = TSDataLoaders.from_dsets(dsets, bs=[64, 128])
model = TST(dls.vars, dls.c, dls.len, res_dropout=0.3, fc_dropout=0.9)
learn = Learner(dls, model, loss_func=LabelSmoothingCrossEntropyFlat(), 
                metrics=[RocAucBinary(), accuracy],  cbs=ShowGraphCallback2())
learn.fit_one_cycle(15, lr_max=1e-3
learn.load('md1')`

But it didn't pass----------learn.load('md1')

**Comment by oguiza** [comment]
Hi @shushan2017,
Sorry for the late reply.
I've modified your code a bit and it now works well:

```
X_train, y_train, X_test, y_test = get_UCR_data('Heartbeat', split_data=True)
X, y, splits = combine_split_data([X_train, X_test], [y_train, y_test]) 
tfms = [None, [Categorize()]] 
batch_tfms=TSStandardize(by_var=True)
dls = get_ts_dls(X, y, tfms=tfms, splits=splits, bs=64, batch_tfms=batch_tfms) 
learn = ts_learner(dls, TST, res_dropout=0.3, fc_dropout=0.9, metrics=[RocAucBinary(), accuracy], cbs=ShowGraph()) 
learn.fit_one_cycle(15, lr_max=1e-3)
learn.save_all('md1')
del learn, dls  # This to simulate you end the session here and then restart a new one

learn = load_learner_all('md1')
probas, targets, preds = learn.get_X_preds(X_test, with_decoded=True)
learn.decoder(preds)
```
Please, make sure you use the latest version from git to use all this updated functionality:
```
!pip install -Uqq git+https://github.com/timeseriesAI/tsai.git@master
```
Please, try it and let me know if it works as expected.

**Comment by shushan2017** [comment]
Hi @oguiza 
 Thank you very much for your answer. This is a success, but there is another question: how to write code to save the "best" model
Places like this

`learn.fit_one_cycle(100, 1e-4,cbs=SaveModelCallback(comp=np.greater, monitor='roc_auc_score',fname='md1')) `
I can use it`learn.save_all('md1')` ？

**Comment by oguiza** [comment]
Hi @shushan2017, I'm glad to see it worked well for you.
As to your new question, you can use the SaveModelCallback (which will save the weights of the best model). 
If you want to use save all with the best model weights, you would need to do: 
```
learn = learn.load('md1') # loads the best model weights to learn.model
learn.save_all('md1')
```

**Comment by shushan2017** [comment]
Hi @oguiza
In accordance with your instructions, the code runs perfectly, thank you!!!!!
`import tsai
from tsai.all import *


X_train, y_train, X_test, y_test = get_UCR_data('FaceDetection', split_data=True)
X, y, splits = combine_split_data([X_train, X_test], [y_train, y_test]) 
tfms = [None, [Categorize()]] 
batch_tfms=TSStandardize(by_var=True)
dls = get_ts_dls(X, y, tfms=tfms, splits=splits, bs=64, batch_tfms=batch_tfms) 
learn = ts_learner(dls, TST, res_dropout=0.3, fc_dropout=0.9, metrics=[RocAucBinary(), accuracy], cbs=ShowGraph()) 
#learn.fit_one_cycle(5, lr_max=1e-3)
learn.fit_one_cycle(5, 1e-4,cbs=SaveModelCallback(comp=np.greater,monitor='roc_auc_score',fname='md1')) 

learn = learn.load("md1") # loads the best model weights to learn.model
'''
out info:
f:\Anaconda3\lib\site-packages\fastai\learner.py:54: UserWarning: Saved filed doesn't contain an optimizer state.
  elif with_opt: warn("Saved filed doesn't contain an optimizer state.")
'''
learn.save_all('md1')
del learn, dls  # This to simulate you end the session here and then restart a new one
learn = load_learner_all('md1')

probas, targets, preds = learn.get_X_preds(X_test, with_decoded=True)
probas, targets, preds

# the end

`
I don't know if there is any problem when I write this way

**Comment by oguiza** [comment]
Sorry I made a mistake. 
I didn't remember that fastai's SaveModelCallback loads the best model weights when the training is finished, so your code is ok except that you need to remove `learn = learn.load("md1") `.
Please, let me know if this works well.

**Comment by shushan2017** [comment]
Hi @oguiza
After I removed  learn = learn.load("md1") , the code worked fine, but I couldn't be sure 
`learn.save_all('md1')` 
Keep the best model, not the last one？
thank you！！！

**Comment by oguiza** [comment]
This is what I tried to explain before. 
`learn.save_all('md1)` will save the learner with the current status. 
If you add the SaveModelCallback that will save the best model during training, and when training finishes, it will upload the weights from the best model, so the `learn` object will contain the weights of the best models. If you then apply `save_all` you will have saved the learner with the best model. I hope it's clearer now.

**Comment by shushan2017** [comment]
Hi @oguiza
I see. Thank you for your patience. Have a good time!!!
