### ISSUE TITLE
create_future_mask is masking past or future?

### ISSUE THREAD

**Issue by vrodriguezf** [timeseriesAI/tsai#293]
Having a look at [the test of `create_future_mask`](https://github.com/timeseriesAI/tsai/blob/main/nbs/063_callback.MVP.ipynb), it seems to me that the masked part (pink) is the past of the sequence and not the future.
![image](https://user-images.githubusercontent.com/7083752/144471141-34b85405-ad8b-4e1c-b571-2e8eb7134aa9.png)

Am I understanding the function wrong?

**Comment by oguiza** [comment]
Good catch, @vrodriguezf! This is indeed a bug. The pink area (values = True) is the one that will be masked. 
I've already updated the repo.
Thanks, Victor!!


![image](https://user-images.githubusercontent.com/11656416/144486873-f58d3cf2-d0e3-44d4-ba8e-2974c2147dbb.png)

**Comment by vrodriguezf** [comment]
works like a charm! closing, thanks! ;)
