### ISSUE TITLE
.predict() for TSForecaster

### ISSUE THREAD

**Issue by jlequeux** [timeseriesAI/tsai#294]
the .predict() function do not work for TSForecaster

I trained a TSForecaster following the README example:
```python
from tsai.all import *
ts = get_forecasting_time_series("Sunspots").values
X, y = SlidingWindow(60, horizon=1)(ts)
splits = TimeSplitter(235)(y) 
batch_tfms = TSStandardize()
fcst = TSForecaster(X, y, splits=splits, batch_tfms=batch_tfms, bs=512, arch=TST, metrics=mae, cbs=ShowGraph())
fcst.fit_one_cycle(10, 1e-3)
```

Then I just tried to predict one value:

```python
fcst.predict(X[0:1, ...])
```

This returns an AttributeError:
```AttributeError: 'tuple' object has no attribute 'transpose'```
as the result from fastai trainer.predict [is a Tupple ](https://docs.fast.ai/learner.html#Learner.predict)
but the TST model tries to Transpose it

More trace:
```
/data/envs/plutus/lib/python3.8/site-packages/fastai/learner.py in _do_one_batch(self)
    170 
    171     def _do_one_batch(self):
--> 172         self.pred = self.model(*self.xb)
    173         self('after_pred')
    174         if len(self.yb):

/data/envs/plutus/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

/data/envs/plutus/lib/python3.8/site-packages/tsai/models/TST.py in forward(self, x, mask)
    206         # Input encoding
    207         if self.new_q_len: u = self.W_P(x).transpose(2,1) # Eq 2        # u: [bs x d_model x q_len] transposed to [bs x q_len x d_model]
--> 208         else: u = self.W_P(x.transpose(2,1)) # Eq 1                     # u: [bs x q_len x nvars] converted to [bs x q_len x d_model]
    209 
    210         # Positional encoding

AttributeError: 'tuple' object has no attribute 'transpose'
```

**Comment by oguiza** [comment]
Hi @jlequeux,
I've updated tsai's documentation. I believe it's clearer now. 
Please, take a look at: 

- examples in [index](https://timeseriesai.github.io/tsai/#Examples)
- (inference](https://timeseriesai.github.io/tsai/inference.html)

**Comment by jlequeux** [comment]
Thank you @oguiza ! This is working.

Is there a reason why some models (like MiniRocketRegressor) works with`.predict()` and others with `.get_X_preds()` ?
It might be useful to raise an error (like NotImplemented) for the on not to use.

**Comment by oguiza** [comment]
Yes, there is. 
The Rocket family (RocketClassifier, RocketRegressor, MiniRocketClassifier, and MiniRocketRegressor) are not deep learning models. They use numba instead of Pytorch and were developed (by the authors) with a sklearn-type API. 
All others are deep learning models that use Pytorch. They need to be trained using stochastic gradient descent. 
We also developed Rocket and MiniRocket in Pytorch since the original ones are recommended by the authors for a sample size <= 10k samples. 

Based on your feedback I'll close the issue. Please, reopen if necessary.
