### ISSUE TITLE
handling of non equally (too short sized) time series

### ISSUE THREAD

**Issue by geoHeil** [timeseriesAI/tsai#30]
Your code https://github.com/timeseriesAI/tsai/blob/master/tsai/data/preparation.py#L83 explicitly enforces time-series of at least 

```
window_length + stride + horizon > seq_len
```

And I think this is a good thing (in general). However, it does not allow to remove offending time-series (i.e. in the SlidingWindowPanel some individual devices might not have enough observations).

What do you think about adding a switch to auto ignore (i.e. catch the exception but remove these devices )?

**Comment by geoHeil** [comment]
I would suggest something along these lines:

```
for v in unique_id_values:
        try:
            x_v, y_v = SlidingWindow(window_length, stride=stride, start=start, get_x=get_x, get_y=get_y, y_func=y_func,
                                     horizon=0, seq_first=seq_first)(df[(df[unique_id_cols].values == v).sum(axis=1) == len(v)])
            _x.append(x_v)
            if y_v is not None: _y.append(y_v)
        except AssertionError:
            print(f'cannot use:{v} due to not enough records')

```

**Comment by oguiza** [comment]
Ok. I think it's a good suggestion.
I'll see what's the best way to incorporate it into the SlidingWindowPanel functionality.

**Comment by oguiza** [comment]
I've made some changes to vectorize the SlidingWindowPanel function, and have also made the changes you suggested. It'd be great if you would confirm they work as expected. SlidingWindowPanel should be now much faster than the previous version.

**Comment by geoHeil** [comment]
I have tested the too short time-series. This functionality works great now.
