### ISSUE TITLE
ensemble learning

### ISSUE THREAD

**Issue by yannicko-neuro** [timeseriesAI/tsai#309]
Hola Ignacio,
great work on this repository. Makes the implementation of models really easy and convenient. 
A suggestion from my side would be the implmentation of ensemble learning for things like inception time. We know that each model can be somewhat unreliable so its advantegeous to use the output of multiple models and then use methods like MEA to evaluate.
For now I am training my models multiple times and then iterate through them. Maybe an optional rgument can be passed to TSclassifier/regressor that automatizes this step for learning/inference and evaluation. 
I imagine the default could be 1 so it doesnt break the existing code a check if there are maybe multiple models (lets assume we name them your_model1, your_model2) in hwich case you would run something different.
For now I am using part of the inception time code (https://github.com/hfawaz/InceptionTime/tree/master/classifiers), namely nne.py.
Its not really an urgent thing to do, but I think it would improve usability and deployment. 
All the best,
Yannick

**Comment by oguiza** [comment]
Thanks for sharing this idea. 
It makes sense to create ensembles (at least for some models). For example, Fawaz (leading author of InceptionTime) recommends using an ensemble of models. 
I will need to analyze this in more depth to determine how much work would be required. I won't be able to do this for at least a month. 
It'd be great if anybody put together a PR :)

**Comment by vrodriguezf** [comment]
I normally automate this by running the training notebook with tools like papermill or wandb sweeps, but it's true that something included directly in the API could help!

**Comment by oguiza** [comment]
Closed due to lack of activity.
