### ISSUE TITLE
fast preprocessing

### ISSUE THREAD

**Issue by geoHeil** [timeseriesAI/tsai#31]
I love your new `SlidingWindowPanel`, but as you can easily imagine for even a moderate size of devices the current implementation using python loops and numpy (=single threaded implementation) is rather slow.

What do you think about adding a `num-jobs` parameter similar to scikit-learn which would use the CPU to auto-parallelize (perhaps via dask)?

**Comment by oguiza** [comment]
I know the SlidingWindow functionality is not streamlined. My idea is to vectorize it so that it runs faster. It's on my roadmap, but I can't still sat when it will be available.

**Comment by geoHeil** [comment]
I have an implementation for dask. Though it might not be *production-ready* it works. If you think it makes sense I could share it here and perhaps we could work together to make it available in tsai.

However, the main change is that I need to change the API of tsais SlidingWindow function to not accept the data frame as an implicit argument for the inner functions i.e. `SlidingWindow()()` but explicitly. 

Maybe there is a better way though.

If you think it would be great - I will share the implementation here as a first step and after some discussion, I could build a merge request.

**Comment by oguiza** [comment]
I have now vectorized the SlidingWindow and SlidingWindowPanel functionality. In my tests, it works between 20 and 100 times faster than the previous version, depending on the settings you use. Please, refer to the (Data preparation)[https://timeseriesai.github.io/tsai/data.preparation] section in the documentation for more details on how it works. 
I've tested it with a pandas DataFrame with 1M rows and 50 columns, and it returns the results in <10s.
It'd be great if you would test it with your data and confirm what sort of performance difference you find.

**Comment by geoHeil** [comment]
Great! I would love to try it. Could you release a new pip version so I can install it in my secured environment?

When recreating the environment (with a non pinned version of sktime) I observe the following problem:

```` 
---------------------------------------------------------------------------
ModuleNotFoundError   
     35 
     36 import tsai
---> 37 from tsai.all import *
     38 print('tsai       :', tsai.__version__)
     39 print('fastai     :', fastai.__version__)

~/development/conda_envs/myenv/lib/python3.8/site-packages/tsai/all.py in <module>
      2 from .imports import *
      3 from .utils import *
----> 4 from .data.all import *
      5 from .metrics import *
      6 from .learner import *

~/development/conda_envs/myenv/lib/python3.8/site-packages/tsai/data/all.py in <module>
      1 from .validation import *
      2 from .preparation import *
----> 3 from .external import *
      4 from .core import *
      5 from .preprocessing import *

~/development/conda_envs/myenv/lib/python3.8/site-packages/tsai/data/external.py in <module>
     17 from pyunpack import Archive
     18 from scipy.io import arff
---> 19 from sktime.utils.load_data import load_from_tsfile_to_dataframe
     20 
     21 # Cell

ModuleNotFoundError: No module named 'sktime.utils.load_data'
```

I know this is unrelated to the current thread - but also in your requirements https://github.com/timeseriesAI/tsai/blob/a216ba11197a3e65fd5c67415a5b288eeba56a46/settings.ini#L16 (i.e. not only in my conda env) you specify a flexible version. I fear that the load data function might be gone in a new version - perhaps we can investigate this together before making a new release.

**Comment by geoHeil** [comment]
Indeed: https://github.com/alan-turing-institute/sktime/blob/112ac501ac3aae0a4ff84b9dc1f3f43979a44cb8/CHANGELOG.rst there was a change a couple of days ago and the load data function seems to be gone.

At least I cannot view it in the source tree of the main branch. https://github.com/alan-turing-institute/sktime/pull/496/files seems to enhance it and add documentation - however https://github.com/alan-turing-institute/sktime/tree/master/sktime/utils has no load_data function

**Comment by geoHeil** [comment]
https://github.com/alan-turing-institute/sktime/issues/558

**Comment by geoHeil** [comment]
Inded: https://github.com/alan-turing-institute/sktime/blob/master/sktime/utils/data_io.py#L28 is now found here. I will create a pull request

**Comment by geoHeil** [comment]
Just realized you fixed this already yesterday and I was running into problems as  I was still using the version from pip. ;) 

@oguiza I can test the change as soon as you can release a new version on pip - as I can only install using the corporate artifactory. Native git-based installation is blocked in my environment due to security constraints.

**Comment by oguiza** [comment]
Ok, good. I've upgraded the library in pip now (to tsai 0.2.12) anyway.

**Comment by geoHeil** [comment]
@oguiza : For a y_func like:

```
things = np.array([1,0,0,1,1])
y_func=lambda o: np.sum(o.sum() > 0)
y_func(things)
```

which returns a scalar result the tsai code now fails with:

```
~/development/conda_envs/my_env/lib/python3.8/site-packages/tsai/data/preparation.py in _SlidingWindowPanel(df)
    178                 _x.append(x_v)
    179                 if return_: _.append([v.tolist()] * len(x_v))
--> 180                 if y_v is not None and len(y_v) > 0: _y.append(y_v)
    181             else: pv(f'cannot use {unique_id_cols} = {v} due to not having enough records', verbose)
    182 

TypeError: object of type 'numpy.int64' has no len()keykey
```

When instead using:

```
y_func=lambda o: [np.sum(o.sum() > 0)]
```

a list (where the len operator is defined) - the tsai code now fails with:

```
~/development/conda_envs/my_env/lib/python3.8/site-packages/tsai/data/preparation.py in _SlidingWindowPanel(df)
    173         _key = []
    174         for i, v in enumerate(progress_bar(unique_id_values)):
--> 175             x_v, y_v = SlidingWindow(window_len, stride=stride, start=start, get_x=get_x, get_y=get_y, y_func=y_func,
    176                                      horizon=horizon, seq_first=seq_first, check_leakage=check_leakage)(df[(df[unique_id_cols].values == v).sum(axis=1) == len(v)])
    177             if x_v is not None and len(x_v) > 0:

~/development/conda_envs/my_env/lib/python3.8/site-packages/tsai/data/preparation.py in _inner(o)
    123             if y_func is not None and len(y) > 0:
    124                 y = y_func(y)
--> 125             if y.ndim >= 2:
    126                 for d in np.arange(1, y.ndim)[::-1]:
    127                     if y.shape[d] == 1: y = np.squeeze(y, axis=d)

AttributeError: 'list' object has no attribute 'ndim'
```

after the update.

**Comment by oguiza** [comment]
Yes, I'm interested in making this function faster. However, before trying a more complex implementation I'd rather test the current one as it's been designed. 
It'd be good if you could test the SlidingWindowPanel without a y_func. I noticed that the vectorized implementation is much faster, but then the y_func calculation may slow things down. 
The second test would be to use define a function that is applied to the axis=1 like the one in the documentation: 
```
def y_max(o): return np.max(o, axis=1)
```
In this case, o is all extracted ys at once. axis 0 are the samples, axis1 is the extracted ys for each sample.
You can then just pass y_func=y_max. You will need to adapt this to your function. If I interpret what you are trying to do correctly (identify if at least one of the y values is >0), it'd be something like this:
```
def y_pos(o): return (o.sum(axis=1) > 0).astype(int)
```
In my tests, this approach works much faster than the previous one with lambda, as it calculates all values at once.
Please, let me know if you have any questions.

**Comment by geoHeil** [comment]
In my minimal example of:

```
def y_func(o): return (o.sum(axis=0) > 0).astype(int)
things = np.array([1,0,0,1,1])
y_func(things)

```
I have to use axis 0, I guess that for the real one in tsai  axis=1 is correct. Is this really the case

So when now applying your suggestion:

```
def y_func(o): return (o.sum(axis=1) > 0).astype(int)
```

the time is down to 2.5 hours instead of 3.

**Comment by oguiza** [comment]
I've rebuilt your example to show the ys from 3 samples: 
```
def y_func(o):
    return (o.sum(axis=1) > 0).astype(int)


things = np.array([[1, 0, 0, 1, 1], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0]])
y_func(things)
# array([1, 0, 1]) # output
```

> the time is down to 2.5 hours instead of 3.

I'm a bit confused with your timings. You mentioned in a separate issue it took you 1h to process 10k devices (I don't know how long the entire df is). An now that the function is vectorized you say it's 2.5-3h. Are you talking about the same dataset? Has it made it worse?
How big is it? In my tests, it took me <10 seconds to process a df with 2M rows and 10 columns. But I imagine that if your df is much larger, it would take much longer.

**Comment by geoHeil** [comment]
Indeed - the different issue was covering a different dataset/time-frame: it is still data from the same data source but now from a different period of time. And this is covering more devices.

**Comment by geoHeil** [comment]
Now with Dask the speed is: 10 hours. Much worse.
But I see a lot of:

```
Timed out trying to connect to inproc://ip/port/1 after 10 s'
```
Strangely, on small dummy data it works really fine and is really fast.

I guess I will work with your vectorized implementation for now.


My changes are:

- make your code for SlidingWindow accept the df directly - and not as an implicit parameter ( at least this is the name in scala - I am not sure if this applies in python). So far, I did not figure out how to get it to work in dask if using in your notation `function(args)(implicit args)`.
- start the dask client (and import some dask functions)
- modify the code as outlined below
- run it

```
...
### your code
 df.sort_values(by=sort_by, axis=0, ascending=ascending, inplace=True, ignore_index=True)
unique_id_values = df[unique_id_cols].drop_duplicates().values
_x = []
_y = []
_key = []


#### my suggestion (a bit hacky) START
remote_df = client.scatter(df, broadcast=True)
global_var = Variable(name="remote_data")
global_var.set(remote_df)

def slow_function(v):
    df_local = Variable(name="remote_data").get().result()
    return SlidingWindow(df_local[(df_local[unique_id_cols].values == v).sum(axis=1) == len(v)],window_len, stride=stride, start=start, get_x=get_x, get_y=get_y, y_func=y_func,
                  horizon=horizon, seq_first=seq_first, check_leakage=check_leakage)

# dask needs to be initialized outside
futures = client.map(slow_function, unique_id_values)
# tqdm needs to be initialized outside

#from dask.distributed import wait
#wait(futures)

for v in progress_bar(futures):
    try:
        v_res = v.result()
        x_v, y_v = v_res
        _x.append(x_v)
        if return_key: _key.append([v_res.tolist()] * len(x_v))
        if y_v is not None: _y.append(y_v)
    except AssertionError:
        pv(f'cannot use {unique_id_cols} = {v} due to not having enough records', verbose)
    except:
        pv(f'cannot use {unique_id_cols} = {v} check this one in more detail', verbose)

#### your code takes over again
X = concat(*_x)
```

Howeve, https://stackoverflow.com/questions/65302537/dask-distributed-single-machine-ip-assignment-loopback currently I strangely get timeout failures after the upgrade.
I could run dask on YARN and see how that goes though ... But do not want to over complicate things as long as the data is still only around 10GB.

**Comment by oguiza** [comment]
I still don't quite understand why it takes so long to process your data. I've tested with some large df and it works pretty well (20-100 times faster than before). 
Based on your comments, should I close this issue?

**Comment by geoHeil** [comment]
I guess it is fine to close it for now.
