### ISSUE TITLE
add stateful custom sklearn API type tfms: TSShrinkDataFrame, TSOneHotEncoder, TSCategoricalEncoder

### ISSUE THREAD

**Issue by oguiza** [timeseriesAI/tsai#313]

**Comment by vrodriguezf** [comment]
Sorry to refloat this, I see that `TSCategoricalEncoder` and `TSDateTimeEncoder` have not been exported. Is this intentional?

**Comment by oguiza** [comment]
Thanks for the gentle reminder. Good catch!
I've added both of them now, plus TSMissingnessEncoder.
