### ISSUE TITLE
Tsai unsupervised

### ISSUE THREAD

**Issue by rruizdeaustri** [timeseriesAI/tsai#314]
Hola Ignacio,

Do you plan to extend tsai with unsupervised algorithms like auto-encoders, etc ...

Muchas Gracias !!

Roberto

**Comment by oguiza** [comment]
Hi @rruizdeaustri,
There's already a self-supervised method in tsai called MVP. It's a method based on [A TRANSFORMER-BASED FRAMEWORK FOR MULTIVARIATE TIME SERIES REPRESENTATION LEARNING](https://arxiv.org/abs/2010.02803).
You can learn more about it in one of our tutorials: 
 https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/08_Self_Supervised_TSBERT.ipynb

**Comment by oguiza** [comment]
I'll close this issue due to a lack of response. Please, reopen if necessary.
