### ISSUE TITLE
Colab install issues

### ISSUE THREAD

**Issue by tcapelle** [timeseriesAI/tsai#315]
Hi Ignacio,

I am having trouble running tsai on colab (Pro or non Pro).

The install process works:
```
pip install tsai
```
but then importing the lib takes forever, I think it is related to Numba.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/18441985/146042390-086b2418-6d7b-42ab-a91f-173c38436aa8.png">
still waiting...

I am trying to run the `wandb` tutorial 🤘

**Comment by oguiza** [comment]
Hi @tcapelle,
Good to hear from you!
I've just tested it on a Colab Pro instance and it took 2 min 41 seconds. The main reason is that when I created the last pip release fastai wasn't supporting torch 1.10. So there's a dependency torch>=1.7,<1.10.
Colab has recently upgraded torch to 1.10. So to install tsai you need to uninstall torch.1.10 and install 1.9. 
I was already planning to create a new pip release that will remove that dependency. I'll try to release it later today or tomorrow. 
I'd appreciate any feedback if you have any idea on how to improve the W&B tutorial 🙂

**Comment by tcapelle** [comment]
I abandoned yesterday, but I was getting this:
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/18441985/146163018-2ae10caa-3d7a-45ad-a30a-be70e93bcb88.png">
I would say that the lib should load instantly, like fastai does (less than 5 secs). you may be able to make optional install of the other dependencies. So if the user don't need them, we can skip then.
In 2022 we will give first class support to time series in wandb so I want `tsai` to be the first =)

**Comment by oguiza** [comment]
Hi @tcapelle,
I've just created a new pip release (0.2.24). I've tested it in Colab and it takes about 30 seconds to install including all extras. 
But I agree with your approach and will review all dependencies to see which ones can be left as extras. 
I'd like to allow a pip install tsai and a pip install tsai[all_extras]. 
I've logged an issue (#318) for this purpose.
As to the wandb support to time series that'd be great. I'd love to know what you have in mind. We could set up a meeting to discuss this. 
It'd be good if you can check that tsai installs in Colab now and close this issue.

**Comment by tcapelle** [comment]
Yeah, hace rato que no hablamos =). Felices fiestas amigo.
