### ISSUE TITLE
Create tsai.basics to speed up loading

### ISSUE THREAD

**Issue by oguiza** [timeseriesAI/tsai#320]
from tsai.all import * loads all modules in tsai, which is convenient but takes a long time and it’s unnecessary in most cases.
It’d be useful to have an alternative that loads the most frequently used modules in tsai, like fastai.basics does. This would reduce the time to load the main modules.

**Comment by oguiza** [comment]
Additional information
Here's a time comparison performed in Google Colab. All timings are taken after a runtime restart.

* For benchmarking: 
   import fastai takes 0.009s
   from fastai.basics import * takes .4s 

* before fixing this issue :
   import tsai takes 0.006s   
   from tsai.basics import * is not available
   from tsai.all import * takes 158s
   
* after fixing this issue :
   import tsai takes 0.007s   
   from tsai.basics import * takes 4s
   from tsai.all import * takes 3s

This is a great performance improvement. You can continue using tsai as you were using it before, but it will load much faster.

The main reason for this improvement is that tsfresh (one of the dependencies is not loaded by default as it was before. It takes very long to load this library, and it's barely used in the library. There's no need to load it.

**Comment by vrodriguezf** [comment]
This is huge Ignacio, many thanks!

**Comment by oguiza** [comment]
> This is huge Ignacio, many thanks!

Thanks, Victor!! 😃
I'm now trying to also significantly reduce the time to pip install it.
