### ISSUE TITLE
bug in MVP code 

### ISSUE THREAD

**Issue by mvccn** [timeseriesAI/tsai#323]
in MVP.py [https://github.com/timeseriesAI/tsai/blob/main/tsai/callback/MVP.py](url), line 176:
   if self.weights_path is not None:
            transfer_weights( **learn.model**, self.weights_path, device=self.learn.dls.device, exclude_head=False)

the bolded part should self.learn.model, right?

**Comment by oguiza** [comment]
Yes, you are right. Good catch!
Do you want to submit a PR (if so follow guidelines on CONTRIBUTING.md) or do you prefer that I fix it?

**Comment by mvccn** [comment]
OK, I will submit it.
