### ISSUE TITLE
TS2VEC 

### ISSUE THREAD

**Issue by mvccn** [timeseriesAI/tsai#335]
I am wondering if you are interested in implementing TS2Vec(https://arxiv.org/abs/2106.10466). This is pretty new and they claimed that they had achieved better results on USC datasets than TST , Inception and many other current state of art models. The author implemented the code in https://github.com/yuezhihan/ts2vec. 
BTW, Happy Holidays!

**Comment by oguiza** [comment]
It sounds very interesting indeed. It's one of the models I'd certainly like to adapt to tsai (since it's already implemented). I'll read the paper in detail and review the code to see how much effort it'd take to add it to tsai.

**Comment by mvccn** [comment]
great. I looked at their code before, the model part should be straightforward, but they defined two their own loss functions, not sure where are the best places to adjust in tsai.

Michael

**Comment by oguiza** [comment]
Closed due to lack of activity.
