### ISSUE TITLE
'se' fixed to be 16 in MLSTM_FCN

### ISSUE THREAD

**Issue by 2533245542** [timeseriesAI/tsai#337]
Is there a reason for doing so?

https://github.com/timeseriesAI/tsai/blob/2d303c051617ad0bc9cb34bb037258f0c61f20b4/tsai/models/RNN_FCN.py#L75

**Comment by oguiza** [comment]
Hi @2533245542, 
Thanks for communicating this issue. 
No, no particular reason. It was just an oversight from my side. I've just fixed it in the repo.
