### ISSUE TITLE
when installing tsai : ModuleNotFoundError: No module named 'sktime.utils.load_data' 

### ISSUE THREAD

**Issue by MOREDataset** [timeseriesAI/tsai#34]
I am getting an error when installing tsai in colab:
`stable = True # True: latest version, False: stable version

import sys
ISCOLAB = 'google.colab' in sys.modules
if ISCOLAB:
    if stable: 
        !pip install tsai -q
    else:
        !pip install git+https://github.com/timeseriesAI/tsai.git -q
            
import tsai
from tsai.all import *
print('tsai       :', tsai.__version__)
print('fastai     :', fastai.__version__)
print('fastcore   :', fastcore.__version__)
print('torch      :', torch.__version__)`

The error is:

> ModuleNotFoundError: No module named 'sktime.utils.load_data'

Any help?

**Comment by MOREDataset** [comment]
Apparently, something changed in the sktime package and the solution is to change in tsai/data/external.py the following line:
`from sktime.utils.load_data import load_from_tsfile_to_dataframe` 
to
`from sktime.utils.data_io import load_from_tsfile_to_dataframe`

**Comment by mloning** [comment]
Yes, there a few changes in our new release https://github.com/alan-turing-institute/sktime/releases/tag/v0.5.0

**Comment by tcapelle** [comment]
I think it is important to pin every requirement of tsai to specific versions, to guarantee that everything works out of the box.
