### ISSUE TITLE
Training & Saving model and later on continue training on different data

### ISSUE THREAD

**Issue by Yarden234** [timeseriesAI/tsai#353]
Hello!
I wanted to know what will be the ideal way for me to train a model (let's say InceptionTime), save it to file, and later on continue training it with different data (off course, I want to continue to the train the model with latest weights that Iv'e saved to the file).
Thanks!

**Comment by TKassis** [comment]
TSAI makes this pretty easy to do. Here is a general outline of how you can do it:

```python
# Initial training and saving best performing model as determined by validation loss
learn = ts_learner(dls, 
InceptionTimePlus, 
pretrained=False, 
model_dir = 'trained_models',
cbs=[SaveModelCallback(monitor='valid_loss', name='my_model')]
)
learn.fit_one_cycle()

# Load the saved model with weights and train on new data
learn = ts_learner(
dls, 
InceptionTimePlus, 
pretrained=True, 
weights_path='my_model,
model_dir = 'trained_models',
cbs=[SaveModelCallback(monitor='valid_loss', name='my_model')]
)
learn.fit_one_cycle

```

**Comment by Yarden234** [comment]
Thanks you very much for the fast reply!
Maybe you should add a notebook to explain of this section and maybe Transfer learning / fine-tune on a new model.
thanks again!

**Comment by oguiza** [comment]
> TSAI makes this pretty easy to do. Here is a general outline of how you can do it:
Thanks a lot, @TKassis for your quick and accurate response! 🙌
