### ISSUE TITLE
Feature request: gMLP and GatedTabTransformer.

### ISSUE THREAD

**Issue by radi-cho** [timeseriesAI/tsai#354]
Hello and thank you for the maintenance of this helpful library.
I see that Multilayer Perceptron (Wang, 2016) and TabTransformer (Huang, 2020) are some of the implemented models. Recently we have been researching the impact of gating in ML architectures for tabular modeling and would request the addition of two new architectures.

- Pay Attention to MLPs - gMLP ([paper](https://arxiv.org/abs/2105.08050), [implementation](https://github.com/lucidrains/g-mlp-pytorch));
- The GatedTabTransformer ([paper](https://arxiv.org/abs/2201.00199), [implementation](https://github.com/radi-cho/GatedTabTransformer));

If the maintainers of the project agree with this proposal I can directly open pull requests with implementations adapted for the format of the `tsai` library.

**Comment by radi-cho** [comment]
@oguiza Should I open a PR?

**Comment by oguiza** [comment]
Hi @radi-cho,
Sorry for my late response.
Thanks for volunteering to add those 2 models. It'd be great to have a 2 PRs adding them to `tsai`.
Please, bear in mind the CONTRIBUTING.md guideline to create the PR to ensure they pass the CI tests.
It's also important to ensure the arguments of the models are aligned to the other models (you can use TabTransformer as a template). This is required so models can then be easily replaced in the learner. 
Please, let me know if you find any issues or need any help during the process.

**Comment by radi-cho** [comment]
Opened #362
