### ISSUE TITLE
Can I use my own dataset to train this net?

### ISSUE THREAD

**Issue by AnthonyFang623** [timeseriesAI/tsai#373]
I've seen all toturials, all of thoes used UEA & UCR datasets with useing get_UCR_data function, I don't understand how could I load my own dataset, could you give an example of this please? It will be a geate help. Thank you!

**Comment by vrodriguezf** [comment]
Absolutely, have a look at https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/00c_Time_Series_data_preparation.ipynb

**Comment by AnthonyFang623** [comment]
> Absolutely, have a look at https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/00c_Time_Series_data_preparation.ipynb

Thanks for replying me so quickly! That's very nice of you! 
I'm a beginner of deep learning, so forgive me if i am getting this wrong. What I need to do according to the toturial-00c is reshaping my data into a 3D numpy array and save them in a certen forder instead of using get_UCR_data function, then load them like 
        X = np.load('mydata.npy')
        y = np.load('mylabel.npy')
        X_3d = to3d(X)
        ......
and the rest process is just like the rest of toturial-00c?

Another question is the data I am processing is ECG data and each of them is 1min long. With sampling rate 256, my X should be like (mydata_number, 1, 15360) right? According to the requirement, the array should be (samples, features, time steps).

**Comment by vrodriguezf** [comment]
> save them in a certen forder

You don't need to store the reshaped data in a folder, just use it to create the TSDatasets

> Would 15360 is too big for this program?

Depends on the architecture that you use in the learner, but at a first glance I would say yes, try to use a lower sampling rate.

**Comment by AnthonyFang623** [comment]
> You don't need to store the reshaped data in a folder, just use it to create the TSDatasets
> Depends on the architecture that you use in the learner, but at a first glance I would say yes, try to use a lower sampling rate.

OK, I get that, I'll try it according to your advise, thank you very much!

**Comment by oguiza** [comment]
I'll close this issue based on the last comment. Please, reopen if necessary.
