### ISSUE TITLE
Argument `d_head`is not used in TSiTPlus

### ISSUE THREAD

**Issue by vrodriguezf** [timeseriesAI/tsai#380]
https://github.com/timeseriesAI/tsai/blob/6baf0ba2455895b57b54bf06744633b81cdcb2b3/tsai/models/TSiTPlus.py#L63

**Comment by oguiza** [comment]
Good catch, @vrodriguezf!
I've checked the ViT implementation that is the one I used as a blueprint to create TSiT and it doesn't use the d_head argument. So based on this, I decided to drop it. I've already fixed this issue in GitHub.

**Comment by oguiza** [comment]
I'll close this issue since I've checked that d_head is no longer an argument in TSiT in GitHub.
