### ISSUE TITLE
sktime 10.0.0 do not have "sktime.utils.data_io". Maybe you can consider to fix it :)

### ISSUE THREAD

**Issue by celtics1863** [timeseriesAI/tsai#386]
Today when I install tsai for the first time, I found a "import error" when from tsai.all import *
I degraded the version of sktime to 9.0.0 and it works. 
By when pip install derectly, version 10.0.0 will be installed and I think many fresh people will encounter this problem ,espetially when excute "from tsai.all import *" and find errors.
I suggest you can fix this bug and give fresh man better experience :)

**Comment by oguiza** [comment]
I'll fix this issue as soon as I find some time. 
For now I've created a new release that sets sktime version < 0.10.0. You can try installing it as indicated in the repo instructions.

**Comment by celtics1863** [comment]
> I'll fix this issue as soon as I find some time. For now I've created a new release that sets sktime version < 0.10.0. You can try installing it as indicated in the repo instructions.

Thank you for reply !
