### ISSUE TITLE
Two typos in FCNPlus model

### ISSUE THREAD

**Issue by ksachdeva** [timeseriesAI/tsai#390]
Typo 1:
`FCNPlus` ctor  is not passing `residual`, `act` and `act_kwargs` to `FCNBlockPlus` ctor

https://github.com/timeseriesAI/tsai/blob/646f3847c9568c619fea5b14f9b9df996652398f/tsai/models/FCNPlus.py#L15

Typo 2:
`BN1` instead of `BN1d`

https://github.com/timeseriesAI/tsai/blob/646f3847c9568c619fea5b14f9b9df996652398f/tsai/models/FCNPlus.py#L32

**Comment by oguiza** [comment]
This is a great catch, @ksachdeva! Thanks for submitting the PR to fix the issue.
