### ISSUE TITLE
Installation on M1 Mac in Pycharm

### ISSUE THREAD

**Issue by orthosku** [timeseriesAI/tsai#392]
I am a noob, FYI.
I'm not able to install tsai in PyCharm (running too slowly on Colab). 

Running into:

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
```

```
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  error: subprocess-exited-with-error
```

and same issue for matrixprofile. 

I tried multiple different python versions 3.8 to 3.10. I tried installing llvmlite and numba separately but couldn't install matrix profile. Would appreciate some help!

**Comment by oguiza** [comment]
As far as I understand Pytorch is working hard to support M1 on Mac. But as of now, they are not still supporting it. 
Have you been able to use Pytorch and fastai for example?

**Comment by orthosku** [comment]
I was using TensorFlow on Mac previously but doing further research learned that PyTorch is 'industry standard' as of recent. I was using fastai on Jupyter. 

Working in Juypter for me though! Thanks for responding.

**Comment by oguiza** [comment]
I'll close this issue as I believe the question has been answered. Please, reopen if necessary.
