### ISSUE TITLE
Tutorial for fine-tuning ?

### ISSUE THREAD

**Issue by FranciscoPalomares** [timeseriesAI/tsai#395]
Hi,
Is there a tutorial for fine-tuning a model? I think it would be necessary and I have not found it.
Thanks

**Comment by FranciscoPalomares** [comment]
Hi @dnth
You can transfer learning with FCN (Fully Convolutional Neural Network) in time series: https://arxiv.org/pdf/1811.01533.pdf  Transfer learning for time series classification

**Comment by oguiza** [comment]
Hi, @FranciscoPalomares  and @dnth,
There's already a [tutorial notebook](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/08_Self_Supervised_TSBERT.ipynb) in tsai that shows how to pretrain a model using a BERT-like approach and then fine-tune it.
In my experience though, fine-tuning doesn't work as well as using the pretrained weights and training all layers. 
Please, let me know if this is what you were looking for.

**Comment by dnth** [comment]
@FranciscoPalomares thanks for the information! 

@oguiza I didn't realize there's this notebook. Will check it out!

**Comment by FranciscoPalomares** [comment]
Hola @oguiza , I need something like this, but it's failing

`from tsai.imports import *
from tsai.models.layers import *
from torch import nn

dsid = 'Haptics'
X, y, splits = get_UCR_data(dsid, verbose=True, split_data=False)
tfms = [None, TSClassification()]
dls = get_ts_dls(X, y, splits=splits, tfms=tfms)
learn = ts_learner(dls, FCN, metrics=accuracy)
learn.fit(5)
#learn.plot_metrics()



def load_weights(model, model_source):
    pretrained_dict = model_source.state_dict()
  
    model_dict = model.state_dict()  
  
    # 1. filter out unnecessary keys
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict and 'fc'  not in k and 'gap'  not in k}
  
    # 2. overwrite entries in the existing state dict
    model_dict.update(pretrained_dict)
  
    model.load_state_dict(model_dict)
    
    
    #Change last layer
    classes = model.fc.out_features
    model.fc = nn.Linear(128, classes)
    
    return model
    

dsid = 'Adiac'
X, y, splits = get_UCR_data(dsid, verbose=True, split_data=False)
tfms = [None, TSClassification()]
dls2 = get_ts_dls(X, y, splits=splits, tfms=tfms)
learn2 = ts_learner(dls2, FCN, metrics=accuracy) 

learn2.model = load_weights(learn2.model, learn.model)

learn2.fit(5)`


Error: 
  File ".../site-packages/fastai/learner.py", line 426, in accumulate
    self.total += learn.to_detach(self.func(learn.pred, *learn.yb))*bs

TypeError: 'TensorCategory' object is not callable

**Comment by oguiza** [comment]
@FranciscoPalomares please, let me know if your question has been answered so I can close this issue. 
Gracias!!

**Comment by FranciscoPalomares** [comment]
@oguiza You can close this issue
