### ISSUE TITLE
How to assign the number of GPU when I will train my model?

### ISSUE THREAD

**Issue by chuzheng88** [timeseriesAI/tsai#402]
How to assign the number of GPU when I will train my model?
I does not see code example in tsai document.

**Comment by vrodriguezf** [comment]
You can use fastai's [`default_device`](https://github.com/fastai/fastai/tree/master/fastai/torch_core.py#L243) function

**Comment by oguiza** [comment]
Hi @chuzheng88,
There's a device argument that can be used when you create the dataloaders.

**Comment by chuzheng88** [comment]
> You can use fastai's [`default_device`](https://github.com/fastai/fastai/tree/master/fastai/torch_core.py#L243) function

Thanks, I have found the parameter of dataloaders, which can set the No. of GPU.

**Comment by chuzheng88** [comment]
> Hi @chuzheng88, There's a device argument that can be used when you create the dataloaders.

Got it thanks.
