### ISSUE TITLE
Why PredictionDynamics function was not work when I trained the model proposed in tasi document?

### ISSUE THREAD

**Issue by chuzheng88** [timeseriesAI/tsai#403]
I used the notebook example code in tasi document as follows:
![image](https://user-images.githubusercontent.com/17675722/154918082-47309cf7-0b8b-44f5-97d0-279ac6587ab3.png)

However, I did not see any dynamic picture that reflect my training model as follows:
![image](https://user-images.githubusercontent.com/17675722/154918386-9c69c30b-71d3-47b5-b7f8-ffefe9170779.png)

I want to know that my code is wrong or the PredictionDynamics function is not support Transformer model?

**Comment by chuzheng88** [comment]
I'm sorry, I have soleved the proposed problem.

**Comment by oguiza** [comment]
Ok. I’ll close the issue then.
