### ISSUE TITLE
MiniROCKETRegressor

### ISSUE THREAD

**Issue by jefferyanderson** [timeseriesAI/tsai#408]
I'm able to successfully use the new TSRegressor convenience approach for TST, InceptionTime, and others:
`learn = TSRegressor(X, y, splits=splits, batch_tfms=batch_tfms, arch=TST, metrics=mae, bs=512)`

But I'd like to test w/ MiniROCKETRegressor and MiniROCKETVotingRegressor.
When I try to do this, I'm given: `TypeError: __init__() got an unexpected keyword argument 'seq_len'`
What is the recommended approach to use the MiniROCKET regressors?
Thanks and Regards

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1021/3644312929.py in <module>
      4 
      5 # tsai_models RNN, RNNPlus, GRU, LSTM, MRNN_FCN,  TST, TSTPlus, InceptionTime, InceptionTimePlus, LSTM_FCN, XCMPlus, mWDN
----> 6 learn = TSRegressor(X, y, splits=splits, batch_tfms=batch_tfms, arch=MiniRocketRegressor, metrics=mae, bs=512) # , train_metrics=True, cbs=ShowGraph()
      7 learn.fit_one_cycle(35, learn.lr_find())
      8 

/tmp/ipykernel_1021/2743173668.py in __init__(self, X, y, splits, tfms, inplace, sel_vars, sel_steps, weights, partial_n, train_metrics, bs, batch_size, batch_tfms, shuffle_train, drop_last, num_workers, do_setup, device, arch, arch_config, pretrained, weights_path, exclude_head, cut, init, loss_func, opt_func, lr, metrics, cbs, wd, wd_bn_bias, train_bn, moms, path, model_dir, splitter, verbose)
     75             build_tabular_model(arch, dls=dls, device=device, arch_config=arch_config)
     76         else:
---> 77             model = build_ts_model(arch, dls=dls, device=device, verbose=verbose, pretrained=pretrained, weights_path=weights_path,
     78                                exclude_head=exclude_head, cut=cut, init=init, arch_config=arch_config)
     79         setattr(model, "__name__", arch.__name__)

~/.local/lib/python3.8/site-packages/tsai/models/utils.py in build_ts_model(arch, c_in, c_out, seq_len, d, dls, device, verbose, pretrained, weights_path, exclude_head, cut, init, arch_config, **kwargs)
    129             if v in arch.__name__]):
    130         pv(f'arch: {arch.__name__}(c_in={c_in} c_out={c_out} seq_len={seq_len} device={device}, arch_config={arch_config}, kwargs={kwargs})', verbose)
--> 131         model = arch(c_in, c_out, seq_len=seq_len, **arch_config, **kwargs).to(device=device)
    132     elif 'xresnet' in arch.__name__ and not '1d' in arch.__name__:
    133         pv(f'arch: {arch.__name__}(c_in={c_in} c_out={c_out} device={device}, arch_config={arch_config}, kwargs={kwargs})', verbose)

~/.local/lib/python3.8/site-packages/tsai/models/MINIROCKET.py in __init__(self, num_features, max_dilations_per_kernel, random_state, alphas, normalize_features, memory, verbose, scoring, **kwargs)
     76                                                                         max_dilations_per_kernel=max_dilations_per_kernel,
     77                                                                         random_state=random_state)),
---> 78                       ('ridgecv', RidgeCV(alphas=alphas, normalize=normalize_features, scoring=scoring, **kwargs))]
     79         store_attr()
     80         self._validate_steps()

TypeError: __init__() got an unexpected keyword argument 'seq_len'`

**Comment by oguiza** [comment]
Hi @jefferyanderson, 
MiniRocketRegressor and MiniRocketVotingRegressor are special types of models in tsai (same as MiniRocketClassifier and RocketVotingClassifier, RocketRegressor, RocketVotingRegressor, RocketClassifier and RocketVotingClassifier). They are not properly deep learning models. That's why you can't build a learner with them. 
Please, take a look at the [documentation](https://timeseriesai.github.io/tsai/models.MINIROCKET.html) to see how to use it.

**Comment by jefferyanderson** [comment]
@oguiza thanks, and apologies. I just found that and implemented it and was coming back to delete my comment! Appreciate the help.

**Comment by oguiza** [comment]
> @oguiza thanks, and apologies. I just found that and implemented it and was coming back to delete my comment! Appreciate the help.

No need to apologize. And thanks for your interest in the library.
I’ll close the issue based on your comment.
