### ISSUE TITLE
Valid loss and accuracy changes randomly

### ISSUE THREAD

**Issue by FranciscoPalomares** [timeseriesAI/tsai#412]
I have a problem. Valid loss and accuracy changes randomly in FCN model, and the model does not converge.Do I have to use it differently? For example:

```
dsid = 'NonInvasiveFetalECGThorax1'
print(dsid)
X, y, splits = get_UCR_data(dsid, verbose=False, split_data=False)
tfms = [None, TSClassification()]
dls = get_ts_dls(X, y, splits=splits, tfms=tfms)
learn = ts_learner(dls, FCN, metrics=accuracy)
learn.fit(200)
```

Epoch 134, 186....

██182       0.258223    0.588670    0.796438  00:00     
██183       0.249661    0.739284    0.746565  00:00     
██184       0.252911    3.633142    0.327226  00:00     
██185       0.254669    0.600458    0.783206  00:00     
██186       0.258261    1.321394    0.560305  00:00     
██187       0.254061    0.739019    0.750127  00:00     
██188       0.239846    0.370743    0.888041  00:00     
██189       0.231562    0.323117    0.892621  00:00     
██190       0.230640    1.813485    0.547583  00:00     
██191       0.237773    0.710824    0.774555  00:00     
██192       0.240087    1.298200    0.621374  00:00     
██193       0.254595    0.964907    0.675827  00:00     
██194       0.246868    0.874791    0.687532  00:00     
██195       0.234622    0.983128    0.688041  00:00     
██196       0.226938    0.626504    0.779644  00:00     
██197       0.226912    0.814686    0.713995  00:00     
██198       0.229283    0.706321    0.764885  00:00     
██199       0.229287    0.572842    0.802545  00:00

**Comment by oguiza** [comment]
Hola @FranciscoPalomares,
It's always a good idea to visualize the loss curve. If you do it you'll see it's pretty bumpy. Jus add cbs=ShowGraph() to the ts_learner.
Something you may want to do is to test other architectures. Not all work on all datasets. 
Assing regularization may also improve the result. 
I've tried this code and it worked quite well (although they may be others that work better. I haven't tried other architectures).
```bash
X, y, splits = get_UCR_data('NonInvasiveFetalECGThorax1', split_data=False)
tfms = [None, TSClassification()]
dls = get_ts_dls(X, y, splits=splits, tfms=tfms)
learn = ts_learner(dls, TSTPlus, fc_dropout=.5, 
                   loss_func=LabelSmoothingCrossEntropyFlat(),
                   metrics=accuracy, cbs=[ShowGraph()], train_metrics=True)
# learn.lr_find()
learn.fit(50, 1e-4)
``
`
Accuracy was about 90%.

**Comment by oguiza** [comment]
I'll close this issue as it seems the initial question has been answered. Please, reopen if necessary.
