### ISSUE TITLE
I wonder why only 'Nor' is displayed in dls.show_batch(sharvey=True).

### ISSUE THREAD

**Issue by DongHyukHwang** [timeseriesAI/tsai#416]
I'm running https://colab.research.google.com/github/timeseriesAI/tsai/blob/master/tutorial_nbs/01a_MultiClass_MultiLabel_TSClassification.ipynb line by line. 

I am using the latest version of tsai 0.3.0.
In the middle of following each line, you can see that all of my result screens are displayed as 'Nor' in the 

Visualize data
dls.show_batch(sharey=True) part. 

You can see that the 'ROT' value is also mixed in the web page. I wonder why this issue occurred.

**Comment by oguiza** [comment]
Hi @DongHyukHwang,
I've already fixed the code in GitHub. It'd be good if you could test that show_batch works well now.

**Comment by DongHyukHwang** [comment]
![Error](https://user-images.githubusercontent.com/26762205/159606713-f02830d9-7aaa-4a73-9082-c370500eb0de.jpg)

**Comment by DongHyukHwang** [comment]
Could you change the encoding to cp949?

**Comment by oguiza** [comment]
This seems to be a new issue unrelated to the original one. If it still persists, please create a new issue.
