### ISSUE TITLE
 Is there a paper on github to verify the code?

### ISSUE THREAD

**Issue by DongHyukHwang** [timeseriesAI/tsai#417]
Is there a paper where I can verify the code at https://colab.research.google.com/github/timeseriesAI/tsai/blob/master/tutorial_nbs/01a_MultiClass_MultiLabel_TSClassification.ipynb#scrollTo=dWvLQmrzJhQv? I want to check if the value I turned into the code matches the value in the paper.

**Comment by oguiza** [comment]
Hi @DongHyukHwang, 
There are many multiclass time series classification papers. Most of them use the UEA/UCR time series classification datasets. I’d suggest you visit http://www.timeseriesclassification.com/ where you’ll find several papers that use those datasets.
As to multi-label papers I haven’t seen many. I found 
[Multi-label Prediction in Time Series Data using Deep Neural Networks](https://arxiv.org/pdf/2001.10098.pdf) in a quick search. It seems it uses a couple of publicly available datasets.
cc: @williamsdoug
