### ISSUE TITLE
Bug with old TSTPlus models on v0.3.0: AttributeError: 'ScaledDotProductAttention' object has no attribute 'scale'

### ISSUE THREAD

**Issue by strakehyr** [timeseriesAI/tsai#418]
Hi all,
Just updated to v0.3.0 and when using an old (v.0.24) TST model to predict (same dataset) I get the following error:
`AttributeError: 'ScaledDotProductAttention' object has no attribute 'scale'`

I have yet to test this with a newly made model. Since I never tried v0.25, the error might come from that instead.

**Comment by strakehyr** [comment]
If it is an expected issue, should I close it?

**Comment by oguiza** [comment]
Hi @strakehyr,
Yes, it's expected. You can close it.
