### ISSUE TITLE
There are bugs about lr.find(suggestion=False)

### ISSUE THREAD

**Issue by EchizenMike** [timeseriesAI/tsai#419]
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-101-99bf292328da>](https://localhost:8080/#) in <module>()
      1 learn = ts_learner(dls, InceptionTimePlus, metrics=accuracy_multi)
----> 2 learn.lr_find(suggestion=False)
      3 # dls

TypeError: lr_find() got an unexpected keyword argument 'suggestion'

How can I solve it?

**Comment by oguiza** [comment]
You just need to remove suggestion and use learn.lr_find().

**Comment by oguiza** [comment]
I'll close this issue now. Please, feel free to reopen if necessary.
