### ISSUE TITLE
some questions of lr.find()

### ISSUE THREAD

**Issue by EchizenMike** [timeseriesAI/tsai#420]
In 01a_MultiClass_MultiLabel_TSClassification.ipynb
There is an error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-102-a0ded2c9b578>](https://localhost:8080/#) in <module>()
      1 learn = ts_learner(dls, InceptionTimePlus, metrics=accuracy_multi)
----> 2 learn.lr_find()
      3 # dls

19 frames
[/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py](https://localhost:8080/#) in binary_cross_entropy_with_logits(input, target, weight, size_average, reduce, reduction, pos_weight)
   2978 
   2979     if not (target.size() == input.size()):
-> 2980         raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
   2981 
   2982     return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)

ValueError: Target size (torch.Size([384])) must be the same as input size (torch.Size([2304]))

How can I solve it?

**Comment by oguiza** [comment]
This issue has been fixed.
