### ISSUE TITLE
Details about Transformer (TST in tsai) for time series data

### ISSUE THREAD

**Issue by chuzheng88** [timeseriesAI/tsai#426]
Hi, I'm back again.
I'm interested with Transformer (TST in tsai), and I have read the paper (Attention is All You Need). However, I want to know the difference between original Transformer for nlp and Transformer (in tsai ) for time series data. If TST comes from a paper, I want to read the paper.

**Comment by chuzheng88** [comment]
In addition, I'm also interested in another question. Original Transformer proposed in "Attention is All You Need" for NLP needs dictionary to encode/decode words, how does Transformer (TST in tsai) for time series regression task deal with this problem?

**Comment by strakehyr** [comment]
If you take a quick look at the documentation you can see that all the papers are always referenced quite clearly:

https://timeseriesai.github.io/tsai/models.TST.html 

Among other things, TST doesn't have a decoder. You can check the paper for full details in the link I provided.

**Comment by oguiza** [comment]
I'll close this issue since I believe the initial question has been answered. Please, reopen if necessary.
