### ISSUE TITLE
Question - How to use time series classifiers with tabular data 

### ISSUE THREAD

**Issue by ranihorev** [timeseriesAI/tsai#43]
Hey,

I noticed that the package includes support for tabular data and I was wondering if there is a way to combine that with time-series data, e.g. classify time-series with tabular data that contains some metadata for each input.

Thanks!

**Comment by vrodriguezf** [comment]
Hi, take a look at https://timeseriesai.github.io/tsai//models.MultiInputNet

**Comment by ranihorev** [comment]
Perfect, thanks @vrodriguezf! 👍
