### ISSUE TITLE
getting regression data returns _check_X() argument error

### ISSUE THREAD

**Issue by orishko-py** [timeseriesAI/tsai#430]
With regards to issue closed 2 weeks ago: https://github.com/timeseriesAI/tsai/issues/415
```
from tsai.all import *
X_train, y_train, X_test, y_test = get_regression_data('AppliancesEnergy')
```
returns `_check_X() got an unexpected keyword argument 'coerce_to_numpy'`
tsai version 0.3.0 @oguiza 
my_setup() output is: 

> os             : Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
python         : 3.7.12
tsai           : 0.3.0
fastai         : 2.5.3
fastcore       : 1.3.29
torch          : 1.10.0+cu111
n_cpus         : 2
device         : cpu

**Comment by oguiza** [comment]
Hi @orishko-py,
That's a but in version 0.3.0. I've already fixed it in the GitHub version (which will eventually become 0.3.1 in pip).
Since this is not available today in pip, you may be able to install tsai using: 
```python
pip install git+https://github.com/timeseriesAI/tsai.git
```

**Comment by oguiza** [comment]
I’ll close this issue since tsai 0.3.1 has been released.
