### ISSUE TITLE
update torch to 1.11

### ISSUE THREAD

**Issue by machielg** [timeseriesAI/tsai#434]
Installation of tsai on MacOS and Linux (Cuda 11.4 3080) fails because Toch 1.10 doesn't have recent OS/Cuda device support

**Comment by oguiza** [comment]
Hi @machielg,
I'm afraid I'm dependent on fastai. I'll be able to upgrade as soon as they do it. I know they are working on it.

**Comment by oguiza** [comment]
fastai 2.5.6 has just been released. It supports Pytorch 1.11.
I've just upgraded tsai to support fastai 2.5.6 in GitHub. I will create a new pip release within the next few days.

**Comment by machielg** [comment]
> 

👌🏻

**Comment by vrodriguezf** [comment]
This is great, thanks!

**Comment by oguiza** [comment]
tsai 0.3.1 (which supports Pytorch 1.11) was released yesterday.
