### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by yangtzech** [timeseriesAI/tsai#435]
The code can run correctly for the first time, but changing the parameters of `learn.fit_one_cycle()` and just running the jupyter notebook cell, where `learn.fit_one_cycle()` is, in the second time will get `TypeError: argument of type 'NoneType' is not iterable`.

Here is the [logs.txt](https://github.com/timeseriesAI/tsai/files/8309475/logs.txt).

![image](https://user-images.githubusercontent.com/41911522/159126170-2b0695cd-adc3-41bb-b809-e7e300afa13e.png)

**Comment by oguiza** [comment]
I'm sorry @yangtzech but I'll be unable to help unless you send some code snippet to reproduce the issue.

**Comment by yangtzech** [comment]
I'm sorry @oguiza  that the problem occurs occasionally, and I will try to post the code next time it occurs.

**Comment by oguiza** [comment]
Are you ok if I close this issue then? You can open a new one once you have some code that replicates it.

**Comment by yangtzech** [comment]
Ok, thanks!
