### ISSUE TITLE
GPU memory usage

### ISSUE THREAD

**Issue by yangtzech** [timeseriesAI/tsai#439]
The GPU usage is limited to 2.5GB approximately. I don't know whether it is because of my code. If so, is it possible to use more GPU and speed up?

**Comment by oguiza** [comment]
I'm sorry @yangtzech , but I don't understand your question. 
GPU memory is defined by your hardware. When installed tsai doesn't take any GPU memory. It's only when you start training a model that memory will be used.
You can always use more memory if you have the hardware.

**Comment by yangtzech** [comment]
I am running the code on a platform with 12GB GPU, but no matter how I change the parameters, the python used by tsai always only takes up 12 GB.

**Comment by oguiza** [comment]
Have you tried increasing the batch size?
There's no built-in limitation of the amount of GPU used in tsai.

**Comment by yangtzech** [comment]
I did try but it did not work. As there is no built-in limitation, I will check my code and platform settings. Thanks!
