### ISSUE TITLE
time series as images: fitting shape for weight

### ISSUE THREAD

**Issue by geoHeil** [timeseriesAI/tsai#44]
I was following the tutorial to convert time-series as Images. However:

```
Expected 3-dimensional input for 3-dimensional weight [32, 47, 3], but got 4-dimensional input of size [64, 47, 224, 224] instead
```

is the error I get for:

```
epochs = 10

def construct_learner():
    model = create_model(xresnet1d34, dls=dls)#, **k)
    return Learner(dls,  model, metrics=[accuracy, fbeta_score, precision, cohen_kappa, average_precision_score], 
                   loss_func = CrossEntropyLossFlat(weight=class_weights)
                  )
```

As I understand this is not transfer learning, rather training the network from scratch and the dimensions should fit. Is this correct?

**Comment by geoHeil** [comment]
Is there a list of which models would be useful image models? Or would you say any model besides the 1D CNNs?

**Comment by oguiza** [comment]
`tsai` currently support the XResNet variations included in fastai.vision.models.xresnet.py :

    'xresnet18', 'xresnet34', 'xresnet50', 'xresnet101', 'xresnet152',
    'xresnet18_deep', 'xresnet34_deep', 'xresnet50_deep', 'xresnet18_deeper',
    'xresnet34_deeper', 'xresnet50_deeper', 'xse_resnet18', 'xse_resnext18',
    'xresnext18', 'xse_resnet34', 'xse_resnext34', 'xresnext34',
    'xse_resnet50', 'xse_resnext50', 'xresnext50', 'xse_resnet101',
    'xse_resnext101', 'xresnext101', 'xse_resnet152', 'xsenet154',
    'xse_resnext18_deep', 'xse_resnext34_deep', 'xse_resnext50_deep',
    'xse_resnext18_deeper', 'xse_resnext34_deeper', 'xse_resnext50_deeper'

Other vision models can't be used because the ts 2 image transforms will create tensors with a channel per variable, and all torchvision models take only 3 channels.

**Comment by geoHeil** [comment]
thx
