### ISSUE TITLE
Inference with "only one sample" for TST? 

### ISSUE THREAD

**Issue by aashikazim** [timeseriesAI/tsai#449]
I was trying to do inference with only one sample at a time with the following provided code. 

```
from tsai.inference import load_learner
clf = load_learner("models/clf.pkl")
probas, target, preds = clf.get_X_preds(X[splits[0]], y[splits[0]])
```

But it gives the following exception. Would you please suggest me a solution? 

"Could not do one pass in your dataloader, there is something wrong in it"

Btw, I was getting the correct result for the provided sample.

**Comment by vrodriguezf** [comment]
Does `learn.predict` work for you?

**Comment by williamsdoug** [comment]
Hi @aashikazim, If I recall correctly,``` clf.get_X_preds``` expects a list of items.  In order to the the correct dimension for a single item list, try using ```clf.get_X_preds(X[splits[0:1]], y[splits[0:1]])```

**Comment by oguiza** [comment]
> Hi @aashikazim, If I recall correctly, clf.get_X_preds expects a list of items. In order to the the correct dimension for a single item list, try using clf.get_X_preds(X[splits[0:1]], y[splits[0:1]])

Exactly. All you need to do is to pass the sample with a shape [1 x n vars x seq length]. If you have a 2d array (X_sample) you can just use X_sample[None].

**Comment by aashikazim** [comment]
Hi, @williamsdoug and @oguiza. Thanks for answering my question. I tried your suggestion. I don't know why it is not working in my side. Please have a look at my code if I am doing anything wrong? 
![image](https://user-images.githubusercontent.com/44184392/160437653-972039e9-353b-43a6-823c-c6266d40b143.png)



@vrodriguezf , I also tried your suggestion also, it produces an error.
![image](https://user-images.githubusercontent.com/44184392/160437830-39e37741-0204-40f6-9076-af870374d985.png)

**Comment by oguiza** [comment]
You may need to update to the most recent version of tsai. 
If you can upgrade to the latest version in GitHub using: pip install git+https://github.com/timeseriesAI/tsai.git

**Comment by oguiza** [comment]
> 

There's no need to do that. 
All you need is: 
```python
test_probas, test_targets, test_preds = learn.get_X_preds(X_test) # X_test is a 3d numpy array [n_samples x n_vars x seq_len]
```
Please, take a look at the documentation about [inference](https://timeseriesai.github.io/tsai/inference.html).

**Comment by forhonourlx** [comment]
Understood. Many thanks!

**Comment by oguiza** [comment]
I'll close this issue based on the last comment. Please, reopen if necessary.
