### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by sarwanpasha** [timeseriesAI/tsai#451]
I am trying to run different architectures on the TS data but I am getting "ZeroDivisionError: division by zero" error. Can you tell me the issue? Here is my colab link
https://colab.research.google.com/drive/16Etn1okt8z1194ampx_c0-xHGvJF74o1?usp=sharing

**Comment by oguiza** [comment]
I’ll close this issue due to a lack of response. Please, reopen it if necessary.
