### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by Manu-Fraile** [timeseriesAI/tsai#460]
Hi, I was trying the following example code for Time Series Classification and got the error in the title:

```
from tsai.all import *

X, y, splits = get_classification_data('LSST', split_data=False)
batch_tfms = TSStandardize(by_sample=True)
mv_clf = TSClassifier(X, y, splits=splits, path='models', arch=InceptionTimePlus, batch_tfms=batch_tfms, metrics=accuracy, cbs=ShowGraph())
mv_clf.fit_one_cycle(10, 1e-2)
mv_clf.export("mv_clf.pkl")
```

**Comment by oguiza** [comment]
Hi @Manu-Fraile,
That's strange. I've never seen that issue before. 
The code seems to be ok. I've tried it and it works fine in my setup. 
Could you please run 
```python
my_setup()
```
and paste the output?

**Comment by oguiza** [comment]
I’ll close this issue due to lack of a response. If the issue persists please, reopen it.
