### ISSUE TITLE
How to save and load splits

### ISSUE THREAD

**Issue by oguiza** [timeseriesAI/tsai#464]
### Discussed in https://github.com/timeseriesAI/tsai/discussions/463

<div type='discussions-op-text'>

<sup>Originally posted by **yangtzech** April  8, 2022</sup>
I see there is Learner.save_all
 and load_all. But I just want to save the splits of data as my data is large and every time it takes lots of time to do the calculation. I tried to save splits into a .npy file, but that didn't work.</div>

**Comment by oguiza** [comment]
Hi @yangtzech,
Your question is very timely! I was actually struggling with this same issue yesterday. So I've decided to add 2 new functions to tsai.data.validation called save_splits and load_splits that facilitate the task. 
Here's the link to the [documentation](https://timeseriesai.github.io/tsai/data.validation.html#save_splits).
Please, let me know if this works for you.

**Comment by yangtzech** [comment]
Hi @oguiza ,
Thanks for your timely new functions. And I just tried it. When n_splits in get_splits is greater than 1, the load_splits could not work with `AttributeError: 'list' object has no attribute 'tolist'`. 





![image](https://user-images.githubusercontent.com/41911522/162564240-240e0691-8922-4b21-98d0-ba748490cd29.png)

**Comment by oguiza** [comment]
Ah, ok! I see. 
I've decided to make the function wider. I've replaced save_splits and load_splits with save_object and load_object. These functions will save and load not just splits, but Python objects in general. Please, try it with your splits and let me know if it works now.

**Comment by yangtzech** [comment]
I updated using `pip install -Uqq git+https://github.com/timeseriesAI/tsai.git`. But `NameError: name 'save_object' is not defined​` occured. I did restart jupyterlab and used `from tsai.all import *`.
![image](https://user-images.githubusercontent.com/41911522/162598744-c4c01c5f-b1bb-4b27-85dd-6fb1ebdc0d55.png)

**Comment by oguiza** [comment]
Good catch! I've already updated the save_object test. 
I'm not sure what is the issue with the installation.  You may need to remove your repo folder and pip install again.

**Comment by oguiza** [comment]
tsai 0.3.1 was released yesterday, so you can now perform a normal
```python
pip install tsai -U
```
and it should upgrade your current install. The new version includes the save_object function.

**Comment by yangtzech** [comment]
Thanks for your reminder, though I might not choose to upgrade due to model import compatiablity.
