### ISSUE TITLE
RuntimeError: Input type (torch.cuda.DoubleTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by lxxxsd** [timeseriesAI/tsai#468]
![image](https://user-images.githubusercontent.com/96508261/162685657-cd744c31-7908-43d8-a622-5283e6c4a00e.png)
What is the reason for this error?

**Comment by oguiza** [comment]
It seems that the input (X) is in float64 (DoubleTensor) while the weight in the model is in float32 (FloatTensor). 
I don't know if X is a np.ndarray or a torch.Tensor but make sure you set dype to float 32 (if array: X.astype('float32'), if tensor X.float())

**Comment by oguiza** [comment]
I’ll close this issue due to lack of response.
