### ISSUE TITLE
Installing from source fails on Windows (UnicodeDecodeError)

### ISSUE THREAD

**Issue by davnn** [timeseriesAI/tsai#470]
Hi everyone,

trying to install the package from source does not work for on Windows 10; it fails with `UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position [...]`. The problem also affects other packages (e.g. https://github.com/iitzco/faced/issues/21), but is easily solved by specifying an `encoding` in the `setup.py`, see PR.

**Comment by oguiza** [comment]
Thanks for sharing this issue and submitting a PR!
I'll review and approve asap.

**Comment by oguiza** [comment]
Hi @davnn,
I've just merged your PR. 
It'd be great if you could test it on a Windows machine (I don't have any available).

**Comment by davnn** [comment]
> Hi @davnn,
> 
> I've just merged your PR. 
> 
> It'd be great if you could test it on a Windows machine (I don't have any available).

I did (on my machine), seems to work fine 👍🏼

**Comment by oguiza** [comment]
Thanks a lot @davnn for submitting the PR!
Based on your feedback, I'll close this issue.
