### ISSUE TITLE
MiniRocket Import Error

### ISSUE THREAD

**Issue by nikhilbyte** [timeseriesAI/tsai#480]
I Tried running the tutorial notebook involving MiniRocket.
It looks like it isn't getting imported

**Comment by oguiza** [comment]
I've now updated [MiniRcoket tutorial nb](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/10_Time_Series_Classification_and_Regression_with_MiniRocket.ipynb). All issues have been fixed.

**Comment by nikhilbyte** [comment]
Okay Thanks
