### ISSUE TITLE
ValueError: Exception occured in `Recorder` when calling event `after_validate`: 	multi_class must be in ('ovo', 'ovr')

### ISSUE THREAD

**Issue by dfx1822375** [timeseriesAI/tsai#481]
When I used TST and Inception_time，this error occurred with the code.Maybe it's a problem in calculating RocAucBinary
<img width="437" alt="image" src="https://user-images.githubusercontent.com/79962395/163776929-bd913a81-4a37-47d4-98be-c9d03c27a97c.png">

**Comment by oguiza** [comment]
Hi @dfx1822375,
I'm sorry but with the information you have provided, there's no way to know what is the issue. 
When submitting an issue please send the entire stack trace and if possible a minimal code snippet to reproduce the issue.
I can only guess you might be using a target with more than 2 classes with RocAucBinary, which only works when there are 2 classes. If that is the case, you should replace RocAucBinary by RocAuc.

**Comment by lxxxsd** [comment]
metrics=[RocAucBinary(), accuracy]  Change to metrics=accuracy

**Comment by oguiza** [comment]
Issue closed due to lack of response. Please, reopen if necessary.
