### ISSUE TITLE
[Question] Incremental learning or partial fit with TST model?

### ISSUE THREAD

**Issue by aashikazim** [timeseriesAI/tsai#484]
Suppose, I have a TST learner that has been trained earlier. Now I want to train the model again (partial train) with some new samples, in an incremental fashion. Is there any method in tsai library that I can do that?

**Comment by oguiza** [comment]
Hi @aashikazim,
Thanks for raising this question. I've just released a new [tutorial notebook](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/14_Inference_Partial_Fit_and_Fine_Tune.ipynb) to try and explain how you can use your learner once it's been trained. Please, take a look at it and let me know if it answers your question.

**Comment by aashikazim** [comment]
Thanks a lot, @oguiza. That clearly explains what I was checking.

**Comment by oguiza** [comment]
Great!
I'll close this issue then. Thanks again!
