### ISSUE TITLE
SmeLU activation function not found

### ISSUE THREAD

**Issue by strakehyr** [timeseriesAI/tsai#495]
As answered in the newest implementation (#458), the newly (v. 0.3.1) added activation function SmeLU did not work for me when using it in a TSTPlus model:

```
    learn = ts_learner(dls, TSTPlus, ks = ks, n_layers = n_layers, d_model = d_model, 
                       n_heads = n_heads, dropout = dropout, act = 'SmeLU',
                       opt_func = SGD, loss_func = mse,
                       metrics=[mae, mse], cbs=cbs)
```
Also tried via the `TSTPlus` function, and the `build_ts_model` function. They all bring:

`ValueError: SmeLU is not available. You can use "relu", "gelu", or a callable`

**Comment by oguiza** [comment]
I've just fixed this issue on GitHub. Please, try it again if you have a chance.

**Comment by strakehyr** [comment]
Working perfectly. Thanks, chief.
