### ISSUE TITLE
TypeError: no implementation found for 'torch.Tensor.masked_fill_' on types that implement __torch_function__: [0x7f9d313fc330, 0x7f9d313fc750]

### ISSUE THREAD

**Issue by aappaappoo** [timeseriesAI/tsai#505]
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/97269542/167657804-01aea1bf-0c9a-478b-9335-ceff9e1bdd57.png">
why is that

**Comment by oguiza** [comment]
Hi @aappaappoo,
Please, whenever you report an issue copy and paste the full stack trace (and put it between ``` ). Otherwise, I'll be unable to help.

**Comment by jrfackler** [comment]
I had the same error which was caused by NaN values in my dataset.

https://github.com/timeseriesAI/tsai/issues/515

**Comment by oguiza** [comment]
I'll close this issue due to a lack of response.
