### ISSUE TITLE
Why are the output values all nan on this dataset

### ISSUE THREAD

**Issue by aappaappoo** [timeseriesAI/tsai#506]
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/97269542/167675163-0aa66c7f-8246-49c6-a49f-189964b5fefb.png">

**Comment by oguiza** [comment]
Hi @aappaappoo,
There are multiple reasons why this may occur. But one of the most common ones is that X contains nan values.
Have you checked if x2 has any nan values? If it does you need to decide how you'll deal with them (remove samples, replace by the median value, replace by zero, ...). There's a batch transform in tsai called Nan2Value that is helpful in these cases. You just need to add it to the list of transforms. By default, it replaces nan values with zeros.

**Comment by oguiza** [comment]
I'll close this issue due to a lack of response.
