### ISSUE TITLE
load_learner() returns AttributeError: 'dict' object has no attribute 'dls'

### ISSUE THREAD

**Issue by strakehyr** [timeseriesAI/tsai#507]
I believe the issue is tied to using cuda instead of CPU when training the model. The error was:
```
    learn = load_learner(model_path+'.pth')

  File "C:\Users\user\Anaconda3\lib\site-packages\fastai\learner.py", line 386, in load_learner
    if cpu: res.dls.cpu()

AttributeError: 'dict' object has no attribute 'dls'
```

**Comment by oguiza** [comment]
@strakehyr, could you please provide a code snippet to reproduce this issue? I've never seen it before.

**Comment by strakehyr** [comment]
Hi @oguiza I just found some old code and solved the issue by calling cpu = False in the arguments. Thank you.
