### ISSUE TITLE
Question: How to properly load a model. 

### ISSUE THREAD

**Issue by strakehyr** [timeseriesAI/tsai#509]
A bit of a follow-up on #507 : when loading a model through ` learn = load_learner(model_path+'.pth', cpu = False)` I get given a dictionary. 
This comes after training and exporting through:
 
```
learn = ts_learner(dls, TSTPlus, ks = hyp['ks'], n_layers = hyp['n_layers'], d_model = hyp['d_model'], 
                   n_heads = hyp['n_heads'], dropout = hyp['dropout'], attn_dropout = hyp['attn_dropout'], 
                   fc_dropout = hyp['fc_dropout'], opt_func = SGD, 
                   loss_func = mse, metrics=[mae, mse], cbs=cbs)
hyp['lr'] = learn.lr_find()[0]  
learn.fit_one_cycle(hyp['num_epochs'], hyp['lr'])
learn.save(save_path)
```
`export` seems to achieve the same as `save`. `load_model` seems to fit in the format but I cant feed it the path as well as the "opt" and "model" without throwing the following error:

`AttributeError: 'collections.OrderedDict' object has no attribute 'load_state_dict'`

Is there a way to turn the dictionary into the model when loading it? Or another way to load it?

Thanks again.

**Comment by oguiza** [comment]
Hi @strakehyr,
Please, take a look at this [notebook](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/14_Inference_Partial_Fit_and_Fine_Tune.ipynb). I believe this will clarify the difference between the export and save methods.

**Comment by strakehyr** [comment]
Thank you again, @oguiza.
