### ISSUE TITLE
When using self-supervised learning, I don't know how to define the input and output of the model

### ISSUE THREAD

**Issue by aappaappoo** [timeseriesAI/tsai#510]
When I was learning "08_Self_Supervised_TSBERT", I found that the code in the picture does not tell the model tensor the input data shape and output data shape. So I want to ask you how to define the model if I don't use ts_learner to train the model The input and output of the model c_in and c_out in tsai must be of type int. However, the input and output of the TSBERT method are both [batch, feature, seqlen]

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/97269542/168429041-450e0562-36de-44b8-883f-5ada79e1027a.png">

**Comment by oguiza** [comment]
There's no need to define the input or output shape to pretrain a model. The MVP callback takes care of that.
When you want to use the pretrained model in a particular task you'll need to pass the y to the dataloader as well as the c_out. But bear in mind the only part of the pretrained model you'll be using is the backbone (which doesn't use the c_out).
Does this answer your question?

**Comment by aappaappoo** [comment]
Thanks for your answer, I know that the MVP callback handles this automatically during pre-training. But I want to know how the MVP callback in the source code defines the input and output of the model? I didn't find the code for this part

**Comment by aappaappoo** [comment]
If I use TSTPlus to train a self-supervised model, the dimension of my input is torch.Size([64, 6, 36]), then the dimension of the output of the model should also be torch.Size([64, 6, 36]), So how to set the TSTPlus model parameter c_out, c_out seems to only be able to pass in an int type.

Is it defined by custom_head? But I seem to be wrong

![image](https://user-images.githubusercontent.com/97269542/168573836-253dcc0c-dac5-4eba-8052-103aa2df049b.png)

**Comment by oguiza** [comment]
I'm sorry but I don't understand what is your issue.
Please, follow the instructions in [https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/08_Self_Supervised_TSBERT.ipynb](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/08_Self_Supervised_TSBERT.ipynb). 
When building the model you want to pretrain, you don't need to pass any custom head. All you need to do is to pass the MVP callback to ts_learner. It will take care of the model's head.
In the tutorial notebook there's no custom head used.

**Comment by aappaappoo** [comment]
Excuse me. I would like to ask, how can I train my self-supervised model without using MVP callback? How to define the input and output of the model? such as the TSTPlus model

**Comment by oguiza** [comment]
The only self-supervised training method in the tsai library uses MVP. It’s the easiest way to pretrain a model. And it’s based on a published method.
If you don’t want to use MVP you’d need to create a custom training script and define your own self-supervised method.
