### ISSUE TITLE
Learning rate decay

### ISSUE THREAD

**Issue by dfx1822375** [timeseriesAI/tsai#511]
Hi @oguiza :
     Hello, I would like to know if there is a way to achieve decay of the learning rate during the training of the network in tsai

**Comment by oguiza** [comment]
Hi @dfx1822375,
tsai uses fastai. LR decay is applied by default if you use learn.fit_one_cycle. Please, take a look at fastai's documentation about this functionality(https://docs.fast.ai/callback.schedule.html#Learner.fit_one_cycle)

**Comment by oguiza** [comment]
I'll close this issue due to the lack of response.
