### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by aappaappoo** [timeseriesAI/tsai#517]
from tsai.models.InceptionTimePlus import InceptionTimePlus
import numpy as np
from tsai.data.external import get_UCR_data, check_data
from tsai.data.preprocessing import TSStandardize, TSNan2Value
from tsai.data.core import TSCategorize, get_ts_dls
from tsai.learner import ts_learner
from tsai.models.InceptionTimePlus import InceptionTimePlus
from tsai.callback import MVP

dsid = 'MoteStrain'
X, y, splits = get_UCR_data(dsid, split_data=False)
check_data(X, y, splits, False)
X[X<-1] = np.nan # T

tfms  = [None, [TSCategorize()]]
batch_tfms = [TSStandardize(by_var=True)]
unlabeled_dls = get_ts_dls(X, splits=splits, tfms=tfms, batch_tfms=batch_tfms)
learn = ts_learner(unlabeled_dls, InceptionTimePlus, cbs=[MVP(fname=f'{dsid}', window_size=(.5, 1))]) # trained on variable window size
learn.fit_one_cycle(1, 3e-3)

The error code is as follows:
![image](https://user-images.githubusercontent.com/97269542/169650548-5956eefc-b802-4fc0-bf27-0b46ba1d668f.png)

**Comment by oguiza** [comment]
In the error, it says that you are calling a module in this line: 
```python
learn = ts_learner(unlabeled_dls, InceptionTimePlus, cbs=[MVP(fname=f'{dsid}', window_size=(.5, 1))]) # trained on variable window size
```
There are only 2 objects you are calling (ts_learner and MVP). One of them is a module instead of an object because it's incorrectly imported. I'll let you figure out which one it is.

**Comment by oguiza** [comment]
I'll close this issue due to the lack of response.
