### ISSUE TITLE
Is the predicted result erratic?

### ISSUE THREAD

**Issue by shushan2017** [timeseriesAI/tsai#52]
I use TST model to predict new data, but the results seem to be inconsistent every time I run, and the length of new data interception also seems to affect the prediction results. Is there any way I can fix the prediction results? This is very important to me. Thank you,

**Comment by oguiza** [comment]
Hi @shushan2017,
I've looked into this issue but I'm unable to reproduce it. In my tests the results are always the same. You can try them with this code:
```
X, y, splits = get_UCR_data('NATOPS', split_data=False)
tfms = [None, TSClassification()]
batch_tfms = [TSStandardize(by_var=True)]
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=512)
learn = ts_learner(dls, TSTPlus, metrics=accuracy)
learn.fit_one_cycle(50, 1e-3)
y_pred1 = learn.get_X_preds(X[splits[0]])[0]
y_pred2 = learn.get_X_preds(X[splits[0]])[0]
torch.equal(y_pred1, y_pred2)
```

**Comment by shushan2017** [comment]
I'm sorry. According to your instructions, I carefully checked my data. It turned out that there were some hidden problems in my input data. Now it's done!

Thank you very much. It's a great project! Almost perfect!!

**Comment by oguiza** [comment]
Ok, no problem. 
Thanks for your kind words. I'm glad you like `tsai` but it's far from being perfect :)
We'll only be able to make it better if we use it and report issues/ bugs.
