### ISSUE TITLE
Understanding GradCAM

### ISSUE THREAD

**Issue by IKetchup** [timeseriesAI/tsai#526]
Hello,

Im not sure to understand the figures ploted by show_gradcam() from the XCM model.

Does anyone could explain me the results?

Her is an example of plot that I get with show_gradcam() : 
 
![image](https://user-images.githubusercontent.com/72007646/170278054-5e3a2fef-a3cf-48fb-a608-3ab3a3d1d251.png)

**Comment by IKetchup** [comment]
@vrodriguezf thanks. Can you correct me if I'm wrong. the x axis is the time (corresponding to the time windows), and the y axis correspond to the features in the multivariates timeseries.

**Comment by IKetchup** [comment]
Thanks @vrodriguezf. So in the 2D gradCAM the X axis correspond to the variables and the Y axis to when they have be impactfull in the sequence ?

**Comment by oguiza** [comment]
> I believe it's the other way around

Exactly.

**Comment by oguiza** [comment]
I'll close this issue as it seems to be resolved. Please, reopen if necessary.
