### ISSUE TITLE
Custom Dataset and Training Procedure on tsai models

### ISSUE THREAD

**Issue by Waterkin** [timeseriesAI/tsai#529]
Hi,

I am recently obsessed with `tsai`, and try using it for many many days, around like two weeks.
However, it is difficult for me to custom my training procedure for `tsai` models on my custom dataset.

①For Custom Training Method: 
I'd like to write my training code, as I want to do meta-learning rather than using `fit_one_cycle`
For example:
```
for n in num_steps:
    update params
params = outer_step * (update params - params)
```

②For Custom Dataset: 
I am wondering how to transform my dataset to combine with `tsai`, as it has been already split in to 3 different parts for different training procedures.
Thus, there's no `split` here, so I also can't use `fit_one_cycle`.

Is there any way to simply create a TSClassifier and train it with my custom training methods?

Thanks a lot for people who contributed to this repo! ^_^

**Comment by vrodriguezf** [comment]
You can use `combine_split_data` as a way of merging separated datsets into a single X,y,splits triplet.

In terms of meta-learning and customising the training loop...I'd rather look at the fastai's training loop and its callback system to tweak it.

**Comment by vrodriguezf** [comment]
You can use `combine_split_data` as a way of merging separated datsets into a single X,y,splits triplet.

In terms of meta-learning and customising the training loop...I'd rather look at the fastai's training loop and its callback system to tweak it.

**Comment by oguiza** [comment]
I'll lclose this issue as it seems to be solved. Please, reopen if necessary.
