### ISSUE TITLE
Issues with multi-label classification inference

### ISSUE THREAD

**Issue by SimonOuellette35** [timeseriesAI/tsai#534]
I have a dataset where my labels are a list of the classes that are relevant for each sample. Example: y[0] = [1, 5, 8] if that sample has labels 1, 5 and 8 respectively.

I train my model as follows:

```
tfms  = [None, TSMultiLabelClassification()] # TSMultiLabelClassification() == [MultiCategorize(), OneHotEncode()]
batch_tfms = TSStandardize()
dls = get_ts_dls(X, multi_y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=bs)
dls.dataset
```

>> [(TSTensor(vars:16, len:100, device=cpu, dtype=torch.float32), TensorMultiCategory([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])), ...

So X has a dimensionality of 16, sequence length of 100. My y gets one-hot encoded to a vector of 12 elements. So far so good.

I train:

```
model = TST(dls.vars, dls.c, seq_len, d_model=256, n_layers=6, d_ff=512, n_heads=8, dropout=0.4)
learn = Learner(dls, model, metrics=[partial(accuracy_multi, by_sample=True), partial(accuracy_multi, by_sample=False)], cbs=[ShowGraphCallback2(), SaveModel()])
learn.fit_one_cycle(n_epochs, lr_max=1e-3)
```

Training goes as expected, no visible issues.

I load the saved model:

```
learn.load('model')
learn.validate()
```

Validate() actually works as expected.

And then I try to infer from a X batch:

```
x = X[-25:]
# I pass an X with 3 dimensions [batch_size x n_vars x seq_len]
results = learn.get_X_preds(x)
```

**I get the following error message:**

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
----> 6 results = learn.get_X_preds(x)

14 frames
[/usr/local/lib/python3.7/dist-packages/tsai/inference.py](https://localhost:8080/#) in get_X_preds(self, X, y, bs, with_input, with_decoded, with_loss)
     17     output = list(self.get_preds(dl=dl, with_input=with_input, with_decoded=with_decoded, with_loss=with_loss, reorder=False))
     18     if with_decoded and len(self.dls.tls) >= 2 and hasattr(self.dls.tls[-1], "tfms") and hasattr(self.dls.tls[-1].tfms, "decodes"):
---> 19         output[2 + with_input] = self.dls.tls[-1].tfms.decode(output[2 + with_input])
     20     return tuple(output)

[/usr/local/lib/python3.7/dist-packages/fastcore/transform.py](https://localhost:8080/#) in decode(self, o, full)
    206 
    207     def decode  (self, o, full=True):
--> 208         if full: return compose_tfms(o, tfms=self.fs, is_enc=False, reverse=True, split_idx=self.split_idx)
    209         #Not full means we decode up to the point the item knows how to show itself.
    210         for f in reversed(self.fs):

[/usr/local/lib/python3.7/dist-packages/fastcore/transform.py](https://localhost:8080/#) in compose_tfms(x, tfms, is_enc, reverse, **kwargs)
    148     for f in tfms:
    149         if not is_enc: f = f.decode
--> 150         x = f(x, **kwargs)
    151     return x
    152 

[/usr/local/lib/python3.7/dist-packages/fastcore/transform.py](https://localhost:8080/#) in decode(self, x, **kwargs)
     72     def name(self): return getattr(self, '_name', _get_name(self))
     73     def __call__(self, x, **kwargs): return self._call('encodes', x, **kwargs)
---> 74     def decode  (self, x, **kwargs): return self._call('decodes', x, **kwargs)
     75     def __repr__(self): return f'{self.name}:\nencodes: {self.encodes}decodes: {self.decodes}'
     76 

[/usr/local/lib/python3.7/dist-packages/fastcore/transform.py](https://localhost:8080/#) in _call(self, fn, x, split_idx, **kwargs)
     81     def _call(self, fn, x, split_idx=None, **kwargs):
     82         if split_idx!=self.split_idx and self.split_idx is not None: return x
---> 83         return self._do_call(getattr(self, fn), x, **kwargs)
     84 
     85     def _do_call(self, f, x, **kwargs):

[/usr/local/lib/python3.7/dist-packages/fastcore/transform.py](https://localhost:8080/#) in _do_call(self, f, x, **kwargs)
     87             if f is None: return x
     88             ret = f.returns(x) if hasattr(f,'returns') else None
---> 89             return retain_type(f(x, **kwargs), x, ret)
     90         res = tuple(self._do_call(f, x_, **kwargs) for x_ in x)
     91         return retain_type(res, x)

[/usr/local/lib/python3.7/dist-packages/fastcore/dispatch.py](https://localhost:8080/#) in __call__(self, *args, **kwargs)
    121         elif self.inst is not None: f = MethodType(f, self.inst)
    122         elif self.owner is not None: f = MethodType(f, self.owner)
--> 123         return f(*args, **kwargs)
    124 
    125     def __get__(self, inst, owner):

[/usr/local/lib/python3.7/dist-packages/tsai/data/core.py](https://localhost:8080/#) in decodes(self, o)
    192             raise KeyError(f"Labels '{diff_str}' were not included in the training dataset")
    193         return TensorMultiCategory(one_hot([self.vocab.o2i[o_] for o_ in o], self.c).float())
--> 194     def decodes(self, o): return MultiCategory([self.vocab[o_] for o_ in one_hot_decode(o, None)])
    195 
    196 # Cell

[/usr/local/lib/python3.7/dist-packages/fastai/torch_core.py](https://localhost:8080/#) in one_hot_decode(x, vocab)
    603 # Cell
    604 def one_hot_decode(x, vocab=None):
--> 605     return L(vocab[i] if vocab else i for i,x_ in enumerate(x) if x_==1)
    606 
    607 # Cell

[/usr/local/lib/python3.7/dist-packages/fastcore/foundation.py](https://localhost:8080/#) in __call__(cls, x, *args, **kwargs)
     95     def __call__(cls, x=None, *args, **kwargs):
     96         if not args and not kwargs and x is not None and isinstance(x,cls): return x
---> 97         return super().__call__(x, *args, **kwargs)
     98 
     99 # Cell

[/usr/local/lib/python3.7/dist-packages/fastcore/foundation.py](https://localhost:8080/#) in __init__(self, items, use_list, match, *rest)
    103     def __init__(self, items=None, *rest, use_list=False, match=None):
    104         if (use_list is not None) or not is_array(items):
--> 105             items = listify(items, *rest, use_list=use_list, match=match)
    106         super().__init__(items)
    107 

[/usr/local/lib/python3.7/dist-packages/fastcore/basics.py](https://localhost:8080/#) in listify(o, use_list, match, *rest)
     57     elif isinstance(o, list): res = o
     58     elif isinstance(o, str) or is_array(o): res = [o]
---> 59     elif is_iter(o): res = list(o)
     60     else: res = [o]
     61     if match is not None:

[/usr/local/lib/python3.7/dist-packages/fastai/torch_core.py](https://localhost:8080/#) in <genexpr>(.0)
    603 # Cell
    604 def one_hot_decode(x, vocab=None):
--> 605     return L(vocab[i] if vocab else i for i,x_ in enumerate(x) if x_==1)
    606 
    607 # Cell

[/usr/local/lib/python3.7/dist-packages/fastai/torch_core.py](https://localhost:8080/#) in __torch_function__(self, func, types, args, kwargs)
    339         convert=False
    340         if _torch_handled(args, self._opt, func): convert,types = type(self),(torch.Tensor,)
--> 341         res = super().__torch_function__(func, types, args=args, kwargs=kwargs)
    342         if convert: res = convert(res)
    343         if isinstance(res, TensorBase): res.set_meta(self, as_copy=True)

[/usr/local/lib/python3.7/dist-packages/torch/_tensor.py](https://localhost:8080/#) in __torch_function__(cls, func, types, args, kwargs)
   1140 
   1141         with _C.DisableTorchFunction():
-> 1142             ret = func(*args, **kwargs)
   1143             if func in get_default_nowrap_functions():
   1144                 return ret

**RuntimeError: Boolean value of Tensor with more than one value is ambiguous**

**Comment by gitusrnm** [comment]
I have exactly the same issue: [https://github.com/timeseriesAI/tsai/issues/533](url)

**Comment by SimonOuellette35** [comment]
I seem to have found a simple workaround for now, I hope this helps figure out the issue:

I wrote my own get_X_preds() function:

`    def get_X_preds(X, bs):
        dl = learn.dls.valid.new_dl(X, y=None, bs=bs)
        output = list(learn.get_preds(dl=dl,
                                      with_input=False,
                                      with_decoded=False,
                                      with_loss=False,
                                      reorder=False))
        return tuple(output)`

This actually works for me.

**Comment by oguiza** [comment]
Hi @SimonOuellette35,
Sorry for the late reply.
I've fixed an issue that impacted MultiLabel tasks. 
I've tested a similar case to yours and it works well (see [gist](https://colab.research.google.com/gist/oguiza/f1205fdbe2565be1c62074bb3591aca7/scratchpad.ipynb)).
