### ISSUE TITLE
How to convert between "get_ts_dls" and "torch.utils.data.DataLoader"

### ISSUE THREAD

**Issue by aappaappoo** [timeseriesAI/tsai#542]
I want to use tsai for model training and torch for model inference, so I need to convert "get_ts_dls" and "torch.utils.data.DataLoader"

**Comment by oguiza** [comment]
Sorry, but tsai uses its own dataloaders that perform multiple operations out of the box. If you want to use a  Pytorch vanilla DataLoader you'll need to manage that on your own.
