### ISSUE TITLE
About transformer classification

### ISSUE THREAD

**Issue by liuyuanhao** [timeseriesAI/tsai#545]
Hello,
I see you have the API for TSclassification, but I don't know if you have an example of classifying time series with a transformer (it would be better if it is multivariate time series classification); Could you tell me?

Thank u so much!

**Comment by zmce2018** [comment]
Hi Liu 

You can see the tutorial here for using transformer-based time series classification. 
https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/07_Time_Series_Classification_with_Transformers.ipynb

**Comment by liuyuanhao** [comment]
Hello,
If I use TSClassfier API, how can I conveniently get inference on additional data?
 Thank u so much!

**Comment by vrodriguezf** [comment]
Here's an example!
https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/14_Inference_Partial_Fit_and_Fine_Tune.ipynb

**Comment by oguiza** [comment]
Closed due to a lack of response
