### ISSUE TITLE
How to split custom data set

### ISSUE THREAD

**Issue by aron-alarik** [timeseriesAI/tsai#550]
I am very new to the TSAI library, just started exploring, its like a swiss army knife for SOTA algos. Amazing work !!

Struggling to get past basic usage, which is splitting my data: 57 independent variables, 1 target column and 100 samples, and firing up the regressor.

A little help on this so that I can move past the basics and explore more advanced features. 

I have posted my code snippet below...Thanks !!

![image](https://user-images.githubusercontent.com/86116123/176846995-7110856a-a087-4d52-b768-a7dbbca04c64.png)

**Comment by ivy113** [comment]
Try this... ? 
```
X_train, X_test, y_train, y_test= split_Xy(X_df, y_df, splits=splits)
X_train.shape, X_test.shape, y_train.shape, y_test.shape
```

I believe this should also work...
```
train_idx, test_idx = splits
X_train = X_df[train_idx]
X_test = X_df[test_idx]
y_train = y_df[train_idx]
y_test = y_df[test_idx]
```
