### ISSUE TITLE
Minirocket cuda out of memory 

### ISSUE THREAD

**Issue by filbert-c** [timeseriesAI/tsai#553]
Hi, in the tutorial nb we could use the pytorch minirocket for any # samples.
My dataset is of size.  10 000 000,2, 32 but i run out of memory even with chunk size =4. Is the memory not being cleared on lazy load?

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/17725170/179660646-5e1b1c91-a336-4e74-b3c7-37e5b98c1451.png">

RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.78 GiB total capacity; 14.56 GiB already allocated; 18.00 MiB free; 14.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by oguiza** [comment]
Hi @filbert-c ,
If you want to use MiniRocket with a larger dataset, I'd recommend you use the Pytorch version. It keeps data on disk, only loads it into memory lazily when it's needed, and features are calculated on the fly.

**Comment by oguiza** [comment]
I'll close this issue due to the lack of response.
