### ISSUE TITLE
using GPU on m1 Pro Mac 

### ISSUE THREAD

**Issue by AsafShul** [timeseriesAI/tsai#556]
hey, first of all thanks for this great repo!

Im using a MacBook with M1 pro chip, 

I have installed PyTorch with the new GPU support, and it seems to be working - 
when running this commands I get True, True
"
    # this ensures that the current MacOS version is at least 12.3+
    print(torch.backends.mps.is_available())
    
    # this ensures that the current current PyTorch installation was built with MPS activated.
    print(torch.backends.mps.is_built())
"

But running the tsai library only utilize the CPU on my machine, 

How can I fix this? thanks

**Comment by oguiza** [comment]
Hi @AsafShul,
I'm afraid I'm unable to help you with this. 
There's no specific `tsai` functionality to support M1 on Mac. So it really depends on Pytorch and fastai support. 
And I don't have any way to test it either.
