### ISSUE TITLE
sorry for my bad English,how to preprocess varying length input data when using TST or other modes ? Thanks !

### ISSUE THREAD

**Issue by psikharpax** [timeseriesAI/tsai#563]
sorry for my bad English,how to preprocess varying length input data when using TST or other modes ? Thanks !

**Comment by vrodriguezf** [comment]
You can apply padding to make all the sequences have the same length, and add timestamp information as additional variables.

**Comment by oguiza** [comment]
I'll close this issue due to a lack of reponse.
