### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'L' (after splitting data into 5 splits.. TFMS gives this error... anyone else faced the same issue?

### ISSUE THREAD

**Issue by ejokhan** [timeseriesAI/tsai#566]
![image](https://user-images.githubusercontent.com/19641451/186495480-763cf083-7e0c-4a50-b171-7da8169df49e.png)
![image](https://user-images.githubusercontent.com/19641451/186495533-925e1cae-4fe9-4cf6-8547-5bb4d172cb7e.png)

**Comment by oguiza** [comment]
Hi @ejokhan ,
If you use n splits, you'll need to use a loop, and use a set of splits in each iteration. Something like this: 
```python
X, y, splits = get_UCR_data('LSST', split_data=False)
for i in splits:
          tfms = [None, TSClassification()]
          batch_tfms= TSStandardize(by_sample=True)
          dls = get_ts_dls(X, y, splits=splits[i], tfms=tfms, batch_tfms=batch_tfms)
          ....
```
