### ISSUE TITLE
Using GPU for models

### ISSUE THREAD

**Issue by R470R** [timeseriesAI/tsai#568]
Hello, do you know some way to put my gpu at work?
I think all packages are well installed, but is running on cpu 

`computer_setup()`
`os             : Linux-5.15.0-46-generic-x86_64-with-glibc2.31
python         : 3.9.12
tsai           : 0.3.1
fastai         : 2.7.9
fastcore       : 1.5.21
torch          : 1.12.1
device         : 1 gpu (['GeForce RTX 3090'])
cpu cores      : 24
RAM            : N/A
GPU memory     : N/A`

**Comment by parshinsh** [comment]
> Hello, do you know some way to put my gpu at work? I think all packages are well installed, but is running on cpu
> 
> `computer_setup()` `os : Linux-5.15.0-46-generic-x86_64-with-glibc2.31 python : 3.9.12 tsai : 0.3.1 fastai : 2.7.9 fastcore : 1.5.21 torch : 1.12.1 device : 1 gpu (['GeForce RTX 3090']) cpu cores : 24 RAM : N/A GPU memory : N/A`

tsai is based on pytorch and fastai so just by using device = torch.device("cuda") you should be able to run models on GPU.

**Comment by oguiza** [comment]
Hi @R470R,
It seems there's some problem with your setup. 
The computer setup function correctly identifies there's a GPU (['GeForce RTX 3090']) but then says GPU memory : N/A. 
This doesn't seem to me that this is related to tsai.
