### ISSUE TITLE
Early stopping should be added to TSClassifier and such functions.

### ISSUE THREAD

**Issue by AslantheAslan** [timeseriesAI/tsai#574]
To reduce the excessive amount of training time, early stopping should be added. For example, we should be able to stop training as soon as we reached a certain score of accuracy or any other metric. It is not possible to interrupt training by fetching the accuracy per epoch now.

I think it will alleviate the memory inefficiency and time consumption for the iterated training loops.

**Comment by vrodriguezf** [comment]
Isn't there an early stopping callback in fastai?

**Comment by AslantheAslan** [comment]
Thanks for the reminder. I have referred to `EarlyStoppingCallbach()` from the `fastai.callbacks.all` and now I am able to utilize that function. However, the thing that I would like to accomplish is to quit training when a certain limit of accuracy has been achieved. Do you have any idea how to do that?

**Comment by vrodriguezf** [comment]
Just changing the [monitor argument](https://docs.fast.ai/callback.tracker.html#earlystoppingcallback) of the EarlyStopping Callback should do it.

**Comment by AslantheAslan** [comment]
Monitor argument only helps me track a particular metric, whereas I need to find a way to terminate training when a particular metric reaches, let's say, %100. So, long story in short, I am looking for an early stopping function that doesn't look for improvement/deterioration but instead looks for a specific score such as %100.

**Comment by vrodriguezf** [comment]
I see...maybe an external tool such as wandb alerts can do the trick.

**Comment by AslantheAslan** [comment]
Again, thank you for the suggestion. I decided not to track a specific level of accuracy. Instead, I'm fetching the early stopping and model saving callbacks of fastai. Since the problem is solved to some extent, I will close this issue. Have a great day and I wish you all the best!
