### ISSUE TITLE
the result between confusion matrix and accurancy is different

### ISSUE THREAD

**Issue by tww0123** [timeseriesAI/tsai#575]
![image](https://user-images.githubusercontent.com/95063969/188322446-84b3dc2f-944c-462b-b6c5-dc8437b15929.png)

**Comment by vrodriguezf** [comment]
Isn't this a fastai issue?

**Comment by tww0123** [comment]
Maybe, but it's strange that the same code can run normally on one computer, and the error shown above does occur on the other computer and colab

**Comment by ejokhan** [comment]
The same thing is happening to me.. the confusion matrix is calculated very wrong not sure why... almost for all models ..

![image](https://user-images.githubusercontent.com/19641451/190066587-dc6e069d-a33c-4617-80c4-6dc4ca68ce16.png)

I am using TSAI latest version.

**Comment by ejokhan** [comment]
> Isn't this a fastai issue?

This is happening in TSAI... the confusion matrix out is totally wrong. Is there any way to fix this?

**Comment by oguiza** [comment]
There was a bug in the code that has already been fixed. If you upgrade `tsai` to the latest version you shouldn't get this issue.
