### ISSUE TITLE
SlidingWindowPanel

### ISSUE THREAD

**Issue by firmai** [timeseriesAI/tsai#577]
Currently only the key `return_key=True` is returned, can the  `sort_by=['date']` also be returned. The benefit, is that the return key and the date is normally combined to form a unique identifier.

**Comment by firmai** [comment]
In essence, I wonder if there is a way to return the sort_by column as well like we can return the key, it would be very helpful.

**Comment by oguiza** [comment]
Hi @firmai,
Sorry for the late reply.
You can actually use multiple columns as unique_id_cols. All of them are used for sorting. In addition to that, you may add other columns to sort by. But the unique ids will be returned if you use `return_key=True`.

**Comment by oguiza** [comment]
Closed due to lack of response.
