### ISSUE TITLE
Suppress progress bar on predict/get_preds

### ISSUE THREAD

**Issue by tim-heuwinkel** [timeseriesAI/tsai#58]
First of all thanks for supplying this useful repository, which enables everyone to work with an implementation of cutting edge timeseries concepts.
I am using a TST model to make live predictions in a bokeh animation displayed in a jupyter notebook. I create the test data for every prediction with a `SlidingWindowPanel`, where the progress bar can be disabled by setting `verbose=False`,  and then get a prediction for the generated test data with get_preds. The get_preds method does not seem to have an option for setting verbosity.
The problem that arises is that even though the progress bar of `get_preds` disappears after it is done, it creates a new blank row each time it is called, leading to an endless and growing white space under the animation.
I tried suppressing the progress bar by redirecting or suppressing std_out, which was without success. I read about a utils function from fastai to suppress all fastprogress bars, but it seems as though this feature was removed in fastai 2.X.

Am i missing an option to set the verbosity of `get_preds` to false? If not, do you have any idea how i could manually suppress the progress bar(s)?

**Comment by oguiza** [comment]
Hi @tim-heuwinkel,
Thanks a lot for your comments!
`get_preds` is fastai functionality, so I can't modify it. 
Having said that, there's an easy way to work around your issue using ContextManagers. Try this:
```
with ContextManagers(learn.no_bar()):
        learn.get_preds()
```
The bar shouldn't be displayed and thus no blank space created.

**Comment by tim-heuwinkel** [comment]
@oguiza works perfectly, thanks!
