### ISSUE TITLE
where is the function init_linear() define?

### ISSUE THREAD

**Issue by Zhangjian55** [timeseriesAI/tsai#580]
The function init_linear() is called call in layers.py Conv2d, but I can't find where it was defined. Could someone help me. Thanks.

**Comment by oguiza** [comment]
Hi @Zhangjian55 ,
If you are using Jupyter and want to know where some function is coming from all you need to do is to write the function or class name in an empty cell and run it. It will return the module it belongs to.

In this case it's `fastai.layers.init_linear`.
