### ISSUE TITLE
New Classification Model/s

### ISSUE THREAD

**Issue by firmai** [timeseriesAI/tsai#581]
This model shows very promising results in regression forecasts, and could easily be turned into a classfication model for this awesome project. https://github.com/cure-lab/ltsf-linear

**Comment by firmai** [comment]
This recent advance in the rocket model that scales down the required number of features https://github.com/lpphd/lightwaves

**Comment by oguiza** [comment]
Hi @firmai ,
It'd be good to add this models if we have capacity to do it. 
Would you be willing to create a PR to add any of them? 
I'd suggest starting with the first one as the models are pretty simple and seem to work very well.

**Comment by oguiza** [comment]
Closed due to lack of response.
