### ISSUE TITLE
Walk forward cross-validation in tsai 

### ISSUE THREAD

**Issue by alitirmizi23** [timeseriesAI/tsai#582]
I was wondering if there are plans to implement walk forward CV in TSAI. #

**Comment by vrodriguezf** [comment]
By default, the function `get_splits` with `n_splits > 0` creates disjunct splits, so ou can use them as folds in a CV process.

**Comment by oguiza** [comment]
Hi @alitirmizi23, cc: @vrodriguezf ,
Thanks for creating this issue.
This is something I've had in mind for quite some time. I've found some time this morning to add this new functionality. You can use it by doing this:
```python
from tsai.data.validation import get_walk_forward_splits
splits = get_walk_forward_splits(
    o, 
    n_splits=4, 
    train_size=.6,
    valid_size=0.1, 
    test_size=0.1, 
    anchored = True,
    gap = 0.,
    test_after_valid = True,
    random_state = None,
    show_plot=True,
)
```
You can find the documentation [here](https://timeseriesai.github.io/tsai/data.validation.html#get_walk_forward_splits).

**Comment by oguiza** [comment]
@alitirmizi23 , if this is what you were looking for, pls feel free to close the issue.

**Comment by alitirmizi23** [comment]
@oguiza amazing, thanks for the feature! Yes, this is what I was looking for. I will close this now.
