### ISSUE TITLE
optuna with TSTplus

### ISSUE THREAD

**Issue by CHonChou** [timeseriesAI/tsai#583]
when i optimize the hyper-paramters of TSTPlus I always get the same error as below
<img width="788" alt="image" src="https://user-images.githubusercontent.com/48724350/192781563-e8aef31b-645c-4267-8f0a-404d583f478a.png">
and my objective function like this
<img width="374" alt="image" src="https://user-images.githubusercontent.com/48724350/192781756-cb91308d-2f39-4136-b08a-a062502c1357.png">

**Comment by MOREDataset** [comment]
Hi,

There is a typo in the hyperparameters you are optimizing: It should be `'d_ff':dff` rather than` 'dff':dff`..
I think using the same names for hyperparameters and values can eliminate this issue in the future.

Not sure if this would solve the error you are getting though!

**Comment by CHonChou** [comment]
thank you for your immediately reply，i've solved this problem.By the way，Is tsai planning to add some traditional time series models like arima ？

**Comment by MOREDataset** [comment]
I usually use tsai for deep learning and [scalecast](https://github.com/mikekeith52/scalecast) for conventional machine learning and statistical models.

**Comment by oguiza** [comment]
> There is a typo in the hyperparameters you are optimizing: It should be 'd_ff':dff rather than 'dff':dff..
I think using the same names for hyperparameters and values can eliminate this issue in the future.

Thanks a lot, @MOREDataset for posting a solution to this issue!!

**Comment by oguiza** [comment]
>thank you for your immediately reply，i've solved this problem.By the way，Is tsai planning to add some traditional time series models like arima ？

@CHonChou,
No there are no plans to add traditional machine learning models or statistical models. tsai is focus on deep learning models. There are other great libraries like sktime that you may find helpful.

Based on previous comments I'll close this issue.
