### ISSUE TITLE
Loading custom model class in ts_learner

### ISSUE THREAD

**Issue by dnth** [timeseriesAI/tsai#59]
Hi! Does anyone know how do I load a custom model into with ts_learner? For example, I have a custom model class as follows:

```
class MySuperCustomModel(Module):
    def __init__(self, c_in, c_out, nf=32, nb_filters=None, **kwargs):
        nf = ifnone(nf, nb_filters) # for compatibility
        self.inceptionblock = InceptionBlock(c_in, nf, **kwargs)
        self.gap = GAP1d(1)
        self.fc = nn.Linear(nf * 4, c_out)

    def forward(self, x):
        x = self.inceptionblock(x)
        x = self.gap(x)
        x = self.fc(x)
        return x.clamp(max=1.0)
```

Can I get MySuperCustomModel to work with ts_learner? 
Below code doesn't work

`learn = ts_learner(dls, MySuperCustomModel, pretrained=True, weights_path=f'data/TSBERT/unsupervised_weights.pth')`

Thanks!

**Comment by oguiza** [comment]
Hi @dnth, 

In order to use TSBERT, you need to create a model with a .head and .head_nf attributes. The way in which I have implemented all models ending in Plus in `tsai` (the ones that can be used with TSBERT) is using a Sequential class. this would be the equivalent for your model:
```
class MySuperCustomModel2(nn.Sequential):
    
    def __init__(self, c_in, c_out, nf=32, **kwargs):
        backbone = InceptionBlock(c_in, nf, **kwargs)
        head = MySuperCustomModelHead(nf, c_out)
        super().__init__(OrderedDict([('backbone', backbone), ('head', head)]))


class MySuperCustomModelHead(Module):
    
    def __init__(self, nf, c_out, **kwargs):
        self.gap = GAP1d(1)
        self.fc = nn.Linear(nf * 4, c_out)
    
    def forward(self, x):
        x = self.gap(x)
        x = self.fc(x)
        return x.clamp(max=1.0)
```
or this:
```
class MySuperCustomModel3(nn.Sequential):
    
    def __init__(self, c_in, c_out, nf=32, min=None, max=None, **kwargs):
        backbone = InceptionBlock(c_in, nf, **kwargs)
        head = nn.Sequential(GAP1d(1), nn.Linear(nf * 4, c_out), Clamp(min=min, max=max))
        super().__init__(OrderedDict([('backbone', backbone), ('head', head)]))


class Clamp(Module):
    
    def __init__(self, min=None, max=None):
        self.min, self.max = min, max
    
    def forward(self, x):
        return x.clamp(min=self.min, max=self.max)
```
I've created a small [gist](https://colab.research.google.com/gist/oguiza/26ff49d380900dcbcef98b4c7357fe36/untitled117.ipynb) to check they both work correctly.
Please, let me know if this resolves your issue.

**Comment by dnth** [comment]
Thank you for your extremely lucid explanation on the matter @oguiza. The gist helped a great deal.
