### ISSUE TITLE
using docments

### ISSUE THREAD

**Issue by deven-gqc** [timeseriesAI/tsai#594]
Hello @oguiza, thank you for this amazing library. I wanted to ask you, are you open to using the `docments` convention for documenting arguments and docstrings?

For example, in `SlidingWindow`
![image](https://user-images.githubusercontent.com/86305049/196707518-9fe94795-e84c-4f8b-a71d-9ff865d3bd1b.png)

I often find myself, looking at the source code to understand the arguments better. I would be happy to create a PR if you are open to this?
![image](https://user-images.githubusercontent.com/86305049/196707941-7d0c233b-7d20-41e2-beac-ec17f50189c1.png)

**Comment by oguiza** [comment]
Hi @deven-gqc,
Thanks for your suggestion. I'm very open to it. 
It'd be great if you submitted a PR for SlidingWindow for example just to agree on a common format before documenting other parts of the library.
We'd also need to agree on which functions or classes we want to document this way, as it would take a considerable amount of time to do it for the entire library.

**Comment by deven-gqc** [comment]
@oguiza I checked the docs again. I saw that a few functions are documented using the docments style. The PR that I've created follows this style of documenting the arguments. 

This style was introduced in `fastcore` a while ago. Here's a reference link. [Link](https://fastcore.fast.ai/docments.html#docments)

![image](https://user-images.githubusercontent.com/86305049/197056856-bd6f4fbe-0675-4c31-be2f-c2f52b5ee393.png)

![image](https://user-images.githubusercontent.com/86305049/197056945-9810fa45-c651-4817-9fd0-616d19d21c6b.png)

**Comment by oguiza** [comment]
Ok, @deven-gqc, I've just merged the PR you have created. Thanks for putting it together.
I have started to document new functions with the docments style. But it'd take a lot of time to time to apply it to most functions. The plan is to document some of the most widely used functions, or those with more questions.
