### ISSUE TITLE
Confusion Matrix changed after running get_X_preds

### ISSUE THREAD

**Issue by raffieeey** [timeseriesAI/tsai#598]
I'm trying to test tsai on a toy dataset

When I run this code:

```
from tsai.all import *

batch_tfms = TSStandardize(by_sample=True)
mv_clf = TSClassifier(x, y_class, path='models', arch=MiniRocketPlus, batch_tfms=batch_tfms, metrics=accuracy, cbs=ShowGraph())
mv_clf.fit_one_cycle(10, 1e-2)
mv_clf.plot_confusion_matrix()

```
I got a confusion matrix that looks like this

![image](https://user-images.githubusercontent.com/32994945/197801133-8290ee48-7e34-493a-b1ab-fc05bdf5e79e.png)

and then I run `get_X_preds` like this:

`
mv_clf.get_X_preds(x.iloc[-128:,:].to_numpy()[:,None])`

and then rerun `mv_clf.plot_confusion_matrix()`

I got this updated confusion matrix. 

![image](https://user-images.githubusercontent.com/32994945/197801851-8932d853-bcb9-413c-a869-a117e0c1e2f2.png)

I'm not sure if this is normal?

**Comment by oguiza** [comment]
Hi @raffieeey,
Thanks for sharing this. 
I've been investigating and it was indeed a bug. 
It should be fixed now. I'd appreciate it if you could confirm it's working well.

**Comment by oguiza** [comment]
Closed due to lack of response.
