### ISSUE TITLE
Difference among TST, TSTPlus and MultiTSTPlus

### ISSUE THREAD

**Issue by jiangye-git** [timeseriesAI/tsai#599]
Hi, when I use the there transfomer models, I wonder what's the diffenrence among the three models. Thanks in advance.

**Comment by oguiza** [comment]
Hi @jiangye-git,
Apologies for my late reply.
The difference is the following:
- TST: is a model that closely matches the original one described in [A Transformer-based Framework for Multivariate Time Series Representation Learning](https://arxiv.org/abs/2010.02803). These are the arguments used in TST:
`TST(
    c_in: int,
    c_out: int,
    seq_len: int,
    max_seq_len: Union[int, NoneType] = None,
    n_layers: int = 3,
    d_model: int = 128,
    n_heads: int = 16,
    d_k: Union[int, NoneType] = None,
    d_v: Union[int, NoneType] = None,
    d_ff: int = 256,
    dropout: float = 0.1,
    act: str = 'gelu',
    fc_dropout: float = 0.0,
    y_range: Union[tuple, NoneType] = None
)`
- TSTPlus: like all models ending in Plus add some additional arguments not available in the original version. This is for advanced users who want to better adjust the model. These are the arguments:
`TSTPlus(
    c_in: int,
    c_out: int,
    seq_len: int,
    max_seq_len: Union[int, NoneType] = 512,
    n_layers: int = 3,
    d_model: int = 128,
    n_heads: int = 16,
    d_k: Union[int, NoneType] = None,
    d_v: Union[int, NoneType] = None,
    d_ff: int = 256,
    norm: str = 'BatchNorm',
    attn_dropout: float = 0.0,
    dropout: float = 0.0,
    act: str = 'gelu',
    key_padding_mask: bool = 'auto',
    padding_var: Union[int, NoneType] = None,
    attn_mask: Union[torch.Tensor, NoneType] = None,
    res_attention: bool = True,
    pre_norm: bool = False,
    store_attn: bool = False,
    pe: str = 'zeros',
    learn_pe: bool = True,
    flatten: bool = True,
    fc_dropout: float = 0.0,
    concat_pool: bool = False,
    bn: bool = False,
    custom_head: Union[Callable, NoneType] = None,
    y_range: Union[tuple, NoneType] = None,
    verbose: bool = False
)`
- MultiTSTPlus is a transformer that takes different types of inputs and processes them in separate branches. These branches are then merged to generate a single output. This is useful when you have features in different time scales.

**Comment by jiangye-git** [comment]
Really really really thank you for your reply!!!!
