### ISSUE TITLE
Segmentation with tsai

### ISSUE THREAD

**Issue by carbocation** [timeseriesAI/tsai#60]
Is there a concept of segmentation in `tsai`? E.g., I have a time series and for every single point, one label applies. This is a 1-dimensional equivalent of semantic segmentation. And I'd like to train a model to perform this same task. I didn't see an obvious candidate with `tsai` but am curious if there is an example that seems to fit.

**Comment by vrodriguezf** [comment]
Not that I am aware of. Something like U-net for time series was proposed at NeurIPS a copule of years ago:
https://arxiv.org/abs/1910.11162

**Comment by carbocation** [comment]
Thanks for the pointer. It looks like there is an [implementation in PyTorch](https://github.com/perslev/U-Time). I'll have to dig into this.

**Comment by oguiza** [comment]
Since this is more a (very interesting) question than an issue, I'll move it to discussions.
