### ISSUE TITLE
Time interval importance with tsai

### ISSUE THREAD

**Issue by saeidehdavoudi** [timeseriesAI/tsai#604]
Hello, I am wondering if this library has any function to specify which time points play key role in classification? I have a task and it is important for me to see which time intervals make significant discrimination.

**Comment by oguiza** [comment]
Hi @saeidehdavoudi , 
Yes, there's functionality to analyze step importance. You can learn more about it here: [step_importance](https://timeseriesai.github.io/tsai/analysis.html#learner.step_importance)

**Comment by oguiza** [comment]
Closed due to lack of response.
