### ISSUE TITLE
with_decoded=True giving wrong predictions in get_X_preds()

### ISSUE THREAD

**Issue by lwachowiak** [timeseriesAI/tsai#605]
The automated decoding functionality in get_X_preds does not work reliably for me. Sometimes it decodes the probabilities in a way that the decoding for an individual sample is an array with 3 labels instead of a single label. With some datasets it works correctly with others it gives multiple labels. See this screenshot:
![image](https://user-images.githubusercontent.com/71786387/198829427-aca2ffc2-ed5f-4320-9a89-059b457bbc16.png)

The workaround is simple as you can just decode the probabilities yourself as in the screenshot; but it is still a weird bug. 

My setup:
![image](https://user-images.githubusercontent.com/71786387/198829477-01b023f1-9ca6-490b-99f8-5d3dcf0caec1.png)

**Comment by oguiza** [comment]
Hi @lwachowiak,
Thanks for sharing this. It's a bit difficult to debug it if I don't understand what's the input and expected output.
Could you please share a code snippet to reproduce the issue?
