### ISSUE TITLE
Beginner -- There is no picture in the running result

### ISSUE THREAD

**Issue by bubu-li** [timeseriesAI/tsai#620]
from tsai.all import *

dsid = 'AppliancesEnergy' 
X, y, splits = get_regression_data(dsid, split_data=False)
tfms  = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_sample=True, by_var=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=32)
dls.show_batch()
learn = ts_learner(dls, InceptionTime, metrics=[mae, rmse], cbs=ShowGraph())
learn.lr_find()

When I run the above code locally, the expected picture of **Loss-Learning Rate** does not appear.( dls.show_batch() did not appear the picture)
No errors but no pictures. 
![image](https://user-images.githubusercontent.com/74704803/201099426-fc7a4e3e-76b0-4df2-916b-2ce21c5b86fd.png)

**Comment by oguiza** [comment]
Hi @bubu-li ,
I've just run your code snippet locally and everything works fine. 
What version of tsai are you using? (You can use `my_setup()` and paste the output here).
Could you also let me know how did you install tsai?

**Comment by bubu-li** [comment]
I run it with python.
I know what's going on. I need to add these two statements to run with python.

from tsai.all import *
**import matplotlib.pyplot as plt**

dsid = 'AppliancesEnergy' 
X, y, splits = get_regression_data(dsid, split_data=False)

tfms  = [None, [TSRegression()]]
batch_tfms = TSStandardize(by_sample=True, by_var=True)
dls = get_ts_dls(X, y, splits=splits, tfms=tfms, batch_tfms=batch_tfms, bs=32)
dls.one_batch()
#dls.show_batch(sharey=True)
#plt.show()

learn = ts_learner(dls, InceptionTime, metrics=[mae, rmse], cbs=ShowGraph(plot_metrics=True, final_losses=True))
learn.lr_find()
**plt.show()**

**Comment by oguiza** [comment]
Closed due to lack of response.
