### ISSUE TITLE
Missing requirements.txt or other dependency list?

### ISSUE THREAD

**Issue by pjnr1** [timeseriesAI/tsai#63]
I'm in the process of setting up a repo and training bench on a HPC, when only tsai is added to my requirements.txt, I get errors when importing.

First off, IPython is missing -> I manually added that to the installation. Re-ran, and then sktime is missing.

It seems that dependency management of `tsai` is missing, or at least bugging for me.

Can you re-produce?

**Comment by pjnr1** [comment]
Nevermind, I can't reproduce it again. Might have been a issue with my $PATH ...

**Comment by oguiza** [comment]
HI @pjnr1, 
I built tsai using nbdev. Dependencies are included in the settings.ini file.

**Comment by williamsdoug** [comment]
Here's the script that I use to build my tsai environment using conda:

conda create --name tsai pytorch=1.7.0 cudatoolkit=10.2 fastai=2.2.5
nb_conda python=3.8 -c fastai -c pytorch
conda activate tsai
pip install tsai

Adjust cudatoolkit version based on your nvidia software.  Also adjust to
reflect your preferred python version (3.7.6 and 3.8 work for me)

If using jupyter notebooks, make sure to update the kernel to use the tsai
environment

**Comment by oguiza** [comment]
Thank you  @williamsdoug!!

**Comment by pjnr1** [comment]
Hi both,

Thanks! That is very helpful @williamsdoug, and thanks for a great package @oguiza.
