### ISSUE TITLE
RevIN method in TSAI

### ISSUE THREAD

**Issue by gitusrnm** [timeseriesAI/tsai#637]
Hi @oguiza, any chance of having RevIN in TSAI anytime soon? Thanks!!!
[https://github.com/ts-kim/RevIN](https://github.com/ts-kim/RevIN)

**Comment by oguiza** [comment]
Thanks for raising this @gitusrnm . I hadn't seen the paper before. It looks pretty straightforward, and seems to improve forecasting performance significantly. I'll certainly add a RevIN layer to `tsai` soon. 
I'll test it in some of the models in the library to see how it could be integrated.

**Comment by oguiza** [comment]
The RevIN layer has already been added to `tsai`. It's already available if you install it from GitHub. Otherwise, it'll be available in the next pip release.
