### ISSUE TITLE
PatchTST model in TSAI

### ISSUE THREAD

**Issue by gitusrnm** [timeseriesAI/tsai#638]
Hi @oguiza, any chance of having the PatchTST model in TSAI anytime soon? Thanks!!!
[https://github.com/yuqinie98/PatchTST](https://github.com/yuqinie98/PatchTST)

**Comment by oguiza** [comment]
Thanks @gitusrnm ,
Yes, this is a paper I'd recently seen. I think it's a very interesting approach. It shouldn't be too difficult to integrate since they used `tsai` as a base code to build the library.

**Comment by oguiza** [comment]
PatchTST has been added to `tsai`. It's available if you install `tsai` from GitHub, and will be available in the next pip release.
I'm preparing a tutorial that will be release within a few weeks.
