### ISSUE TITLE
df2xy multivariate sort order?

### ISSUE THREAD

**Issue by carbocation** [timeseriesAI/tsai#64]
I'm using `df2xy` to convert a pandas dataframe with multivariate input to data that is appropriate for `tsai`. 

The data are structured such that the 8 features in `feat_col` should all behave fairly consistently from sample to sample. E.g., I expect that when I plot feature 1 from two different samples, they will look similarly. For example, X[0][1] and X[1][1], like so:
![image](https://user-images.githubusercontent.com/218804/108539699-545a1d80-72ae-11eb-9e4e-5a8d8dad1bcd.png)

However, once I run the data through `df2xy`, this pattern no longer seems true: for each sample, the channel 1 seems to receive the `feat_col` randomly. As I march down to X[4][1] and X[5][1] I see what appear to be data that originated in different channels (which behave inversely from one another, as expected) but are both assigned to channel X[...][1]:
![image](https://user-images.githubusercontent.com/218804/108539633-41dfe400-72ae-11eb-902a-2bcfad88ae07.png)

Knowing my data, the most parsimonious interpretation seems to be that the `feat_col` categories are not being inserted into the same channel, but instead seem to be inserted in a random order.

Glancing at the [df2xy](https://github.com/timeseriesAI/tsai/blob/75f81e4ab1bda5c6618028b0e96a59e2a9dedd6b/tsai/data/preparation.py#L12), I actually don't see anything that enforces a sort order for the channels - but I may be missing this, so I wanted to double check. If that is the case, do we basically need to ensure that our input data frame is sorted consistently along the `feat_col` axis prior to running `df2xy`?

**Comment by oguiza** [comment]
That's strange. I've tried some simple code and it seems to work well:
```
data = np.tile(np.arange(6), 12).reshape(12, 6)
df = pd.DataFrame(data, columns=['key'] + np.arange(4).astype(str).tolist()+['target'])
df.iloc[4:8, 0] = 1
df.iloc[8:, 0] = 2
df2xy(df, feat_col='key', target_col='target', data_cols=['3', '1'])
```
output:
```
(array([[[4, 2],
         [4, 2],
         [4, 2]],
 
        [[4, 2],
         [4, 2],
         [4, 2]],
 
        [[4, 2],
         [4, 2],
         [4, 2]],
 
        [[4, 2],
         [4, 2],
         [4, 2]]]), array([5, 5, 5, 5]))
```
So the features (or channels) are taken in the order you pass them. Isn't this what you would expect?

**Comment by carbocation** [comment]
I am probably just grossly misunderstanding the function. Here is a toy example:

```py
import numpy as np
import pandas as pd
from io import StringIO

from tsai.all import *

TESTDATA = StringIO("""sample_id;trait;value_0;target
    rob;green;2;hot
    rob;yellow;3;hot
    rob;blue;4;hot
    rob;red;5;hot
    alice;green;6;lukewarm
    alice;yellow;7;lukewarm
    alice;blue;8;lukewarm
    alice;red;9;lukewarm
    eve;yellow;11;cold
    eve;green;10;cold
    eve;blue;12;cold
    eve;red;13;cold
    """)

df = pd.read_csv(TESTDATA, sep=";")

x, y = df2xy(df, feat_col = 'trait', target_col = 'target', data_cols=['value_0'])
```

Output:
```
array([[[ 2],
        [ 5],
        [ 8],
        [10]],

       [[ 3],
        [ 6],
        [ 9],
        [12]],

       [[ 4],
        [ 7],
        [11],
        [13]]])
```

The output I actually expected was:
```
array([[[ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13]]])
```

So, probably a mismatch between my expectations and what it's actually doing.

**Comment by carbocation** [comment]
For my purposes, I think I was looking for something more like the following (which seems to work fine for me):

```py
def id_df2xy(dat, id_col=None, feat_col=None, target_col=None, data_cols=None):
    
    df = dat.sort_values([id_col, feat_col], inplace=False)
    
    x = df[id_col].factorize()[0]
    y = df.groupby(x).cumcount().values

    vals = df.loc[:, data_cols].values
    
    out_shp = (x.max()+1, y.max()+1, vals.shape[1])
    
    out = np.full(out_shp, np.nan)
    out[x,y] = vals
    
    return out, np.array(df[[id_col, target_col]].drop_duplicates()[target_col])
```

Called like:
```py
train_xy = id_df2xy(i2, id_col = 'sample_id', feat_col = 'trait', target_col='value', data_cols=value_cols)
```

**Comment by oguiza** [comment]
You were right. There were issues with the function as designed. 
I've updated it and I think it works as expected. Caould you please try it: 
```
def df2xy(df, sample_col=[], feat_col=[], target_col=[], data_cols=[], to3d=True, splits=None, sort=False):
    r"""
    This function allows you to transform a pandas dataframe into X and y numpy arrays that can be used to craete a TSDataset.
    sample_col: column that uniquely identifies each sample
    feat_col: used for multivariate datasets. It indicates which is the column that indicates the feature by row.
    target_col: indicates the column/s where the target is.
    data_col: indicates where the data is located. If None, it means all columns (excpet the target)
    sort: indicates whether the df needs to be sorted or not. If sorted, it will use sample col first, and feat_col second.
    """
    if sample_col and not is_listy(sample_col): sample_col = [sample_col]
    if feat_col and not is_listy(feat_col): feat_col = [feat_col]
    if target_col and not is_listy(target_col): target_col = [target_col]
    if data_cols and not is_listy(data_cols): data_cols = [data_cols]
    if not data_cols: 
        no_data_cols = []
        if sample_col: no_data_cols.append(sample_col)
        if feat_col: no_data_cols.append(feat_col)
        if target_col: no_data_cols.append(target_col)
        data_cols = [col for col in df.columns if col not in no_data_cols]
    n_samples = len(np.unique(df[sample_col].values)) if sample_col else 1
    n_feats = len(np.unique(df[feat_col].values)) if feat_col else 1
    if sort:
        df = df.sort_values(sample_col + feat_col)
    data = df.loc[:, data_cols].values
    _, seq_len = data.shape
    if to3d: X = data.reshape(n_samples, n_feats, -1)
    else:
        assert feat_col is None, 'When feat_col is not None you must set to3d=True'
        X = data
    if X.dtype == 'O': X = X.astype(np.float32)
    if target_col is not None: y = np.split(df[target_col].values, n_feats)[0]
    else: y = None
    if splits is None: return X, y
    else: return split_xy(X, y, splits)

```

**Comment by carbocation** [comment]
This function does not yield the expected response. Namely, it does not correct for the fact that for the third sample (eve), green and yellow need to be swapped in terms of their order in order to maintain their semantic meaning. (That is, for every other individual, green is the 0th layer, but for eve, green is being inserted as the 1st layer.)

**Comment by carbocation** [comment]
(One solution might just be to explicitly say that the input needs to be pre-sorted in a certain order.)

**Comment by oguiza** [comment]
Hi James,
I've updated the df2xy function to cover some more use cases (see [gist](https://gist.github.com/oguiza/170bb9afad59d6fa41f3c652317a8595)). I think it works as expected (it returns the result you indicated before, that I agree it's the right one). 
However, it's impossible to cover all cases, so I agree with you that if you want to use a more complex sorting, you'll need to pass a pre-sorted dataframe.

**Comment by oguiza** [comment]
I will close this issue due to a lack of activity. I believe it is fixed. If it reappears, please, feel free to reopen it.
