### ISSUE TITLE
Links in the online documentation website are broken

### ISSUE THREAD

**Issue by yangtzech** [timeseriesAI/tsai#641]
Links in the online documentation website are broken. They cannot be clicked. It seems to be caused by the `renumbered nbs` commit https://github.com/timeseriesAI/tsai/commit/25abd5b0917abe540869050f03334f567ef7d5bb, where `013_data.core.ipynb` is renamed to `006_data.core.ipynb`.

![image](https://user-images.githubusercontent.com/41911522/206849084-b3edeb1c-a255-4ebc-b412-96ca0f7a27ae.png)

**Comment by oguiza** [comment]
Thanks @yangtzech for bringing this up. I reorganized the nbs yesterday and forgot to update the sidebar.yml.

**Comment by yangtzech** [comment]
You are welcome!
