### ISSUE TITLE
how to use multivariate variables forcast using transformer model

### ISSUE THREAD

**Issue by rk0033** [timeseriesAI/tsai#643]
Hello.
Please tell me about the tsai model with multivariate variables.

I am trying to create a time series model with multivariate variables using transformer model of tsai.
In the Forecasting section of the document below, it says "univariate or multivariate time series input," but I can only find examples of univariate forcast and not multivariate forcast.
https://timeseriesai.github.io/tsai/#forecasting
When I trained a model with multivariate variables and performed inference, the result was unnatural oscillation.

Please tell me an example of multivariate forcast description?
Or should I use the following Multivariate Regression instead of Forcasting?
https://timeseriesai.github.io/tsai/#multivariate-regression

**Comment by oguiza** [comment]
Hi @rk0033, 
I don't have any examples I can share with you right now. 
But I'm preparing several time series forecasting tutorials to demonstrate how to use tsai in many common scenarios. I'll share them over the next few weeks.

**Comment by oguiza** [comment]
Hi @rk0033,
I've recently released a new tutorial notebook that focuses on long-term, multivariate time series forecasting: https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/15_PatchTST_a_new_transformer_for_LTSF.ipynb
It uses a new, state-of-the-art transformer architecture called PatchTST. 
I hope you'll find it useful.

**Comment by oguiza** [comment]
Closed due to lack of response.

**Comment by rk0033** [comment]
@oguiza 
Sorry for late reply.
Thank you.
I will let you use it.
