### ISSUE TITLE
How Does the pv() Logging Work?

### ISSUE THREAD

**Issue by xanderdunn** [timeseriesAI/tsai#65]
I see the code is peppered with `pv()` logging statements, but when I'm running the code I don't see anything printed to the console. Can you point me to where `pv` is defined or some docs on how it works? 

I'm not familiar with fastai and haven't been able to find where `pv` is imported from.

**Comment by oguiza** [comment]
Hi @xanderdunn,
pv(‘a’, verbose) is equivalent to if verbose: print(‘a’). So it’s enabled setting verbose to True.

**Comment by xanderdunn** [comment]
Oh, this isn't a global logger. There is no global location I can set `verbose=True`? It looks like I need to pass `verbose=True` to every function call that supports it.

**Comment by xanderdunn** [comment]
As an example, passing `get_UCR_data(dsid, return_split=False, verbose=True)` works. Thanks.
