### ISSUE TITLE
TSDataset(x,y=None).vars property fails

### ISSUE THREAD

**Issue by williamsdoug** [timeseriesAI/tsai#66]
vars property incorrectly handles situation where y value is omitted. 

**Reproducer notebook:**
https://gist.github.com/williamsdoug/cb44ef5b1326ab4a9c679396b6fc3db8

- Error reproduced in cell: 17, 18
- Patch shown in cell: 21

**Analysis:**
When y is present, ds[0] returns tuple containing X[0],y[0], however when y=None, ds[0] returns only X[0].  Current vars property uses incorrect dimensions for latter case.

**Proposed fix:**

    @property
    def vars(self):
        if self.y is None:
            if self[0].ndim >=4: return self[0].shape[-3]
                return self[0].shape[-2]
            else:
                if self[0][0].ndim >=4: return self[0][0].shape[-3]
                return self[0][0].shape[-2]

**Sample Error Code:**

a = np.random.rand(5,6,7)
ds = TSDataset(a)
test_eq(ds.c, 0)
test_eq(ds.vars, 6)
test_eq(ds.len, 7)

**Sample error message:**

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-17-1602540782bc> in <module>
      2 ds = TSDataset(a)
      3 test_eq(ds.c, 0)
----> 4 test_eq(ds.vars, 6)
      5 test_eq(ds.len, 7)

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/tsai/data/core.py in vars(self)
    146     def vars(self):
    147         if self[0][0].ndim >=4: return self[0][0].shape[-3]
--> 148         return self[0][0].shape[-2]
    149     @property
    150     def len(self): return self[0][0].shape[-1]

IndexError: tuple index out of range

**Comment by oguiza** [comment]
Hi @williamsdoug,
For some reason, I've been unable to open the gits you sent to me. However, I've updated the code, and I think the issue is fixed now. It'd be great if you would confirm it. Thanks.

**Comment by williamsdoug** [comment]
I'll retest once I complete a regression test of the tutorial noticebooks.

Also, I noticed that GitHub sometimes has difficulties rendering Gists
containing larger Juypter notebooks.  Below are pointers to the Gist
notebooks rendered externally using nbviewer:

Failing notebook:

https://nbviewer.jupyter.org/urls/gist.github.com/williamsdoug/50ee2377b638680c894eb811003c5599/raw/aa35626e2ffb05378a5bd7f6eb8cbd7cb760403c/TSDatset_y_fragility.ipynb


Work-around (patches TSDatasets):

https://nbviewer.jupyter.org/urls/gist.githubusercontent.com/williamsdoug/50ee2377b638680c894eb811003c5599/raw/aa35626e2ffb05378a5bd7f6eb8cbd7cb760403c/TSDataset_y_Patched.ipynb

**Comment by williamsdoug** [comment]
Fixed using 0.2.16.  Attached is verification code.

[TSDataset_Verify_Error_Fix.zip](https://github.com/timeseriesAI/tsai/files/6118229/TSDataset_Verify_Error_Fix.zip)
