### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by rskumar** [timeseriesAI/tsai#662]
https://github.com/timeseriesAI/tsai/blob/8b112284dcae73505f856963ee77ae7e39094452/tsai/data/core.py#L330

`lts` would be undefined if `else` executed at line 326
https://github.com/timeseriesAI/tsai/blob/8b112284dcae73505f856963ee77ae7e39094452/tsai/data/core.py#L326

Therefore it may throws error in such scenario.

**Comment by oguiza** [comment]
Hi @rskumar,
Thanks for bringing this up. It was indeed an issue. I've already fixed it.
