### ISSUE TITLE
Df2xy causing incorrect splits 

### ISSUE THREAD

**Issue by Zwayeh** [timeseriesAI/tsai#666]
Unsure if this is an issue with my code/understanding, or a bug with the df2xy function. When attempting to generate splits for multivariant data, I am finding the data being split by feature instead of sample; this of course causes incorrect training / testing.

To test, I have imported the NATOPS UCR dataset and shown the splits generated below: 

![Original Splits](https://user-images.githubusercontent.com/33404330/215333017-18dd67d0-861c-49c5-82f8-b9409869f8b8.png)

I have then converted this dataset to a pandas df, and converted it back to X, y by utilising the df2xy function:

![df2xy splits](https://user-images.githubusercontent.com/33404330/215333056-82433fa4-a05c-45f8-ac84-af3f3e5b9571.png)

As you can see, the splits change from correctly being split by sample, to being split by feature. Any help would be greatly appreciated :)

**Comment by oguiza** [comment]
Hi @Zwayeh,
I've investigated this issue you mention, and found a bug in the code. It's related to a pandas sorting issue I wasn't aware of. 
You can replicate the pandas issue with this code if interested: 
```python
df=pd.DataFrame(np.repeat(np.arange(5), 4), columns=["values"])
df["values2"] = df["values"]
df['rank'] = np.arange(len(df))
df.sort_values(['values'])
```
When sorting by a single column, you may get this strange behavior. To avoid that you need to pass kind='stable':
```python
df.sort_values(['values'], kind='stable')
```

You can now confirm the code works by doing this: 
```python
X, y, _ = get_UCR_data('NATOPS', split_data=False)
splits = get_splits(y, valid_size=.2, stratify=.2, random_state=34, shuffle=True)
df = pd.DataFrame(X.swapaxes(0,1).reshape(X.shape[1], -1).T)
df['target'] = np.repeat(y, X.shape[-1])
df['sample_id'] = np.repeat(np.arange(len(X)), X.shape[-1])
test_eq(X, X_df)
test_eq(y, y_df)
```

**Comment by oguiza** [comment]
Closed due to a lack of response.
