### ISSUE TITLE
font_size and title_size in confusion matrix

### ISSUE THREAD

**Issue by georgemossad** [timeseriesAI/tsai#674]
hey there,
when I try to increase the fontsize in arguments of the confusion using the below code as in the documentation:
interp.plot_confusion_matrix(fontsize=15)
I get this error:
AttributeError: 'Figure' object has no property 'fontsize'
also the same happens for title size.

**Comment by oguiza** [comment]
Hi @georgemossad,
I'm not sure where you've seen that in the documentation. You should use: 
```python
learn.plot_confusion_matrix(title_fontzise=18, fontsize=12)
```
like it appears in tsai's [doc](https://timeseriesai.github.io/tsai/analysis.html#learner.plot_confusion_matrix).

**Comment by oguiza** [comment]
Closed due to the lack of response.
