### ISSUE TITLE
MiniRocket incompatible with latest scikit-learn version

### ISSUE THREAD

**Issue by isears** [timeseriesAI/tsai#677]
FYI when I installed tsai into an environment with scikit-learn v1.2.1 and tried to use MINIROCKET, I got the following error:

```
Traceback (most recent call last):
  File "xxx", line 11, in <module>
    model = MiniRocketRegressor()
  File "xxx/python3.10/site-packages/tsai/models/MINIROCKET.py", line 87, in __init__
    ('ridgecv', RidgeCV(alphas=alphas, normalize=normalize_features, scoring=scoring, **kwargs))]
TypeError: _BaseRidgeCV.__init__() got an unexpected keyword argument 'normalize'
```

It looks like the `normalize` keyword in `RidgeCV` was removed in scikit-learn v1.2.1

If anyone else is having this problem, downgrading sklearn to v1.1.3 appears to fix the issue for now. That is assuming nothing else in your environment depends on the latest version.
```
pip install scikit-learn==1.1.3
```

**Comment by oguiza** [comment]
Hi @isears,
Thanks for raising this issue. I'll work on it as soon as I can.
