### ISSUE TITLE
how to preds when using the TS-to-ImageClassification model?

### ISSUE THREAD

**Issue by jiangtaochen** [timeseriesAI/tsai#681]
I was following the tutorial to convert time-series as Images. and the training process is over ;but i have some problem when I using the model to preds the ublabeled test dataset ?what should I to input in the function `learn.get_X_preds(X_test)`?what is the typr of  "X_test"? ndarray or TSImage?。
here is my code :+1: 
training:

```
batch_tfms =[TSNormalize(),TSToGADF()]
dls = TSDataLoaders.from_dsets(dsets.train,dsets.valid,bs = [64,128],batch_tfms = batch_tfms,num_workers=0)
model = create_model(xresnet18,dls=dls)
learn = Learner(dls, model,metrics=accuracy)  #
learn.fit_one_cycle(100, lr_max=2e-5)
learn.export(pkl_name)
```

inference:

```
learn = load_learner(model_name)
out= TSToGADF()(TSTensor(X_test),split_idx = 0)
test_probas1, test_targets1, test_preds1 = learn.get_X_preds(out)
```

when I input the TSImage ,some error occurs:
![image](https://user-images.githubusercontent.com/72733459/221813071-d47e0d7c-d012-4b13-b564-b9cd5b841ff5.png)

but when I input array ,it works ,but the accuracy is very low,and  all the inference results are all the same,it seems not the right way.
so what is the typr of  "X_test"? ndarray or TSImage?。

**Comment by oguiza** [comment]
Hi @jiangtaochen,
The input to generate predictions is the same as the input to the dataloaders you used in training: numpy arrays. 
The learner stores the batch_transforms, so it knows what needs to be applied.

**Comment by oguiza** [comment]
Closed due to lack of response.
