### ISSUE TITLE
Mixed augmentations on my time series batch

### ISSUE THREAD

**Issue by Willtl** [timeseriesAI/tsai#683]
Is there a way that I can use mixed augmentations on my batch, as in the code below?
```
    for epoch in range(1, EPOCHS + 1):
        for i, batch in enumerate(train_dl):
            series, targets = batch
            if torch.cuda.is_available():
                series = series.cuda(non_blocking=True)
                targets = targets.cuda(non_blocking=True)

            # Apply CutMix1d on my batch
            series, targets = CutMix1d(series, targets)
            
            # Feedfoward, backward, and adjust model
            output = model(series,targets)
            loss = ...
            step ...           
```

**Comment by oguiza** [comment]
Hi @Willtl, 
I'm not sure I understand what you want to do?
CutMix1d is available as a callback in tsai. You can pass it to any Learner (tslearner, TSClassifier, etc). You just need to add cbs=CutMix1d().
The callback will apply CutMix to every batch during training.
Does this answer your question?

**Comment by oguiza** [comment]
Ok, I understand. 
You’ll need to look into the CutMix1d [code](https://github.com/timeseriesAI/tsai/blob/54f04db2e965ee51224b2bd232ad7985ae6faa40/tsai/data/mixed_augmentation.py#L61), extract what you need and adapt it to your code.
