### ISSUE TITLE
Useability: TSDataset breaks if categorical data not in numpy array

### ISSUE THREAD

**Issue by williamsdoug** [timeseriesAI/tsai#69]
Took me about a half day to debug this issue, so passing along in case others encounter similar issue ... While Categorical/Multi-Categorical data is often a list of strings, unless the data is reformatted as numpy array, calls to TSDatasets fails with a somewhat cryptic error.  Problem occurs if y data is of type list or L().

Included is a monkey patch to work around this issue, however a modifying TSDatasets.__init__ to include type conversion would be a cleaner solution. 

Gist showing error and work-around: https://gist.github.com/williamsdoug/50ee2377b638680c894eb811003c5599

*Monkey Patch:*

    old_init = TSDatasets.__init__
    def patched_init(self, *args, **kwargs):
        print('patched_init', len(args), list(kwargs.keys()))
    
        if len(args) >= 2:
            y = args[1]
        elif 'y' in kwargs:
            y = kwargs['y']
        else:
            return old_init(self, *args, **kwargs)
        
        if y is not None and 'numpy' not in str(type(y)):
            y = np.array(y)
    
            if len(args) == 2:
                return old_init(self, args[0], y, **kwargs)
            elif len(args) >= 2:
                return old_init(self, args[0], y, **args[2:], **kwargs)
            elif 'y' in kwargs:
                kwargs['y'] = y
        
        return old_init(self, *args, **kwargs)
    
    TSDatasets.__init__ = patched_init

**Sample code producing errpr:**
dsid = 'NATOPS' 
bs = 64
X, y, splits = get_UCR_data(dsid, return_split=False)
y = [str(z) for z in y]
vocab = sorted(set(y))
print(X.shape)
print(type(y), type(y[0]))
print(vocab)

tfms  = [None, [Categorize(vocab=vocab)]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits)
dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=[bs, bs*2])

**Sample Error Message:**

IndexError                                Traceback (most recent call last)
<ipython-input-6-3f582002cc5b> in <module>
      1 tfms  = [None, [Categorize(vocab=vocab)]]
----> 2 dsets = TSDatasets(X, y, tfms=tfms, splits=splits)
      3 dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=[bs, bs*2])

/media/big_ssd/doug/Documents/GitHub/tsai/tutorial_nbs/tsai/data/core.py in __init__(self, X, y, items, sel_vars, sel_steps, tfms, tls, n_inp, dl_type, inplace, **kwargs)
    263         self.sel_vars = ifnone(sel_vars, slice(None))
    264         self.sel_steps = ifnone(sel_steps,slice(None))
--> 265         self.tls = L(tls if tls else [TfmdLists(item, t, **kwargs) for item,t in zip(items,self.tfms)])
    266         self.n_inp = (1 if len(self.tls)==1 else len(self.tls)-1) if n_inp is None else n_inp
    267         if 'split' in kwargs: self.split_idxs = kwargs['split']

/media/big_ssd/doug/Documents/GitHub/tsai/tutorial_nbs/tsai/data/core.py in <listcomp>(.0)
    263         self.sel_vars = ifnone(sel_vars, slice(None))
    264         self.sel_steps = ifnone(sel_steps,slice(None))
--> 265         self.tls = L(tls if tls else [TfmdLists(item, t, **kwargs) for item,t in zip(items,self.tfms)])
    266         self.n_inp = (1 if len(self.tls)==1 else len(self.tls)-1) if n_inp is None else n_inp
    267         if 'split' in kwargs: self.split_idxs = kwargs['split']

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/foundation.py in __call__(cls, x, *args, **kwargs)
     95     def __call__(cls, x=None, *args, **kwargs):
     96         if not args and not kwargs and x is not None and isinstance(x,cls): return x
---> 97         return super().__call__(x, *args, **kwargs)
     98 
     99 # Cell

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/data/core.py in __init__(self, items, tfms, use_list, do_setup, split_idx, train_setup, splits, types, verbose, dl_type)
    234         if do_setup:
    235             pv(f"Setting up {self.tfms}", verbose)
--> 236             self.setup(train_setup=train_setup)
    237 
    238     def _new(self, items, split_idx=None, **kwargs):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/data/core.py in setup(self, train_setup)
    250 
    251     def setup(self, train_setup=True):
--> 252         self.tfms.setup(self, train_setup)
    253         if len(self) != 0:
    254             x = super().__getitem__(0) if self.splits is None else super().__getitem__(self.splits[0])[0]

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in setup(self, items, train_setup)
    190         tfms = self.fs[:]
    191         self.fs.clear()
--> 192         for t in tfms: self.add(t,items, train_setup)
    193 
    194     def add(self,t, items=None, train_setup=False):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in add(self, t, items, train_setup)
    193 
    194     def add(self,t, items=None, train_setup=False):
--> 195         t.setup(items, train_setup)
    196         self.fs.append(t)
    197 

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/transform.py in setup(self, items, train_setup)
     77     def setup(self, items=None, train_setup=False):
     78         train_setup = train_setup if self.train_setup is None else self.train_setup
---> 79         return self.setups(getattr(items, 'train', items) if train_setup else items)
     80 
     81     def _call(self, fn, x, split_idx=None, **kwargs):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/data/core.py in <lambda>(i, x)
    217         return self._dbunch_type(*dls, path=path, device=device)
    218 
--> 219 FilteredBase.train,FilteredBase.valid = add_props(lambda i,x: x.subset(i))
    220 
    221 # Cell

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/data/core.py in subset(self, i)
    239         split_idx = ifnone(split_idx,self.split_idx)
    240         return super()._new(items, tfms=self.tfms, do_setup=False, types=self.types, split_idx=split_idx, **kwargs)
--> 241     def subset(self, i): return self._new(self._get(self.splits[i]), split_idx=i)
    242     def _after_item(self, o): return self.tfms(o)
    243     def __repr__(self): return f"{self.__class__.__name__}: {self.items}\ntfms - {self.tfms.fs}"

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/foundation.py in _get(self, i)
    117         return (self.items.iloc[list(i)] if hasattr(self.items,'iloc')
    118                 else self.items.__array__()[(i,)] if hasattr(self.items,'__array__')
--> 119                 else [self.items[i_] for i_ in i])
    120 
    121     def __setitem__(self, idx, o):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastcore/foundation.py in <listcomp>(.0)
    117         return (self.items.iloc[list(i)] if hasattr(self.items,'iloc')
    118                 else self.items.__array__()[(i,)] if hasattr(self.items,'__array__')
--> 119                 else [self.items[i_] for i_ in i])
    120 
    121     def __setitem__(self, idx, o):

IndexError: list index out of range

**Comment by williamsdoug** [comment]
The above approach fails for MultiCategorical data since inner lists may be of uneven length, depending on the number of categories that a row may map to.

**Error Message Mapping Nested Ragged LIsts to Numpy Array**

<ipython-input-28-ab5b66a7aed3>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  y = np.array(y)

**Code and error message with processing ragged numpy array y**

bs = 64
n_epochs = 100
tfms  = [None, [MultiCategorize()]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits, inplace=True)
dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=bs)
dls.show_batch()

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)
<ipython-input-30-139584c54dfa> in <module>
      2 n_epochs = 100
      3 tfms  = [None, [MultiCategorize()]]
----> 4 dsets = TSDatasets(X, y, tfms=tfms, splits=splits, inplace=True)
      5 dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=bs)
      6 dls.show_batch()

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/tsai/data/core.py in __init__(self, X, y, items, sel_vars, sel_steps, tfms, tls, n_inp, dl_type, inplace, **kwargs)
    270         if len(self.tls[0]) > 0:
    271             self.types = L([ifnone(_typ, type(tl[0]) if isinstance(tl[0], torch.Tensor) else tensor) for tl,_typ in zip(self.tls, [self._xtype, self._ytype])])
--> 272             self.ptls = L([tl if not self.inplace else tl[:] if type(tl[0]).__name__ == 'memmap' else tensor(stack(tl[:])) for tl in self.tls])
    273 
    274     def __getitem__(self, it):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/tsai/data/core.py in <listcomp>(.0)
    270         if len(self.tls[0]) > 0:
    271             self.types = L([ifnone(_typ, type(tl[0]) if isinstance(tl[0], torch.Tensor) else tensor) for tl,_typ in zip(self.tls, [self._xtype, self._ytype])])
--> 272             self.ptls = L([tl if not self.inplace else tl[:] if type(tl[0]).__name__ == 'memmap' else tensor(stack(tl[:])) for tl in self.tls])
    273 
    274     def __getitem__(self, it):

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/tsai/utils.py in stack(o, axis, retain)
    264 def stack(o, axis=0, retain=True):
    265     if isinstance(o[0], torch.Tensor):
--> 266         return retain_type(torch.stack(tuple(o), dim=axis),  o[0]) if retain else torch.stack(tuple(o), dim=axis)
    267     else:
    268         return retain_type(np.stack(o, axis), o[0]) if retain else np.stack(o, axis)

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/fastai/torch_core.py in __torch_function__(self, func, types, args, kwargs)
    323         convert=False
    324         if _torch_handled(args, self._opt, func): convert,types = type(self),(torch.Tensor,)
--> 325         res = super().__torch_function__(func, types, args=args, kwargs=kwargs)
    326         if convert: res = convert(res)
    327         if isinstance(res, TensorBase): res.set_meta(self, as_copy=True)

~/anaconda3/envs/tsai2/lib/python3.8/site-packages/torch/tensor.py in __torch_function__(cls, func, types, args, kwargs)
    993 
    994         with _C.DisableTorchFunction():
--> 995             ret = func(*args, **kwargs)
    996             return _convert(ret, cls)
    997 

RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [2] at entry 58

**Comment by oguiza** [comment]
Hi @williamsdoug,
I'm sorry about the late reply. 
I've just released a new version of `tsai`and it seems to be working well now. 
This is the code I've used to test it: 

```
dsid = 'NATOPS'
bs = 64
X, y, splits = get_UCR_data(dsid, return_split=False)
y = [str(z) for z in y]
vocab = sorted(set(y))
print(X.shape)
print(type(y), type(y[0]))
print(vocab)

tfms = [None, [Categorize(vocab=vocab)]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits)
dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=[bs, bs*2])
first(dls.train)
```
and 
```
bs = 64
n_epochs = 100
y = np.random.randint(0, 5, X.shape[0]*2).reshape(-1,2).tolist()
tfms = [None, [MultiCategorize()]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits, inplace=True)
dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=bs)
dls.show_batch()
```
It'd be good if you can test it as well and confirm if it works as expected.
Thanks

**Comment by williamsdoug** [comment]
Works using 0.2.16.  Attached is my test used to verify


[TSDatset_y_datatype_tests.zip](https://github.com/timeseriesAI/tsai/files/6118175/TSDatset_y_datatype_tests.zip)
