### ISSUE TITLE
Question about which architectures can be used for which problem

### ISSUE THREAD

**Issue by karllandheer** [timeseriesAI/tsai#691]
Hello, is there a list of which arch types work for regression? I found all arch type names in the code, however when I try some, for example LSTM, it gives invalid argument for custom_head, so I assume some aren't built for regression? Or is there something I'm missing for some architectures?

**Comment by MOREDataset** [comment]
I got the same problem! They used to work before. I think there must be an issue with the new update!

**Comment by karllandheer** [comment]
Another quick question: is there an easy way to print out the training curves to a pd dataframe?

**Comment by karllandheer** [comment]
Hello, another quick question: is there a easy way to set the x and y data for a model? Say you have a model saved and want to load it and re-train on a new set of data, can this be done easily? I don't see anything like set_data

**Comment by oguiza** [comment]
Closed due to lack of response
