### ISSUE TITLE
Need user guide, api reference and better search result from documentation.

### ISSUE THREAD

**Issue by langslike** [timeseriesAI/tsai#698]
Hi I am learning to use tsai, but the documentation isn't quite handy, for example, when I read the tutoria notebooks , I encountered 
learn.fit_one_cycle(25, lr_max=1e-3)
So I went to check the usage of this function , but the search box on the documentation site didn't give much help, it just lists out many code snippets other than  detailed function usage, I think this hinders people from learning tsai. Hope for a better documentation.

**Comment by langslike** [comment]
Do I need some fastai knowledge before learning tsai? Advice is needed :)

**Comment by oguiza** [comment]
It would certainly help since `tsai` is built on top of `fastai`, so it leverages much of its functionality.
I would review the documentation in particular in regards to the Learner object and training.

**Comment by langslike** [comment]
Thanks a lot.

**Comment by oguiza** [comment]
@langslike, are you ok if I close this issue?

**Comment by langslike** [comment]
Sure.
