### ISSUE TITLE
Output score of Minirocket 

### ISSUE THREAD

**Issue by sydat2701** [timeseriesAI/tsai#706]
Hi TSAI, I am wondering if it is possible to get the exact output scores of the model when predicting, since I want to set a suitable threshold score for my own project.
Thank for your help!

**Comment by oguiza** [comment]
Hi @sydat2701,
I'm not sure what you mean by "output score". If you mean the loss for each sample there's a way to get that setting with_loss=True in learn.get_X_preds (https://timeseriesai.github.io/tsai/inference.html#learner.get_x_preds).
If you mean any metric you have used, there's no out-of-the-box functionality to do that.

**Comment by oguiza** [comment]
Closed due to lack of response.
