### ISSUE TITLE
Is there a preferred way of handling multi-label data in tsai?

### ISSUE THREAD

**Issue by williamsdoug** [timeseriesAI/tsai#71]
I'm currently training an ECG classification model with tsai where the label data includes one or more labels per recording.  Simply substituting tfms  = [None, [MultiCategorize()]] for tfms  = [None, [Categorize()]] fails.  Is there a preferred approach?

As a work-around, I am currently pre-encoding the y data.  With limitations this seems to work, but am hoping for a cleaner solution.

        ml = MultiLabel()
        y_enc = ml.encode(y_raw)
        
        print(y_raw[0], y_enc[0], ml.vocab)
        >> ['PAC'] [False False False False False  True False False False] ['1AVB', 'AFIB', 'CLBBB', 'CRBBB', 'NORM', 'PAC', 'STD_', 'STE_', 'VPC']
        
        print(X.shape, y_enc.shape, type(X), type(y_enc))
        >> (6871, 1, 1000) (6871, 9) <class 'numpy.ndarray'> <class 'numpy.ndarray'>
        
        bs = 64
        n_epochs = 100
        tfms  = [None, None]
        dsets = TSDatasets(X, y_enc, tfms=tfms, splits=splits, inplace=False)
        dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=bs)
        dls.show_batch()
        
        >> Note:  graphs display properly, except label is tensor with binary encoding of label data
        
        model = InceptionTime(dls.vars, y_enc.shape[-1])
        learn = Learner(dls, model,  #metrics=[accuracy_multi], 
                       cbs=ShowGraphCallback2(),
                       loss_func=BCEWithLogitsLossFlat())
        learn.lr_find()
      
      start = time.time()
      learn.fit_one_cycle(n_epochs, lr_max=1e-3)
      print('\nElapsed time:', time.time() - start)

--------------------------------------------
Custom pre-encoder, .encode() returns numpy array with encoded data:

        class MultiLabel:
            def __init__(self, vocab=None, n_classes=None):
                self.vocab, self.n_classes = vocab, n_classes
                self.v2i, self.i2v = None, None
                
            def encode(self, y, as_binary=True):
                if self.vocab is None:
                    self.vocab = sorted(set([str(zz) for z in y for zz in z]))
                if self.n_classes is None:
                    self.n_classes = len(self.vocab)
                if self.v2i is None:
                    self.v2i = {v:i for i, v in enumerate(self.vocab)}
                    
                if as_binary:
                    ret = np.zeros((len(y), self.n_classes), dtype=np.bool)
                    for i, row in enumerate(y):
                        for v in row:
                            ret[i, self.v2i[v]] = True
                else:
                    ret = np.zeros((len(y), self.n_classes), dtype=int)
                    for i, row in enumerate(y):
                        for v in row:
                            ret[i, self.v2i[v]] = 1
                return ret
                
            def decode(self, o):
                if self.i2v is None:
                    self.i2v = {i:v for i, v in enumerate(vocab)} 
                    
                ret = []
                for row in o:
                    ret.append([vocab[i]for i, v in enumerate(row) if v])
                return ret

**Comment by williamsdoug** [comment]
With the enhancements in the 0.2.16 release, I'm now able to get multi-label classification to work using native tsai / fastai functionality.  Since this can be a bit tricky, I've created a candidate tutorial notebook (attached) demonstrating how to perform multi-label classification with tsai.

Note:  Since many of the fastai metrics based on sklearn metrics seem to fail when handling multi-label data, I've includes a number of multi-label metrics in the tutorial notebook.

You're welcome to include the tutorial notebook and/or multi-label metrics with tsai if you think it would be of values to others.

[01a_MultiClass_MultiLabel_Classification.zip](https://github.com/timeseriesAI/tsai/files/6126893/01a_MultiClass_MultiLabel_Classification.zip)

**Comment by oguiza** [comment]
Hi @williamsdoug, 
I think it's a great idea. I'll take a look at it this weekend and will let you know.

**Comment by williamsdoug** [comment]
Updated multi-label  tutorial notebook.  Better flow, corrects error computing position weights.

[01a_MultiClass_MultiLabel_Classification.zip](https://github.com/timeseriesAI/tsai/files/6132354/01a_MultiClass_MultiLabel_Classification.zip)

**Comment by oguiza** [comment]
Hi @williamsdoug,
I'm very sorry I have not been able to take a look at your notebook. I will review it this weekend, and will provide feedback.

**Comment by oguiza** [comment]
Hi @williamsdoug,
I've already reviewed your nb, and it's great! I really like it. I've actually learned a few things!!
Having said that I've seen there are a few rough areas, where fastai/ tsai don't work as well as I'd expect. I'm going to make a few changes to make the experience more smooth and will send it to you again for your review. I think I may have it ready tomorrow.

**Comment by oguiza** [comment]
Hi @williamsdoug,
First of all, I'm really sorry for the delay, but I'm pretty busy at the moment. Thanks a lot for your patience.
I've eventually found the time to focus on your notebook. I think it's a great introduction to MultiClass and MultiLabel classification, and I'll be more than happy to add a tutorial to `tsai`. 
I've created a [gist](https://colab.research.google.com/gist/oguiza/e1d51fa0e7add2217bd16ea245b656bd/01a_multiclass_multilabel_classificationv2.ipynb). You'll see I've made some significant changes to it, as there were some rough areas in `tsai` for this type of task. With the proposed changes I think it runs more smoothly. I wasn't aware of those issues/ limitations as I'd never tried multiLabel before in `tsai`. 
You can run the notebook from start to end in less than 5 mins. 
BTW, you should sign it. It's your work, and I want to make sure you get credit for it. 
Please, take a look at the notebook (it's still in draft mode), and make any necessary changes to it. As soon as we agree to a final format, I'll make the required changes in `tsai` and we'll upload the tutorial notebook to `tsai`. 
Please, let me know your comments.

**Comment by williamsdoug** [comment]
Hi @oguiza ,

Thanks so much for all your efforts cleaning up the Multi-Label example and making the supporting TSAI extensions for ease of use.  Overall the example looks very good and thanks for your offer to include with TSAI !  

A few of items I noticed while reviewing your updated notebook:
- Typo on markdown section that starts with "Augment labels to demonstrate multi-label".  "more typically multi-lebel " should read "more typically multi-**label**"
- Under section Multi-label Classification / Build Learner and Train / function: accuracy_multi()
  - Were you thinking of including the new **accuracy_multi** in TSAI?  If so, is there any issue with the function sharing it's name with an existing fastai function?  I think your version is a fully compatible super-set, so there may not be an issue.
- Would you consider including the additional multi-label metrics defined below the heading "Define Metrics" in tsai? I realize it may beyond the strict scope of TSAI?, but could be helpful for others performing multi-label classification. 
-  Thanks for the offer to include my name in the intro, sure!   I think your name should be included as well given all your effort.  If neded, my email address is ddwilli@gmail.com

Slightly off topic, I'm hoping to submit an implementation of TSAnnotatedTensor / TSAnnotatedDataset fairly soon.  This is similar to the preprocessing function I  submitted in a recent pull request, but implements annotated window extraction as a training-time batch transform.  Feel free to ignore my current pull request  since I've slightly modified some of the code to support better re-use by the training time variant.

**Comment by oguiza** [comment]
Hi @williamsdoug, 
Please find attached the latest version of the [tutorial nb](https://colab.research.google.com/gist/oguiza/2119191cef6159bcd3274c6551356136/01a_multiclass_multilabel_tsclassification.ipynb). If you are ok with it I'll upload it to `tsai` and will share it in the fastai forum. 
Please, let me know if you find anything you'd like to modify. 
Is there any other forum or blog post where you'd like to share it? If so please, feel free to do so.

**Comment by williamsdoug** [comment]
Hi @oguiza -

I'm OK, looks great.  One comment:  Now that the metrics are included in
TSAI, so you still want to include the code in the tutorial as well
(section: Define Metrics)?

**Comment by oguiza** [comment]
There all metrics will be included in the documentation (very briefly though):https://timeseriesai.github.io/tsai/metrics

If you are interested, you can expand this. 

What I'll include as a tutorial is the nb we have prepared.

**Comment by oguiza** [comment]
Thanks @williamsdoug for preparing the PR. I've just merged it.
You are now a `tsai`official contributor!
It's been great to work with you on this tutorial notebook. I've learned  a lot about multi-label datasets in particular. And have also enhanced `tsai`, so others can benefit as well.
Please, let me know if there are any other areas you'd like to see enhanced.

**Comment by oguiza** [comment]
I'll close this issue now as this has been addressed with a new [tutorial nb](https://github.com/timeseriesAI/tsai/blob/main/tutorial_nbs/01a_MultiClass_MultiLabel_TSClassification.ipynb).

**Comment by ammargilani** [comment]
Hi, the notebook no longer works for multi-label classification. I fixed some easy errors but I'm getting this:
ValueError: Target size (torch.Size([384])) must be the same as input size (torch.Size([2304]))

**Comment by oguiza** [comment]
> Hi, the notebook no longer works for multi-label classification. I fixed some easy errors but I'm getting this:
> ValueError: Target size (torch.Size([384])) must be the same as input size (torch.Size([2304]))

Thanks for raising this @ammargilani. There's an open issue already in the log addressing this problem. We'll fix it soon.
