### ISSUE TITLE
Training is fine, but can't do prediction:  AttributeError: 'LSTM_FCN' object has no attribute 'get_X_preds'

### ISSUE THREAD

**Issue by langslike** [timeseriesAI/tsai#723]
Hi, I am using tsai to do multi-in-one-out forecasting, the training goes well, but when I do prediction, AttributeError: 'LSTM_FCN' object has no attribute 'get_X_preds' occured, I tried other models like InceptionTime, still do not work.

**this is the output of my data dls.one_batch()**
(TSTensor(samples:64, vars:136, len:20, device=cuda:0, dtype=torch.float32),
 tensor([ 0.0008,  0.0010,  0.0017, -0.0006,  0.0127,  0.0083,  0.0083,  0.0202,
         -0.0016, -0.0087,  0.0044, -0.0128, -0.0180,  0.0085, -0.0021,  0.0049,
         -0.0034,  0.0132,  0.0071, -0.0017,  0.0119, -0.0275,  0.0007, -0.0180,
         -0.0058,  0.0127,  0.0512,  0.0010,  0.0198,  0.0242, -0.0242,  0.0003,
         -0.0232,  0.0053, -0.0082,  0.0391, -0.0026, -0.0048,  0.0031,  0.0197,
          0.0063,  0.0058, -0.0189, -0.0057, -0.0273, -0.0087, -0.0216, -0.0091,
         -0.0055,  0.0309, -0.0065, -0.0021,  0.0034, -0.0033,  0.0043,  0.0137,
          0.0102,  0.0121, -0.0179, -0.0181,  0.0018,  0.0070, -0.0147,  0.0113],
        device='cuda:0', dtype=torch.float64))

**this is my model definition:**

from tsai.models.RNN_FCN import LSTM_FCN
model = LSTM_FCN(dls.vars, dls.c, shuffle = False)

from tsai.learner import ts_learner
from fastai.metrics import rmse,mae
from tsai.callback.core import ShowGraph
learn = ts_learner(dls, model,  metrics=[mae, rmse],cbs=ShowGraph())
learn.fit_one_cycle(50, lr_max=5e-4)

**the training goes well:**
epoch     train_loss  valid_loss  mae       _rmse     time   
...
47        0.000213    0.000259    0.011582  0.016097  00:00                                
48        0.000206    0.000262    0.011748  0.016197  00:00                                
49        0.000204    0.000261    0.011661  0.016145  00:00 

**this is my inference code:**
import sklearn.metrics as skm
probas, targets, preds = learn.get_X_preds(X[splits[2]])    #my dataset has train, val and test 3 parts
skm.mean_squared_error(y[splits[2]], preds, squared=False)

**this is the error code:**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[56], line 2
      1 import sklearn.metrics as skm
----> 2 probas, targets, preds = learn.get_X_preds(X[splits[2]])
      3 skm.mean_squared_error(y[splits[2]], preds, squared=False)

File [d:\Anaconda\envs\py39\lib\site-packages\fastcore\basics.py:496](file:///D:/Anaconda/envs/py39/lib/site-packages/fastcore/basics.py:496), in GetAttr.__getattr__(self, k)
    494 if self._component_attr_filter(k):
    495     attr = getattr(self,self._default,None)
--> 496     if attr is not None: return getattr(attr,k)
    497 raise AttributeError(k)

File [d:\Anaconda\envs\py39\lib\site-packages\torch\nn\modules\module.py:1207](file:///D:/Anaconda/envs/py39/lib/site-packages/torch/nn/modules/module.py:1207), in Module.__getattr__(self, name)
   1205     if name in modules:
   1206         return modules[name]
-> 1207 raise AttributeError("'{}' object has no attribute '{}'".format(
   1208     type(self).__name__, name))

AttributeError: 'LSTM_FCN' object has no attribute 'get_X_preds'

**this is my env：**
os              : Windows-10-10.0.19041-SP0
python          : 3.9.16
tsai            : 0.3.5
fastai          : 2.7.10
fastcore        : 1.5.27
torch           : 1.12.1+cu113
device          : 1 gpu (['NVIDIA GeForce GTX 1650'])
cpu cores       : 4
threads per cpu : 2
RAM             : 15.84 GB
GPU memory      : [4.0] GB

**Comment by oguiza** [comment]
Hi @langslike,
Could you please run this code and see if it works?

```python
X = np.random.rand(100, 2, 50)
y = np.random.rand(100)
splits = TSSplitter(valid_size=.2, test_size=.3, show_plot=False)(y)
tfms = [None, TSRegression()]
batch_tfms = TSStandardize(by_sample=True)
dls = get_ts_dls(X, y, splits, tfms=tfms, batch_tfms=batch_tfms)
reg = ts_learner(dls, arch="LSTM_FCN", metrics=[rmse, mae])
reg.fit_one_cycle(5, 3e-4)
probas, targets, preds = reg.get_X_preds(X[splits[2]])
probas.shape
```

**Comment by langslike** [comment]
tried install from github, still the same error. 
but I added one line to my code, everything is fine:
from tsai.all import *
I kind of resist import package in this way, cause there maybe namespace conflict and it's confusing to find the source code.But if I only import the objects I will use, I get the error

**Comment by oguiza** [comment]
You don’t need to use fastai’s import style. I don’t use it in most projects with my customers. But in that case you need to import all the necessary code. 
You can use this:

```python
from tsai.inference import get_X_preds
```

**Comment by langslike** [comment]
Well explained, thanks.
