### ISSUE TITLE
The training information was not printed

### ISSUE THREAD

**Issue by Loccret** [timeseriesAI/tsai#725]
### Description
I am trying to run the [01_Intro_to_Time_Series_Classification.ipynb](https://colab.research.google.com/github/timeseriesAI/tsai/blob/master/tutorial_nbs/01_Intro_to_Time_Series_Classification.ipynb) notebook in VS Code. The training process seems to be fine, but no training information is being printed.

### Environment
os              : Linux-5.4.0-100-generic-x86_64-with-glibc2.31
python          : 3.10.9
tsai            : 0.3.4
fastai          : 2.7.10
fastcore        : 1.5.28
torch           : 1.13.1
device          : 2 gpus (['NVIDIA A100-PCIE-40GB', 'NVIDIA A100-PCIE-40GB'])
cpu cores       : 48
threads per cpu : 2
RAM             : 93.76 GB
GPU memory      : [40.0, 40.0] GB
VSCODE     : 1.76.2

### Steps to reproduce
```Python
from tsai.all import *
import sklearn.metrics as skm

dsid = 'NATOPS' 
X, y, splits = get_UCR_data(dsid, return_split=False)
X_train, y_train, X_test, y_test  = get_UCR_data(dsid, return_split=True)
X, y, splits = combine_split_data([X_train, X_test], [y_train, y_test])
tfms  = [None, [Categorize()]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits, inplace=True)
dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid, 
                        bs=[64, 128], batch_tfms=[TSStandardize()], num_workers=0)

model = InceptionTime(dls.vars, dls.c)
learn = Learner(dls, model, metrics=accuracy)
learn.fit_one_cycle(25, lr_max=1e-3)
```

There is nothing printed.
![image](https://user-images.githubusercontent.com/29334003/228454821-0b0ce785-fdd6-46b4-8654-feb27337120d.png)

### Additional context
The expected result is: 
![image](https://user-images.githubusercontent.com/29334003/228455267-64c32c82-c3e5-494c-81ba-6e1a0217b5df.png)

**Comment by Loccret** [comment]
Hi, @oguiza,
Thank you for your great work.

1. This issue still persists when I run this fastai code.
![image](https://user-images.githubusercontent.com/29334003/228518816-2c551a22-039a-45ec-a243-5261fdd6d9e4.png)

2. I suspect that this issue may be related to VS Code, as I did not encounter this problem when running the code in my local Windows 10 Jupyter Lab environment.
```Python
from tsai.all import *
import sklearn.metrics as skm
my_setup()
```
>os              : Windows-10-10.0.19044-SP0
python          : 3.10.8
tsai            : 0.3.4
fastai          : 2.7.10
fastcore        : 1.5.27
torch           : 1.13.1
device          : 1 gpu (['NVIDIA GeForce GTX 980 Ti'])
cpu cores       : 4
threads per cpu : 2
RAM             : 31.94 GB
GPU memory      : [6.0] GB

![image](https://user-images.githubusercontent.com/29334003/228520859-ca54e4ac-0c23-444a-b93f-a612d4ec2c25.png)

But it appeared when I used VS Code.
![image](https://user-images.githubusercontent.com/29334003/228522285-d6bdb4ae-a3eb-4dbd-b147-9f1894f5a6cb.png)

**Comment by oguiza** [comment]
I'm sorry, there was a line missing in the fastai code snippet I sent you before:
```python
from fastai.vision.all import *
path = untar_data(URLs.PETS)/'images'
def is_cat(x): return x[0].isupper() 
dls = ImageDataLoaders.from_name_func('.',
    get_image_files(path), valid_pct=0.2, seed=42,
    label_func=is_cat,
    item_tfms=Resize(192))
learn = vision_learner(dls, resnet18, metrics=error_rate)
learn.fit_one_cycle(1, 1e-3) # <-- this line was missing!!
```
It'd be good to retry it again to check if the issue is in the fastai/ VSCode or tsai/VSCode integration. If the former, there's nothing I can do (but it'd be good to log a new issue with fastai).

**Comment by Loccret** [comment]
This issue still persists.
![image](https://user-images.githubusercontent.com/29334003/228534693-3b2cf206-fd0f-4816-ba38-b60e2eec8282.png)
Thank you @oguiza.
I will log a new issue with fastai.
