### ISSUE TITLE
How can I use my own split method to divide train and valid?

### ISSUE THREAD

**Issue by DennisShaw** [timeseriesAI/tsai#729]
Dear developer, I see that the splits way given in the example and in the api documentation are the 'splits' provided by tsai, if I use KFold or StratifiedKFold in sklearn to split the training and validation sets, is there a function that can bring my own splits into TSClassifer? Thanks in advance!

**Comment by oguiza** [comment]
Hi @DennisShaw,
In many examples, I'm using predefined public datasets that come with their own splits. 
However, `tsai` provides functionality to create your own splits. Which one you should use depends on the use case.
I'd recommend you to take a look at the [Splitting data section in the tsai docs](https://timeseriesai.github.io/tsai/data.validation.html).

**Comment by oguiza** [comment]
Closed due to lack of response.
