### ISSUE TITLE
Masking and Normalization order in PatchTST

### ISSUE THREAD

**Issue by ikvision** [timeseriesAI/tsai#734]
The current implementation of PatchTST is Normalization and then Masking:
https://github.com/timeseriesAI/tsai/blob/3e481d501a81bf914644f64d51179d636d62caa9/tsai/models/PatchTST.py#L376-L379
I think this can lead to an unintentional leakage - the normalization takes into account the data from the patches that are masked. 
This order of Layers can leak information from the masked data during training and therefore the reconstruction task of the masked information is easier. 
I believe that masking and later normalizing the data during training can lead to better performance on the test set.

**Comment by oguiza** [comment]
Hi @ikvision,
I'm not sure what masking you are referring to. AFAIK there's no masking in tsai`s PatchTST.

**Comment by ikvision** [comment]
@oguiza you are right, in the supervised patchTST there is no masking
I was confused by the original paper self-supervised masking operation
