### ISSUE TITLE
Endlesss OpenBLAS Warning

### ISSUE THREAD

**Issue by 1180300318** [timeseriesAI/tsai#735]
When I try to run the training function `clf.fit_one_cycle(num_epoch, lr)`,  endless

> "OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option. "

 would be printed.
the same problem with the function `clf.lr_find()` and `clf.plot_metrics()`.
Is there any solution? 
Thanks!

**Comment by oguiza** [comment]
Hi @1180300318,
With the information you have provided, I'm afraid I won't be able to help. 
Could you run `my_setup()`and paste the output here?
I have not seen that issue before. But it seems you may need to rebuild OpenBLAS as suggested [here](https://stackoverflow.com/questions/34578526/how-to-make-openblas-work-with-openmp).

**Comment by oguiza** [comment]
OpenBLAS is not part of tsai. It comes with your operating system. 
I don't know what's causing this warning. Maybe others can help?

**Comment by 1180300318** [comment]
@oguiza Ok, thanks for your reply. I will try some other solutions.
