### ISSUE TITLE
Partial fit vs fine tune?

### ISSUE THREAD

**Issue by alitirmizi23** [timeseriesAI/tsai#749]
Hi. I was wondering what would be the better setting for incremental learning? like I want to train my models as new data come in - so that they keep their previous memory as well as learn any new representations on top. Would fine tune work or partial fit? Or do I just snapshot my training data from before, and as new data come in, I just add that to the snapshot-ed data and re-train models from scratch?

**Comment by oguiza** [comment]
Hi @alitirmizi23,
it's difficult to know. A key factor though is the dataset size. 
If your dataset is not large, you may get better results retraining the model from scratch.
If it's large, you may want to "fine-tune" it. Fastai offers 2 options to do it: learn.fine_tune or learn.fit_one_cycle. The first one only trains the last layers, while the latter trains all of them. In my experience, I've usually achieved better results when training all layers.

**Comment by oguiza** [comment]
Closed due to lack of response.
