### ISSUE TITLE
00c_Time_Series_data_preparation fails under tsai 0.2.16

### ISSUE THREAD

**Issue by williamsdoug** [timeseriesAI/tsai#75]
tutorial_nbs/00c_Time_Series_data_preparation.ipynb fails using tsai 0.2.16.

Configuration:
- tsai       : 0.2.16
- fastai     : 2.2.7
- fastcore   : 1.3.19
- torch      : 1.7.0

Failing code - Cell 18:

        X, y = df2xy(df, target_col='target')
        X.shape, y.shape

Error Message:

        ---------------------------------------------------------------------------
        IndexError                                Traceback (most recent call last)
        <ipython-input-18-cd3cfd0d567c> in <module>
        ----> 1 X, y = df2xy(df, target_col='target')
              2 X.shape, y.shape
        
        ~/anaconda3/envs/tsai2/lib/python3.8/site-packages/tsai/data/preparation.py in df2xy(df, sample_col, feat_col, step_col, data_cols, target_col, to3d, splits, sort)
             41     # y
             42     if target_col:
        ---> 43         y = df[target_col][df[sample_col[0]].ne(df[sample_col[0]].shift())].values.reshape(n_samples, -1)
             44         if y.shape[-1] <= 1: y = y.ravel()
             45     else:
        
        IndexError: list index out of range

**Comment by oguiza** [comment]
Hi @williamsdoug, 
I've updated Github, and think this issue is fixed now (you'll need to git clone and not pip install). It'd be good if you can confirm it.

**Comment by williamsdoug** [comment]
Hi @oguiza , I was able to confirm that the notebook runs correctly using the tsai master branch.  The issue seems limited to the 0.2.16 release.

**Comment by oguiza** [comment]
Ok, @williamsdoug. Thanks for checking this out. I'll create a new pip release soon and will include this bug fix. I'll keep this issue open until then.
