### ISSUE TITLE
get_X_pred() : get different predicting probablity when change the input to tensor, shouldn't the result be the same?

### ISSUE THREAD

**Issue by yifeiSunny** [timeseriesAI/tsai#754]
when I input array type input, I get a different predicting probability from when I change the type of input to tensor.
![issue](https://user-images.githubusercontent.com/52452360/234756270-10533ceb-9477-4f75-bc21-fdd012f0905b.png)

I wonder why the results are different, shouldn't the results be the same?
Thanks!

**Comment by oguiza** [comment]
Thanks for raising this issue @yifeiSunny. Yes, they should be the same.
It's a bug. I'll fix it as soon as I can. 
The correct predictions are the ones generated from the numpy array.

**Comment by oguiza** [comment]
Hi @yifeiSunny , 
this issue is fixed now. You should get the correct prediction even if you pass a tensor.
