### ISSUE TITLE
The document about the plus versions of InceptionTime and TST are unreadable

### ISSUE THREAD

**Issue by qew4476** [timeseriesAI/tsai#756]
![image](https://user-images.githubusercontent.com/81016471/235272929-4eb61827-0eb2-439b-9d03-0094b9cd5daf.png)

I can understand these paragraphs.
What's the difference between the plus version and the non-plus version?

Thanks for your answer.

**Comment by vrodriguezf** [comment]
Plus versions can have any head, and therefore they can be adapted to different tasks (forecasting, regression,...)

**Comment by qew4476** [comment]
Ok! Thank you for your responds!
