### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'custom_head'

### ISSUE THREAD

**Issue by hiromis** [timeseriesAI/tsai#759]
This line results in "TypeError: __init__() got an unexpected keyword argument 'custom_head'":
```python
learn = ts_learner(dls, InceptionTime, metrics=[mae, rmse], cbs=ShowGraph())
```

![image](https://user-images.githubusercontent.com/5401333/235765957-a74a86ad-7ffd-46c7-acc2-a2248cb50bab.png)

The cause seems to be InceptionTime's __init__ takes **kwargs but InceptionModule does not. If you look at the signature the wildcard is in between InceptionTime's constructor arguments and InceptionModule's:

![image](https://user-images.githubusercontent.com/5401333/235767768-091f7bb6-8357-47d0-b24e-ecb3a1ee83fe.png)

I would assume adding **kwargs to InceptionModule's constructor, and possibly remove **kwargs from InceptionBlock and InceptionTime's constructor  will fix the issue but I am still not familiar with the code enough to say that definitely.

**Comment by oguiza** [comment]
Hi @hiromis,
Can you try using InceptionTimePlus instead of InceptionTime?
All models ending in Plus within `tsai` allow you to pass targets with different shapes. They use a custom head to recreate an output of the same shape as the target.

**Comment by hiromis** [comment]
Worked for me. Thanks!
