### ISSUE TITLE
Should get_UCR_data be changed?

### ISSUE THREAD

**Issue by limhasic** [timeseriesAI/tsai#765]
# Univariate classification with sklearn-type API
dsid = 'OliveOil'
X_train, y_train, X_valid, y_valid = get_UCR_data(dsid)   # Download the UCR dataset

# Computes MiniRocket features using the original (non-PyTorch) MiniRocket code.
# It then sends them to a sklearn's RidgeClassifier (linear classifier).
model = MiniRocketClassifier()
timer.start(False)
model.fit(X_train, y_train)
t = timer.stop()
print(f'valid accuracy    : {model.score(X_valid, y_valid):.3%} time: {t}')

...

TypeError: X cannot be None, but found None

**Comment by meowkash** [comment]
get_UCR_data is not working. It appears as if origin has changed to their own library 

https://www.timeseriesclassification.com/dataset.php
