### ISSUE TITLE
One hot encoding example

### ISSUE THREAD

**Issue by vigneshrk29** [timeseriesAI/tsai#778]
Hi,

Is there a tutorial on how to use one hot encoding or one hot encoder? I am facing a few issues which I am not able to overcome. 

Thanks,
Vignesh

**Comment by oguiza** [comment]
Hi @vigneshrk29,
Please, take a look at the documentation on TSOneHotEncoder: https://timeseriesai.github.io/tsai/data.preprocessing.html#tsonehotencoder
I would suggest you to transform your data before loading into tsai.

**Comment by oguiza** [comment]
Closed due to lack of response.
