### ISSUE TITLE
Sliding Window produces y that cannot be split using get_splits

### ISSUE THREAD

**Issue by nate123456** [timeseriesAI/tsai#78]
Hi,

I am running into some issues preparing my data using the `SlidingWindow` approach to generate samples. 

The original data is a `DataFrame` with with shape `(862607, 5)` where all columns are independent variables. I'm attempting to use the `SlidingWindow` class to shape the data so I can train a model to predict the next 60 series. My approach was to set the `horizon` to `60` (and the `window_length` to `60`) accomplish this:

``` python
window_length = 60
stride = 1
horizon = 60

X, y = SlidingWindow(window_len=window_length, stride=stride, horizon=horizon)(df)

X.shape, y.shape
```

The output is: 
``` python
((862488, 5, 60), (862488, 60, 5))
```

When I attempt to split the data into training/validation sets as per the docs, via the code:

``` python
splits = get_splits(y, valid_size=.2)
```

I get the following error:

``` python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-8e0cd2cfcc6e> in <module>()
----> 1 splits = get_splits(y, valid_size=.2, stratify=True, random_state=23, shuffle=True)

5 frames
/usr/local/lib/python3.7/dist-packages/tsai/data/validation.py in get_splits(o, n_splits, valid_size, test_size, train_only, train_perc, balance, shuffle, stratify, check_splits, random_state, show_plot, verbose)
    210     if balance: stratify = True
    211     splits = TrainValidTestSplitter(n_splits, valid_size=valid_size, test_size=test_size, train_only=train_only, stratify=stratify,
--> 212                                       balance=balance, shuffle=shuffle, random_state=random_state, verbose=verbose)(o)
    213     if check_splits:
    214         if train_only or (n_splits == 1 and valid_size == 0): print('valid == train')

/usr/local/lib/python3.7/dist-packages/tsai/data/validation.py in _inner(o, **kwargs)
    141             else:
    142                 train, valid = train_test_split(range(len(o)), test_size=vs, random_state=random_state, stratify=o if stratify_ else None,
--> 143                                                 shuffle=shuffle, **kwargs)
    144                 train, valid = toL(train), toL(valid)
    145                 if balance: train = train[balance_idx(o[train], random_state=random_state)]

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py in train_test_split(test_size, train_size, random_state, shuffle, stratify, *arrays)
   2195                      random_state=random_state)
   2196 
-> 2197         train, test = next(cv.split(X=arrays[0], y=stratify))
   2198 
   2199     return list(chain.from_iterable((_safe_indexing(a, train),

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py in split(self, X, y, groups)
   1791         to an integer.
   1792         """
-> 1793         y = check_array(y, ensure_2d=False, dtype=None)
   1794         return super().split(X, y, groups)
   1795 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    658         if not allow_nd and array.ndim >= 3:
    659             raise ValueError("Found array with dim %d. %s expected <= 2."
--> 660                              % (array.ndim, estimator_name))
    661 
    662         if force_all_finite:

ValueError: Found array with dim 3. Estimator expected <= 2.
```

If I set the `horizon` to `1`, then the shape of `X, y` from `SlidingWindow` is: 

``` python
((862547, 5, 60), (862547, 5))
```
And `get_splits` succeeds, resulting in:

![splits](https://user-images.githubusercontent.com/30061861/110984410-f5714c80-831f-11eb-834c-3f7216a156e8.PNG)

It would seem that the shape of `y` that `get_splits` is expecting is not what is generated by the `SlidingWindow` class.

Do I need to reshape `y` in some way to make it compatible with `get_splits`? Am I misusing the `get_splits` call or `SlidingWindow` in some way? Perhaps there's another splitter function that works better with a `n > 1` horizon?

Thank you!

**Comment by oguiza** [comment]
Hi @nate123456, 
I've updated the code and I think it works well now. You can test it installing from Github. It'll take some more time to have a new pip release. 
As to the y output, I've modified it when y has 3 dimensions. It makes more sense to have n_samples x n_features x n_timesteps.

**Comment by nate123456** [comment]
Thank you @oguiza, I will try it out. I appreciate all the work you're doing!

**Comment by strakehyr** [comment]
Hey Ignacio. 
get_splits used to work for me but for some reason now I am getting this error when splitting:
```
splits = get_splits(y, n_splits=1, valid_size=.2, shuffle=True)
ValueError: Found array with dim 3. Estimator expected <= 2.
```
I am feeding it a y with 3 dimensions. 
I have the following versions of libraries:
tsai - 0.2.24
fastai - 2.5.3
sklearn - 1.0.1

Might it probably be due to the newer release changing something?

**Comment by oguiza** [comment]
Hi @strakehyr,
If you have any issue, please create a new one. You may reference it to a closed issue. Otherwise you run the risk that your issue is never addressed. 
I haven't made any changes to get_splits recently. But this function uses sklearn that has recently been updated. It may be that it no longer accepts 3d input.
