### ISSUE TITLE
get_UCR_data function fails due to changed download link

### ISSUE THREAD

**Issue by trungle15** [timeseriesAI/tsai#785]
I have been working with the `tsai` library and ran into an issue when attempting to use the `get_UCR_data` function. It appears that the UCR time series data repository has changed its download link, causing the function to fail and return the message: `'It has not been possible to download the required files'`.

Looking at the source code for get_UCR_data, the current source website is defined as 
`src_website = 'http://www.timeseriesclassification.com/Downloads'`.
However, it seems the correct website should be:
 `http://www.timeseriesclassification.com/ClassificationDownloads`.

Here is the current code in the `external.py` script under `data` directory:

```
src_website = 'http://www.timeseriesclassification.com/Downloads'
decompress_from_url(f'{src_website}/{dsid}.zip', target_dir=full_tgt_dir, verbose=verbose)
```

Proposed update:

```
src_website = 'http://www.timeseriesclassification.com/ClassificationDownloads'
decompress_from_url(f'{src_website}/{dsid}.zip', target_dir=full_tgt_dir, verbose=verbose)
```

**Comment by oguiza** [comment]
Hi @trungle15,
Thank you so much for raising this issue and adding the solution! The link has indeed changed so it needs to be updated. 
I've just fixed it! And will be part of a new release that will come out soon.
