### ISSUE TITLE
implement src_key_padding_mask in TST & TSTPlus 

### ISSUE THREAD

**Issue by harisriaz17** [timeseriesAI/tsai#79]
In many time series datasets, the sequences are of variable length. Now TSAI dataloader expects fixed length time sequences. The most natural solution is to transcribe each time sequence to the maximum length in our dataset and pad zeros (or -1 or any other <PAD> token) in the extra positions. In vanilla PyTorch implementation of Transformer, there is an src_key_padding argument given to `forward` method of `torch.nn.Transformer`. Essentially, this prevents the transformer from computing self attention on the padded values (which are basically noise that we introduced and may inhibit training). 

Currently, TST and TSTPlus have no provision for src_key_padding mask of shape `batch_size x q_len`. 

I think this should be introduced in the framework.

For more details, see: [pytorch docs](https://pytorch.org/docs/stable/generated/torch.nn.Transformer.html)

Also see this specific [post](https://discuss.pytorch.org/t/how-to-add-padding-mask-to-nn-transformerencoder-module/63390/3) discussing masking.

**Comment by oguiza** [comment]
Thanks for logging this issue @harisriaz17. I won't be able to work on it now, but I'll keep it on my to-do list. 
The main issue is to find a way to pass the values that were padded to the model.

**Comment by harisriaz17** [comment]
> Thanks for logging this issue @harisriaz17. I won't be able to work on it now, but I'll keep it on my to-do list.
> The main issue is to find a way to pass the values that were padded to the model.

Hi @oguiza.  

We don't have to pass the padded values through the dataloader.

I think that we can calculate the `src_key_padding` mask inside the `forward` method of `class TST(Module)`.

In this method we get the tensor `X` of shape `[bs x nvars x q_len]` and here we can compute `src_key_padding` mask by looping over the current batch, checking each example to see where it is 0 and at the end, generating a mask of  shape `[bs x q_len]` which we can give to `z=self.encoder()` as an argument and so on.

**Comment by oguiza** [comment]
Hi @harisriaz17, thanks for your suggestion. There’s a problem with that approach, that is that the time series may contain zeros that are valid time series values. These values shouldn’t be masked. 
I’m thinking of a different approach, where you create a mixed dls to handle both the time series, and the padding mask. I’m currently working on a new API that would simplify this. I’ll try my best to have a solution to this issue soon.

**Comment by harisriaz17** [comment]
Hi @oguiza I see you've implemented `key_padding_mask` in TSTPlus. If I understand it correctly, the mask is computed based on `NaN` values in the time sequences right? So if I pad my real valued time sequences with `NaN's` in the extra positions, I should be good right?

**Comment by oguiza** [comment]
Hi @harisriaz17,
Yes, I uploaded that functionality last night. You've been very fast getting the news, as I was planning to let you know this morning :)
I haven't really tested it in depth yet. TSTPlus should now by default create a key_padding_mask for those samples in a batch where all steps (for all channels if multivariate) contain nan values. You don't need to use any special settings. 
This should work for time series with a seq_len < max_seq_len. By default, max_seq_len is set to 512, but it can be overridden and set to None. The issue is that, as you know, transformers with very long time series use a lot of memory (that's why that max_seq_len default is set to 512, to avoid OOM errors).
Bear in mind that a key padding mask would be applied to just to the end of the sequence, but to any missing values (when all channels in that step are set to nan). 
It's a very easy-to-use approach, so I hope it works well. 
It'd be great if you could test this functionality and provide feedback. 
Please, let me know if you have any questions.

**Comment by harisriaz17** [comment]
Okay, have you defined TSMask anywhere? Inside `_key_padding_mask` method of `class _TSTBackbone` I am getting error: "NameError: name 'TSMask' is not defined".

The relevant piece of code:

```
    def _key_padding_mask(self, x):
        if self.key_padding_mask and torch.isnan(x).any():
            return TSMask(torch.isnan(x).float().mean(1).bool())   # key_padding_mask: [bs x q_len]
        else: 
            return None
```

**Comment by oguiza** [comment]
Sorry about that. I've already updated it. The mask is a TSMaskTensor, but you shouldn't worry about it. 
Just make sure that you pad your time series with nan values. TSTPlus should take care of it automatically. 
You can actually see the mask created with this example: 
```
model = TSTPlus(3, 2, 10)
xb = torch.randn(8, 3, 10)
random_idxs = np.random.choice(len(xb), 3, False)
xb[random_idxs, :, -5:] = float('nan')
model.backbone._key_padding_mask(xb)[1].data, model(xb)
```
Please, let me know if this works as expected.

**Comment by harisriaz17** [comment]
> Please, let me know if this works as expected.

I tried training TSTPlus on my dataset padded with `NaN` values. The forward pass worked, however the backward pass failed (cross entropy loss went to `NaN`). 

I think gradient computation fails for those intermediate tensors containing `NaN` values. 

`dls.show_batch` also fails to visualize time sequences containing `NaN` values (but I think this is a minor issue, can be fixed later). 

If I pad my tensor with zeros and modify `the _key_padding_mask` function to create a mask based on 0's in the input instead of NaN's, then training works. Otherwise, with nan's it doesn't.

**Comment by oguiza** [comment]
Hmm. That's strange. 
I've tried this code and didn't get any error: 
```
model = TSTPlus(3, 2, 10).cuda()
xb = torch.randn(64, 3, 10).cuda()
yb = torch.randint(0, 2, (64,)).cuda()
random_idxs = np.random.choice(len(xb), 16, False)
xb[random_idxs, :, -5:] = float('nan') # nan values on all channels in last 5 steps
xb[random_idxs, 0, 1] = float('nan') # nan values on a single channel in step 1
print(torch.isnan(xb).sum()) # prints # nan values
pred = model(xb)
loss = CrossEntropyLossFlat()(pred, yb)
print(loss)
loss.backward()
#tensor(256, device='cuda:0')
#TensorBase(0.9355, device='cuda:0', grad_fn=<AliasBackward>)
```
Is there any code snippet you can send me where the code doesn't work for you?

**Comment by harisriaz17** [comment]
No, it's actually working now. It turns out that the batch transform `TSStandardize(by_var=True, verbose=True)` was causing all of the values in the entire batch to go `NaN`. I guess this is another issue now that must be fixed: mean and standard deviation for a particular channel (feature) become `NaN` when there is any `NaN` value present in the timesteps of that channel -> this was causing my whole tensor to become `NaN`.

So after removing this batch transform it works now. Thanks for adding this functionality! I think this issue can be closed (with some of these minor bugs needing fixing).

**Comment by oguiza** [comment]
Ok, I'm glad TSTPlus with auto key_padding_mask is working well. 
I've checked the TSStandardize issue and there was a minor chance of getting nan values even using torch_nanmean. I've modified the function now so hopefully, you won't see this issue again. I've already updated the repo.

**Comment by harisriaz17** [comment]
So I just checked out TSStandardize using the latest version of tsai and unfortunately I am still facing the issue: after normalizing, all values in the dataloader tensor goes to NaN.  

I am checking like this:

`
dls = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=64, batch_tfms=[TSStandardize(by_var=True, verbose=True)], num_workers=0)

x, y = next(iter(dls.train))

print(x.cpu().numpy())    # outputs tensor of all NaN values
`

**Comment by oguiza** [comment]
Hi @harisriaz17,
Let me clarify a few things:
1. I've updated TSStandardize so that it calculates mean and standard deviation ignoring nan values. **This doesn't however eliminate nan values though.**
2. If you want to eliminate nan values, you should use Nan2Value. In your case, as you are using nan values to identify padding, you don't want to use it. 
3. TSTPlus will automatically identify all padding (all nan values across all channels for every single sample). Any other nan value will be set to 0. 

I've tested this and it worked ok for me. Please, let me know if you find any issues.

**Comment by harisriaz17** [comment]
Okay! I tested it and now it works great. Thanks a lot for adding this functinality. I am closing this issue now.
