### ISSUE TITLE
Issue when using MixedDataLoaders and trying to get confusion matrix and feature importance

### ISSUE THREAD

**Issue by jorgpg5** [timeseriesAI/tsai#792]
Thank you so much for developing this tool! It is great. So I have a mixed model, and I would like to get the confusion matrix and the feature importance. Nonetheless, I'm having these errors when running the code for the confusion matrix. If you could guide me on how to fix this, I would be super happy to fix it and upload the example for future reference. My guess is that I need to copy how the DataLoader works, but I got a bit lost (Sorry, I'm still learning how this works).

I tried hardcoding the value (something very naive), and it didn't work.
![image](https://github.com/timeseriesAI/tsai/assets/70129680/7946f3d6-4b14-4c78-8f36-8628125c80cd)

I also get this error when running the code for feat importance, which is more convoluted than the last one.
![image](https://github.com/timeseriesAI/tsai/assets/70129680/d705e52d-3771-499f-9886-e1457b2e15ec)

Do you have any suggestions or guidance to fix it from my end? I'll be thrilled to update the code, upload another example notebook, or update the one that already has it.

Cheers.

**Comment by oguiza** [comment]
@jorgpg5 , 
That is a limitation of using MixedDataLoaders.
I'm not sure what's your use case, but you may be interested in some new (still experimental) functionality we have added to handle different types of data. You can find more information here: https://timeseriesai.github.io/tsai/models.multimodal.html

**Comment by jorgpg5** [comment]
Thank you for your answer, Ignacio. I'm sorry, I have one more question. Would it be possible to get the confusion matrix and feature importance using the new functionality (multimodal approach)?

**Comment by oguiza** [comment]
Hi @jorgpg5,
I haven't tested it yet, but I believe it'd be possible.
If you test it, it'd be great if you let us know if it works or not.

**Comment by jorgpg5** [comment]
Will do! I'll come back with the test results in a few days. Thank you!

**Comment by oguiza** [comment]
Closed due to lack of response.
