### ISSUE TITLE
the difference between TSRegression() and TSForecasting()

### ISSUE THREAD

**Issue by David-Ttao** [timeseriesAI/tsai#793]
hello dear creator，I use my dataset to forcast the futher data, but i find the demo use "TSRegression()" not "TSForecasting()", and I also find 
![image](https://github.com/timeseriesAI/tsai/assets/82387560/7facc69e-9c9a-4861-bc8c-5113376b1ac4)
but i dont know why, and what should i need note when i use my data in forecast task。
thanks，my question maybe is a little naive，sorry i am just a beginner，thanks

**Comment by Sandy4321** [comment]
good question !

**Comment by oguiza** [comment]
Hi @Sandy4321,
There's no difference. It's just to make it easy to remember based on the task you are performing. You might use ToFloat too.

**Comment by David-Ttao** [comment]
thanks for your reply!
