### ISSUE TITLE
how to change muti-vars into single vars?

### ISSUE THREAD

**Issue by David-Ttao** [timeseriesAI/tsai#794]
![image](https://github.com/timeseriesAI/tsai/assets/82387560/855b9e88-bffc-405d-9ae4-56adacf6539d)
hello，i change the get_ts_dls like this to change the X(n,vars,fcst_history),y(n,vars,fcst_horizon) into single vars, i mean i want to split the dataset with the num of vars,but failed.for example: 
![image](https://github.com/timeseriesAI/tsai/assets/82387560/646c194c-106c-4b82-b850-345f8b14bd53)
the X shape is (16813, 7, 512) , how can i change it into (16813,1,512)  and combine the 7 x(16813,1,512) in a dataloader. THANKS !

**Comment by oguiza** [comment]
Hi @David-Ttao,
I'm sorry but I don't understand your question. If you want to have a single channel, you should prepare your data that way before loading it into tsai.

**Comment by David-Ttao** [comment]
> 

thanks for reply, i mean if i have many single channel datasets, how to train them  in the same time ?

like i have said, X(n,vars,fcst_history), the X shape is (16813, 7, 512) , how can i change it into (16813,1,512) and combine the 7 x(16813,1,512) in a dataloader. because i want to train one model  
with muti-datasets, so i need spilit defferent model into same dim, so that they can use same model's input.  such as i have two datasets A and B, after the function Prepare_forecasting_data(), A's X is (1000,4,512),Y (1000,4,96). B‘s X is (400,6,512), Y（400,6,96）.but the model only have one input dim. so i want come A and B'X and Y as one dataset. so I change A's X (1000 * 4, 1, 512),Y(1000 * 4, 1, 96) B's X(400 * 6,1,512),Y(400 * 6,1,96). so the model input dim can set as"1". and **what should i do** can concat A and B's X,Y into one dataloader, so the model can read two datasets train_data. the question confused me too long, thanks for your reply,thank sincerely. or if u have other methods to train one model in the many datasets?

**Comment by oguiza** [comment]
I'm sorry, but you can't do that with `tsai`. The number of channels is a fixed variable that cannot be changed from epoch to epoch or batch to batch.

**Comment by oguiza** [comment]
Closed due to lack of response.
