### ISSUE TITLE
BUG with get_UCR_data error fix

### ISSUE THREAD

**Issue by gitgash** [timeseriesAI/tsai#795]
UCR changed url.
In file data/external.py change line 2198 to:
src_website = 'http://www.timeseriesclassification.com/ClassificationDownloads'

**Comment by mesner** [comment]
I assume this will fix the following?

> It has not been possible to download the required files

**Comment by oguiza** [comment]
Hi @gitgash,
This is a duplicate issue of  #785. It was already fixed 2 weeks ago.
You'll need to upgrade tsai to the latest github release until I create a new release (planning to do within the next few days). You can use: 
```python
pip install git+https://github.com/timeseriesAI/tsai.git
```
Based on this I'll close this issue.

**Comment by eromoe** [comment]
@oguiza 
Installed latest `pip install git+https://github.com/timeseriesAI/tsai.git` 
Still got `It has not been possible to download the required files` when `get_classification_data('LSST', split_data=False)`

**Comment by ffanz01** [comment]
> @oguiza Installed latest `pip install git+https://github.com/timeseriesAI/tsai.git` Still got `It has not been possible to download the required files` when `get_classification_data('LSST', split_data=False)`

Same issue, no clue at the moment.

**Comment by oguiza** [comment]
Hi @gitgash, @mesner, @eromoe, @ffanz01,
The link was initially updated, but they changed it again, causing a new issue. It's been fixed again in the GitHub version.
In the future, It's better to create a new issue instead of adding comments to a closed one.
