### ISSUE TITLE
how to get list all data sets available to download  and how to get them 

### ISSUE THREAD

**Issue by Sandy4321** [timeseriesAI/tsai#796]
may you help 
how to get list all data sets available to download  and how to get them 
especially 
30 multivariate classification datasets
15 regression datasets
62 forecasting datasets

for example 
how to guess that I need to use 
from tsai.data.external import get_Monash_regression_data

**Comment by oguiza** [comment]
Hi @Sandy4321, 
Please take a look at the documentation on external data:  https://timeseriesai.github.io/tsai/data.external.html
There's no single list of all datasets in `tsai` because the different datasets have different uses.

**Comment by Sandy4321** [comment]
great thanks

**Comment by oguiza** [comment]
Closed based on the previous response.
