### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by awalece04ku** [timeseriesAI/tsai#798]
I just tried the example code written on the home page (https://github.com/timeseriesAI/tsai), and it is **NOT** working.
https://github.com/timeseriesAI/tsai
Could you please check and fix this? 
If the example code is not working, it would be hard to use.

Thanks for paying attention in advance.

**Comment by oguiza** [comment]
Hi  @awalece04ku,
Thanks for raising this issue.
There was an issue when importing data. It's fixed now. I have rerun all code snippets in the landing page and they work well, but you'll need to update tsai to the latest version in github (I will create a new pip release soon). For now, you can use:
```python
pip install git+https://github.com/timeseriesAI/tsai.git
```

**Comment by hmate9** [comment]
Installing via git works but it is very slow. Any chance the new pip version is getting deployed soon?

**Comment by oguiza** [comment]
Hi @hmate9,
2 comments:
1. The concept of "very slow" is subjective. I've tested it in Cola and it takes 5s to install from pip vs 16s to do it from GitHub.
2. Please, read my previous response: "but you'll need to update tsai to the latest version in github (I will create a new pip release soon)"

**Comment by oguiza** [comment]
I've just created a new release (0.3.7) that fixes this issue. Based on this, I'll close it.
