### ISSUE TITLE
All notebooks fail to execute in Google Colab

### ISSUE THREAD

**Issue by ldselvera** [timeseriesAI/tsai#82]
Installation gives the following issues:
ERROR: torchtext 0.9.0 has requirement torch==1.8.0, but you'll have torch 1.7.1 which is incompatible.
ERROR: googleapis-common-protos 1.53.0 has requirement protobuf>=3.12.0, but you'll have protobuf 3.11.2 which is incompatible.
ERROR: google-api-core 1.26.1 has requirement protobuf>=3.12.0, but you'll have protobuf 3.11.2 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.

from tsai.all import *
gives the following issues:
---------------------------------------------------------------------------

ContextualVersionConflict                 Traceback (most recent call last)

<ipython-input-13-0cd012edf11b> in <module>()
      1 import tsai
----> 2 from tsai.all import *
      3 print('tsai       :', tsai.__version__)
      4 print('fastai     :', fastai.__version__)
      5 print('fastcore   :', fastcore.__version__)

12 frames

/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    775                 # Oops, the "best" so far conflicts with a dependency
    776                 dependent_req = required_by[req]
--> 777                 raise VersionConflict(dist, req).with_context(dependent_req)
    778 
    779             # push the new requirements onto the stack

ContextualVersionConflict: (scipy 1.4.1 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('scipy>=1.5'), {'stumpy'})

**Comment by oguiza** [comment]
Hi @ldselvera,
This issue is due to the fact that Google Colab is now using Pytorch 1.8 while fastai is still on Pytorch 1.7. I expect this to be resolved soon. In any case, I’ll make a change in the notebooks to separate pip install from imports. 
To resolve this you’ll need to:

* pip install everything you need
* Restart the Runtime
* Continue with the imports

Please, let me know if this works.

**Comment by nate123456** [comment]
I have this issue as well- my standard procedure is to install using the same code in the notebooks.:

```python
stable = False # True: latest version, False: stable version
import sys
ISCOLAB = 'google.colab' in sys.modules
if ISCOLAB:
    if stable: 
        !pip install tsai -Uqq
    else:
        !pip install -Uqq git+https://github.com/timeseriesAI/tsai.git
```

After which I receive various mismatching package version errors. I resolve it by restarting the runtime, then running the same code again, which always succeeds.

**Comment by dnth** [comment]
I replaced this code block
```
stable = False # True: latest version, False: stable version
import sys
ISCOLAB = 'google.colab' in sys.modules
if ISCOLAB:
    if stable: 
        !pip install tsai -Uqq
    else:
        !pip install -Uqq git+https://github.com/timeseriesAI/tsai.git
```
with this 
`!pip install tsai`

and everything works again in Colab

**Comment by oguiza** [comment]
I have updated all tutorial notebooks to make installation more clear:
```
# ## NOTE: UNCOMMENT AND RUN THIS CELL IF YOU NEED TO INSTALL/ UPGRADE TSAI
# stable = False # True: latest version from github, False: stable version in pip
# if stable: 
#     !pip install -Uqq tsai
# else:      
#     !pip install -Uqq git+https://github.com/timeseriesAI/tsai.git@master
# ## NOTE: REMEMBER TO RESTART YOUR RUNTIME ONCE THE INSTALLATION IS FINISHED
```
