### ISSUE TITLE
UCR Dataset download link

### ISSUE THREAD

**Issue by irosyadi** [timeseriesAI/tsai#827]
The UCR dataset download link should be changed from http://www.timeseriesclassification.com/ClassificationDownloads to http://www.timeseriesclassification.com/aeon-toolkit

**Comment by oguiza** [comment]
Thanks for providing a solution @irosyadi!
Duplicate of #765 which is now fixed.

**Comment by lelouch514** [comment]
I switched to the new link but still report error? Is there a new update?
