### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape' when running colab tutorial

### ISSUE THREAD

**Issue by 12869741** [timeseriesAI/tsai#836]
cell:
# dataset id
dsid = 'NATOPS' 
X, y, splits = get_UCR_data(dsid, return_split=False)
X.shape, y.shape, splits
output:
It has not been possible to download the required files
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-e4c74b1103d5>](https://localhost:8080/#) in <cell line: 4>()
      2 dsid = 'NATOPS'
      3 X, y, splits = get_UCR_data(dsid, return_split=False)
----> 4 X.shape, y.shape, splits

AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by MohitBurkule** [comment]
It has been solved in #795 
Install with 
`pip install git+https://github.com/timeseriesAI/tsai.git`
