### ISSUE TITLE
add support for session windows

### ISSUE THREAD

**Issue by geoHeil** [timeseriesAI/tsai#85]
TSAI has great support for sliding windows in the data preprocessing methods: https://github.com/timeseriesAI/tsai/blob/62e9348d9e29a6b5f628879bd77056c11db5c0ab/tsai/data/preparation.py#L119

Ideally support for (event-) session based windows can be added as outlined in https://stackoverflow.com/questions/66783615/transform-time-series-to-event-window-sessions

**Comment by williamsdoug** [comment]
I'm seeing a similar need in the context of beat-level ECG analysis where the events are a series of beat QRS positions.  Could be either sliding windowing or random event selection, where the returned window would be some specified region prior and after the event.  Ideally one could apply other transforms such as TSRandomTimeScale afterwards.

**Comment by oguiza** [comment]
I understand your request, but for the moment this falls outside the scope of `tsai`. 
A few helper functions like SlidingWindow were included to show how data needs to be prepared. But data preparation is not in the scope of `tsai` as there are many different needs, that would take a lot of time. 
Having said that I'm happy to analyze any PR you prepare that may sort this issue as long as it's general enough to meet others' needs.

**Comment by williamsdoug** [comment]
Attached is a prototype implement of a  preprocessing function that, given a set of signals and events, returns a windowed signal snippet for each event.  Code is currently prototype, but my plan to eventually submit a pull request after restructuring to use in an nbdev environment.    Hope to eventually implement similar code as a training-time Transform as well.

If close enough to your session use-case, I would be happy collaborate to extend.

````
preprocess_sliding_event_window(X, y, events, splits=None, folds=None, width=100, offset=None, limit=None, include_empty=False)
    Inputs:
          X: signal data, can be uniform or ragged, with or without channels 
          y: label data 
          events: List of event positions  for each signal  
          width: window size in samples
          offset: start of window vs event, window centered by default
          limit: max windows per signal, 
          include_empty: include randomly selected window if no events
          splits: splits data, will be mapped to windows data if present
          folds:  folds data, will be mapped to windows data if present
          *note: splits and folds are mutually exclusive
    Returns:
          X_win: windows signals 
          y_win: labels for windowed signals
          folds_win or folds_win: Optional, depending on if splits or folds specified
````

[proto_event_preprocessing.zip](https://github.com/timeseriesAI/tsai/files/6216080/proto_event_preprocessing.zip)

**Comment by geoHeil** [comment]
Same here. I have a prototype. However, so far it is only in pandas and not in tsai/fastai format.

```
region_id = 'region_id'
device_id = 'device_id'
time_value = 'time_value'
trigger_in_region = 'trigger_in_region'
label = 'label'

import pandas as pd
import numpy as np
from tqdm import tqdm
tqdm.pandas()

df = pd.DataFrame({
    region_id:[1,1,1,1,1,1,1,1,1,1,1,1, 1,1,1,1,1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3,3,3,3,3],
    device_id:[1,1,1,1,1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3,3,3,3,3, 4,4,4,4,4,4,4,4,4,4,4,4],
    time_value:[1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12, 1,2,3,4,5,6,7,8,9,10,11,12, 1,2,3,4,5,6,7,8,9,10,11,12],
    trigger_in_region:[0,0,1,0,0,0,1,0,0,0,0,1, 0,0,1,0,0,0,1,0,0,0,0,1, 0,0,0,0,1,1,0,0,0,0,1,0, 0,0,0,0,0,0,0,0,0,0,0,0,],
    label: [0,0,1,0,0,0,0,0,0,0,0,1, 0,0,0,0,0,0,1,0,0,0,0,1, 0,0,0,0,1,0,0,0,0,0,1,0, 0,0,0,0,0,0,0,0,0,0,0,0,]
})

from numpy import random
df['value_1']=random.randint(100, size=(df.shape[0]))
df['value_2']=random.randint(20, size=(df.shape[0]))

display(df.head())


start_points = df[df.trigger_in_region > 0][[region_id, time_value]].drop_duplicates()
start_points


time_int = 4


def sessionize_pd(df, time_interval):
    session_results = []


    def handle_sessionization_pd_umap(x):
        region = x[region_id].unique()[0]
        trigger_times = x[time_value].unique()

        region_df = df[df[region_id] == region]

        for individual_trigger in tqdm(trigger_times):
            previous_records_inclusive_time_value = individual_trigger - time_interval
            session_candidate_devices = region_df[(region_df[time_value] >= previous_records_inclusive_time_value) & (region_df[time_value] <= individual_trigger)]
            record_counts = session_candidate_devices.groupby([device_id]).size()
            device_ids_in_range_with_enough_records = record_counts[record_counts == time_interval + 1].index.values

            real_combined_sessions = session_candidate_devices[session_candidate_devices[device_id].isin(device_ids_in_range_with_enough_records)]

            session_labels = real_combined_sessions[(real_combined_sessions[time_value] == individual_trigger)].groupby([device_id])[label].max().rename('session_label').reset_index()
            real_combined_sessions = real_combined_sessions.merge(session_labels, on=[device_id])
            real_combined_sessions['trigger'] = f'[{previous_records_inclusive_time_value}-{individual_trigger}]'
            
            #print(real_combined_sessions.columns)
            #display(real_combined_sessions.head())
            
            real_combined_sessions = real_combined_sessions.drop([trigger_in_region, label], axis=1)
            session_results.append(real_combined_sessions)
    

    _ = start_points.groupby(['region_id']).progress_apply(handle_sessionization_pd_umap)

    return pd.concat(session_results).sort_values([region_id, 'trigger', time_value, 'session_label', device_id]).reset_index(drop=True)

s = sessionize_pd(df, time_int).set_index([region_id, 'trigger', device_id, time_value])
s
```

> Notice how in my case the sessionization logic is much more complex. 

Perhaps it would be possible to pass a higher order function for the business logic of the sessionization procedure?

**Comment by williamsdoug** [comment]
Thanks @geoHeil, after looking at your use-case I seem some commonality but significant differences.   Here's my initial analysis.

**Summary of key differences:**
- Input Data Format
- Unique labels per trigger vs common label per-training example
- Multiple triggers per window (with multiple labels) vs window for each trigger

**Input Data Format:**
- Your case:   Data organized as multiple rows in pandas dataframe, with highest level grouping  being region_id
- My case:  Multi-dimensional numpy array, **data[<*patient_id*>, <*ecg_chan*>, <*time_value*>]**  

One could map your pandas data into a similar numpy array as: **data[<*region_id*>, <*device_id*> ,<*value_xx*>, <*time_value*>]** where **<*device_id*> <*value_xx*>** could be flattened as **<*device_id* x *value_xx*>**.  Note:  it appears that *trigger_in_region* and *label* contain redundant data as specified in pandas format since data common across all devices within the same region. 
- **trigger_in_region[<*region_id*>,<*time_value*>]**
- **label[<*region_id*> <*time_value*>]**

**Unique labels per trigger**:  This would be a useful extension for my case as well (per-beat ECG ).  Would be relatively east to implement, and I'll explore incorporating in my code.

**Multiple triggers per window**: 
This is where a custom window function might work.  For example, a window might start at the first trigger and subsume any subsequent triggers that occur withing the same window duration.  Also, the formal of the label outputs would need to change to include multiple labels (most likely as label value per-time within window).

**Comment by williamsdoug** [comment]
@geoheil: Correction to my earlier analysis:  It appears that in your use-case  there are a variable number of device_id per region, so may be difficult to map into a channel dimension as proposed above.

**Comment by geoHeil** [comment]
Hi,

no, trigger in region and label are not equal. And indeed, it could should/ will soon be reformatted by me into a NumPy array to be compatible with the TSAI way of handling data.


Correct there is a variable number of devices in a region. Given a trigger (= failure) the network should identify the root cause given the sequence of the last couple of observations of data.

**Comment by williamsdoug** [comment]
@geoHeil: Based on your feedback it doesn't appear possible to combine both of our use-cases into a single solution.  I will move any further discussion of my use-case to a different thread, if needed,  to keep this issue focused on your use-case.

**Comment by oguiza** [comment]
Hi @geoHeil, since you opened this issue. how would you like to proceed with it?

**Comment by geoHeil** [comment]
When looking at my code - but also at the one from @williamsdoug I think 1) there is a need for this and 2) the needs are very diverse.

Perhaps it would be possible to have an API where a higher-order function could be passed? And a couple of example functions would be given in the documentation?

**Comment by oguiza** [comment]
Hi @geoHeil,
As I said, I'm open to any proposal that is generic to cover common needs. Feel free to submit your ideas.

**Comment by geoHeil** [comment]
I will work on the implementation in the coming weeks and update you when I have more. But I guess @williamsdoug might be faster.

**Comment by geoHeil** [comment]
After looking into it a bit more I believe tha transforming the data (pivoting/unstacking) is curcial. Thus the minimal example would translate over to:


```
region_id = 'region_id'
device_id = 'device_id'
time_value = 'time_value'
trigger_in_region = 'trigger_in_region'
label = 'label'

import pandas as pd
import numpy as np
from tqdm import tqdm
tqdm.pandas()

df = pd.DataFrame({
    region_id:[1,1,1,1,1,1,1,1,1,1,1,1, 1,1,1,1,1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3,3,3,3,3],
    device_id:[1,1,1,1,1,1,1,1,1,1,1,1, 2,2,2,2,2,2,2,2,2,2,2,2, 3,3,3,3,3,3,3,3,3,3,3,3, 4,4,4,4,4,4,4,4,4,4,4,4],
    time_value:[1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12, 1,2,3,4,5,6,7,8,9,10,11,12, 1,2,3,4,5,6,7,8,9,10,11,12],
    trigger_in_region:[0,0,1,0,0,0,1,0,0,0,0,1, 0,0,1,0,0,0,1,0,0,0,0,1, 0,0,0,0,1,1,0,0,0,0,1,0, 0,0,0,0,0,0,0,0,0,0,0,0,],
    label: [0,0,1,0,0,0,0,0,0,0,0,1, 0,0,0,0,0,0,1,0,0,0,0,1, 0,0,0,0,1,0,0,0,0,0,1,0, 0,0,0,0,0,0,0,0,0,0,0,0,]
})

from numpy import random
df['value_1']=random.randint(100, size=(df.shape[0]))
df['value_2']=random.randint(20, size=(df.shape[0]))

display(df.head())

start_points = df[df.trigger_in_region > 0][[region_id, time_value]].drop_duplicates()
start_points


time_int = 4


def sessionize_pd(df, time_interval):
    session_results = []


    def handle_sessionization_pd_umap(x):
        region = x[region_id].unique()[0]
        trigger_times = x[time_value].unique()

        region_df = df[df[region_id] == region]

        for individual_trigger in tqdm(trigger_times):
            previous_records_inclusive_time_value = individual_trigger - time_interval
            session_candidate_devices = region_df[(region_df[time_value] >= previous_records_inclusive_time_value) & (region_df[time_value] <= individual_trigger)]
            record_counts = session_candidate_devices.groupby([device_id]).size()
            device_ids_in_range_with_enough_records = record_counts[record_counts == time_interval + 1].index.values

            real_combined_sessions = session_candidate_devices[session_candidate_devices[device_id].isin(device_ids_in_range_with_enough_records)]

            session_labels = real_combined_sessions[(real_combined_sessions[time_value] == individual_trigger)].groupby([device_id])[label].max().rename('session_label').reset_index()
            real_combined_sessions = real_combined_sessions.merge(session_labels, on=[device_id])
            real_combined_sessions['hour_row_index_cumcount'] = real_combined_sessions.groupby(device_id).cumcount(ascending=False)
            real_combined_sessions['trigger'] = f'[{previous_records_inclusive_time_value}-{individual_trigger}]'
            
            
            real_combined_sessions = real_combined_sessions.drop([trigger_in_region, label], axis=1)
            session_results.append(real_combined_sessions)
    

    _ = start_points.groupby(['region_id']).progress_apply(handle_sessionization_pd_umap)

    return pd.concat(session_results).sort_values([region_id, 'trigger', device_id, time_value, 'session_label']).reset_index(drop=True)

s = sessionize_pd(df, time_int).set_index([region_id, 'trigger', device_id, 'session_label', 'hour_row_index_cumcount']).drop([time_value], axis=1)
s

s.unstack().reset_index().set_index([region_id, 'trigger', device_id])
```

Where the data now looks like this:
![image](https://user-images.githubusercontent.com/1694964/114129172-5465b980-98fe-11eb-9581-879ddba46456.png)



When thinking about it more and more, I must agree it might be better to instead provide a tutorial notebook instead than changing the API. I.e. to depict how to easily create custom session windows in a TSAI compatible format.

This also brings me to my main question:

Given the data is already transformed in the pivoted format (one row per session window and including a session label): how can I put this into a TSAI compatible numpy array/data loader/dls?

**Comment by geoHeil** [comment]
@oguiza do you think that this column-oriented approach (1 row per device and trigger) is suitable for TSAI?

**Comment by oguiza** [comment]
Hi @geoHeil,
I'm afraid I'm unable to answer your question since I don't fully understand what you are trying to do. 
What I understand is that you need to use a custom sliding window based on some trigger instead of the generic one.  Based on what you have shared, it seems you have achieved it. 
If your question is how to transform the pivot table into a numpy array you can use in `tsai`, can't you just do this: 

```
new_df = s.unstack().reset_index().set_index([region_id, 'trigger', device_id])
X = np.stack(np.split(new_df[['value_1', 'value_2']].values, 2, axis=1)).transpose(1,0,2)
y = new_df['session_label'].values
X.shape, y.shape
```
This would create an X array of shape (7, 2, 5) and y of shape (7,). You can load them to create a dataloader.
Isn't this what you need or am I missing anything?

**Comment by tcapelle** [comment]
Let me take a look @oguiza.

I think the best approach is not to preprocess all possible items `X, y` as this does not scale well and does not fit memory in most cases.
What I have done from my side is create a `Dataset` object that will `getitem` on the fly, with the configured params windows. I understand the issues about why you want to slide on the groups where data is contiguous, and I have dealt with the same type of problems. But preprocessing should be dont externally, and `tsai` should build the DL pipeline for you.  My ds class is the followwing:
```python
class WindowDataset:
    "A class to make windowed selection on a DataFrame"
    def __init__(self, df, x_cols=None, y_cols=None, bsteps=2, fsteps=1, overlap=None, shift=1, debug=False):
        store_attr(but='x_cols,y_cols')
        self.x_cols, self.y_cols = listify(x_cols), listify(y_cols)
        self.overlap = ifnone(overlap, 0)
        self.check_validity()
    
    def check_validity(self):
        assert self.x_cols and self.y_cols, "plaease give me some x_cols y_cols to play with"
        assert len(self.df) > self.bsteps + self.fsteps, "the dataset is empty"
        
    
    @property
    def iloc(self):
        "A better iloc, that supports col names"
        return _Iloc(self)
    
    def _get_x(self, idx):
        i,j = (idx-self.bsteps+1,idx+1)
        return self.iloc[i:j, self.x_cols]
    
    def _get_y(self, idx):
        i,j = (idx+1+self.overlap, idx+self.fsteps+1)
        return self.iloc[i:j, self.y_cols]
    
    def __getitem__(self, idx):
        "get on pair (x,y) at idx"
        if idx >= len(self):
            raise Exception(f"idx out of bounds, len(ds)={len(self)}, python indexing starts at zero.")
        idx = (idx*self.shift + self.bsteps-1)
        x, y = self._get_x(idx), self._get_y(idx)
        if self.debug:
            display_xy(x,y)
        return x, y
    
    def __len__(self):
        return (len(self.df) - self.fsteps - self.bsteps ) // self.shift + 1
```
What I do is I create one of this `WindowDatasets` for each group of data (I think is  what you call sessions) and then stack all the dataset together using the `MetaDataset` class that was recently added to `tsai`.
```python
from itertools import chain

class MetaDataset:
    " A dataset capable of indexing mutiple datasets at the same time!"
    def __init__(self, datasets):
        self.datasets = datasets
        self.mapping = self._mapping_simple()
    
    def __len__(self):
        return sum([len(ds) for ds in self.datasets])
    
    def _mapping(self):
        relative_idxs = [range_of(r) for r in self.datasets]
        idx_pairs = [list(zip(len(r)*[i], r)) for i,r in enumerate(relative_idxs)]
        return list(chain.from_iterable(idx_pairs))
    
    def _mapping_simple(self):
        res = []
        for i,ds in enumerate(self.datasets):
            for j in range_of(ds):
                res.append((i,j))
        return res
    
    def __getitem__(self, idx):
        ds_idx, rel_idx = self.mapping[idx]
        return self.datasets[ds_idx][rel_idx]
```
So my preprocessing is external, where I do a bunch of `pandas` magic to create one pandas data frame for earch event (session) and so I can safely slide window inside each of this periods. For me, is mostyl intra-day data, and don't want to slide across different days. I also find missing timeindexes (skips) and beak contiguous predios. At the end, I have a bunch of pandas dataframes that will generated the Datasets that will finally stack in a big `MetaDataset`.

**Comment by geoHeil** [comment]
@tcapelle you are completely correct - but this also seems more complex. Probably too complex for now for what I need, especially given the fact that these window transformations are rather vectorized using the groupby operator.

Still, I think it would be really useful to contribute something back to TSAI, at least a jupyter notebook outlining how these custom session windows could be used with a little bit of preprocessing. But I agree, that something more scalable as proposed by you would be even better. However, it is still not fully clear for me to map my preprocessing logic into this setting.

@oguiza , indeed you are correct. These transformations would yield the right numpy arrays. And I should be able to continue from there using the regular TSAI magic.

**Comment by geoHeil** [comment]
@tcapelle no I think the session is different than the window in the sense that considering panel data I would understand that your window is applicable for a 1-panel item whereas for me 1 session in a group can contain a different number of panel items (devices). And for each of these devices within a session (out of the full time-series) I want to get the window.

**Comment by oguiza** [comment]
Hi @geoHeil, 
Does your proposed solution work? Can I close this issue?
I'm not keen on adding a tutorial nb about custom data preparation, because there are many different scenarios, and it's impossible to generalize. We've seen 2 examples discuss here and you couldn't get to an agreement on what was required, because the needs were different.
That's why I prefer to keep data preparation limited to just standard cases that most users will require, and explain what is the required input format.

**Comment by geoHeil** [comment]
sounds good for me.
