### ISSUE TITLE
It has not been possible to download the required files - get_classification_data func

### ISSUE THREAD

**Issue by dimtsiakm** [timeseriesAI/tsai#850]
I am trying to get data using get_classification_data function with no success.
I run the following command and I am getting a message that I can't download the required files.
`
X, y, splits = get_classification_data('ECG200', split_data=False)`

**Comment by Xie-Hao0818** [comment]
Me too!

**Comment by oguiza** [comment]
This is an error that may occasionally occur when the server where the data are stored is down for any reason. There's nothing I can do to sort out the issue. Data doesn't belong to tsai. In tsai we just built some convenience functions to make it easy to download data. 
I 'm not able to fix this.
