### ISSUE TITLE
get_long_term_forecasting_data fails 

### ISSUE THREAD

**Issue by laiki** [timeseriesAI/tsai#861]
Hi, 
I tried to run the example 15_PatchTST_a_new_transformer_for_LTSF and failed when trying to download data forecasting data access to the url defined in external.py
    url = 'https://cloud.tsinghua.edu.cn/d/e1ccfff39ad541908bae/files/?p=%2Fall_six_datasets.zip&dl=1'
seems invalid
Best Regards
Laiki

**Comment by JacobDu** [comment]
I encountered the same problem.
I found that the dataset can be obtained through this link.
`https://drive.google.com/drive/folders/1ZOYpTUa82_jCcxIdTmyr0LXQfvaM9vIy`
Hope it helps you.

**Comment by laiki** [comment]
thanks
